### ISSUE TITLE
Using OpenJDK 12

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#1929]
When I execute `gradlew cli:run --args="--info scanner -f JSON -i <project folder> -o <output folder>"`

I get this error
```
λ gradlew cli:run --args="--info scanner -f JSON -i <project folder> -o <output folder>\ort\analyzer"
Configuration on demand is an incubating feature.

> Configure project :
Reckoned version: 0.1.0-beta.0.4184+20191104T115247Z

> Task :cli:run FAILED
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got scanner
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:788)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at com.here.ort.Main.run(Main.kt:115)
        at com.here.ort.Main.main(Main.kt:99)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cli:run'.
> Process 'command 'C:\Program Files\Java\jdk-12.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 13s
```

**Comment by sschuberth** [comment]
The sub-commands for ORT are verbs that are named after the respective module. That is, if you want to run the scanner, the sub-command is called "scan".

**Comment by CleanHit** [comment]
> 
> 
> The sub-commands for ORT are verbs that are named after the respective module. That is, if you want to run the scanner, the sub-command is called "scan". Also see the output of `./gradlew cli:run --args="--help"`.

My bad, I thought I was running it with the `analyze` command :-).
