### ISSUE TITLE
Scanner stopped due to GC overhead limit exceeded error.

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2370]
I ran the scanner with analyzer result file.
and it stopped due to GC overhead limit exceeded error.
Falling back to fetching all refs.
```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.StringCoding$StringEncoder.encode(StringCoding.java:300)
        at java.lang.StringCoding.encode(StringCoding.java:344)
        at java.lang.String.getBytes(String.java:918)
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.isFile(File.java:882)
        at com.here.ort.spdx.SpdxUtilsKt$calculatePackageVerificationCode$2.invoke(SpdxUtils.kt:110)
        at com.here.ort.spdx.SpdxUtilsKt$calculatePackageVerificationCode$2.invoke(SpdxUtils.kt)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:133)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at com.here.ort.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForDirectory(SpdxUtils.kt:168)
        at com.here.ort.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:371)
        at com.here.ort.scanner.scanners.ScanCode.scanPath(ScanCode.kt:331)
        at com.here.ort.scanner.LocalScanner.scanPackage(LocalScanner.kt:324)
        at com.here.ort.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:75)
        at com.here.ort.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:195)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

How can I set the proper Xmx heap size?
It might be occurred the result file is too big. Or if not, please check the cause of the error.

**Comment by fb33** [comment]
Hello, you can try this kind of env var : 
`JAVA_OPTS=-Xms512M -Xmx4g -XX:MaxMetaspaceSize=2g -Dkotlin.daemon.jvm.options='-Xmx2g'`

**Comment by dd-lge** [comment]
@fb33,
Thank you! I'll try again with the env var that you commented.

**Comment by sschuberth** [comment]
Maybe we can reduce memory consumption by more consequently using sequences instead of lists in that code. I'll investigate.

**Comment by sschuberth** [comment]
@dd-lge could you please check whether https://github.com/heremaps/oss-review-toolkit/pull/2372 makes a difference?

**Comment by sschuberth** [comment]
@dd-jy, did you see this issue ever happening again with the latest `master`?

**Comment by dd-jy** [comment]
I tested again with the latest master. The GC overhead limit error didn't occurred. But another issue was found.
`11:14:40.150 [ScanCode-1] ERROR java.lang.Object - Could not download 'NPM::coin-server:0.0.1': DownloadException: Download failed for 'NPM::coin-server:0.0.1'.
Suppressed: DownloadException: No VCS URL provided for 'NPM::coin-server:0.0.1'. Please define the "repository" in the package.json file, see: https://docs.npmjs.com/files/package.json#repository,
Suppressed: DownloadException: No source artifact URL provided for 'NPM::coin-server:0.0.1'.
Exception in thread "main" java.io.FileNotFoundException: /home/osc/user-test/osc_2397_coin/scanner-result_0625/downloads/NPM/unknown/walkdir/0.4.0/test/dir/symlinks/dir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/loop/dir1/sdir2/sdir1/sdir2/loop/dir1/sdir2/sdir1/sdir2/loop/dir2/loop/dir1/sdir2/loop/dir2/loop/dir2/loop/dir2/loop/dir1/sdir2/loop/dir1/sdir2/loop/dir2/loop/dir2/loop/file (Too many levels of symbolic links)`

**Comment by sschuberth** [comment]
@dd-jy, I've moved that to a new issue then.
