### ISSUE TITLE
Can't scan Python project？

### ISSUE THREAD

**Issue by freedom-wy** [oss-review-toolkit/ort#2422]
i clone a project from github

`https://github.com/freedom-wy/binaryanalysis.git`

i use ort analyze

./cli/build/install/ort/bin/ort analyze -i test/binaryanalysis/ -o ../test -f JSON

error

`
```
Analyzing project path:
	/home/user1/ort/test/binaryanalysis
Exception in thread "main" com.vdurmont.semver4j.SemverException: Invalid version (no major version): virtualenv 20.0.14 from /home/user1/requests_packages/venv/lib/python3.6/site-packages/virtualenv/__init__.py
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:20)
	at com.vdurmont.semver4j.Requirement.isSatisfiedBy(Requirement.java:549)
	at org.ossreviewtoolkit.utils.CommandLineTool$DefaultImpls.checkVersion(CommandLineTool.kt:125)
	at org.ossreviewtoolkit.analyzer.managers.VirtualEnv.checkVersion(Pip.kt:83)
	at org.ossreviewtoolkit.utils.CommandLineTool$DefaultImpls.checkVersion$default(CommandLineTool.kt:121)
	at org.ossreviewtoolkit.analyzer.managers.Pip.beforeResolution(Pip.kt:219)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:212)
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$$inlined$use$lambda$1$1$1.invokeSuspend(Analyzer.kt:143)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

`

**Comment by sschuberth** [comment]
Could you please copy & paste the output from running `virtualenv --version` on a regular command prompt?

**Comment by freedom-wy** [comment]
@sschuberth 
virtualenv == 20.0.14

now i use 15
it's ok

**Comment by sschuberth** [comment]
Could you please still post the *output* of running `virtualenv --version` with version 20.0.14 in a terminal?

**Comment by sschuberth** [comment]
Nevermind, just duid it myself:

    $ virtualenv --version
    virtualenv 20.0.14 from /usr/local/lib/python2.7/dist-packages/virtualenv/__init__.pyc

I'll add compatibility for that version.

**Comment by freedom-wy** [comment]
@sschuberth  when i use 20.0.14 virtualenv，not work
when i use 15.1.0 virtualenv it's ok
python version 3.6.9
