### ISSUE TITLE
Evaluator "No value passed for parameter 'packageConfigurationProvider'" Error.

### ISSUE THREAD

**Issue by CleanHit** [oss-review-toolkit/ort#2471]
I've pooled the latest **master commit 754403** and when I ran:
```bash
ort --info evaluate -i ./scan-result.yml -o ./evaluation/v1 --rules-file ./rules.kts --license-configuration-file ./licenses.yml
```
I get:
```java
Exception in thread "main" javax.script.ScriptException: No value passed for parameter 'packageConfigurationProvider'
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:104)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
        at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:93)
        at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
        at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.ossreviewtoolkit.utils.ScriptRunner.run(ScriptRunner.kt:68)
        at org.ossreviewtoolkit.evaluator.Evaluator.run(Evaluator.kt:67)
        at org.ossreviewtoolkit.commands.EvaluatorCommand$run$evaluatorRun$2.invoke(EvaluatorCommand.kt:166)
        at org.ossreviewtoolkit.commands.EvaluatorCommand$run$evaluatorRun$2.invoke(EvaluatorCommand.kt:55)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.ossreviewtoolkit.commands.EvaluatorCommand.run(EvaluatorCommand.kt:169)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:162)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:188)

```
I didn't change my environment settings and everything was working 4-5 weeks ago.
```
OS: Fedora 31
JAVA_HOME = <path_to_openJDK>/jdk-12-0-2
ANDROID_HOME = <path_to_SDK>/AndroidSDK
```

**Comment by sschuberth** [comment]
This should already have been fixed by https://github.com/oss-review-toolkit/ort/pull/2379/commits/4d5b0b77022cea3d1697a215b3534591b0fc55ba.



> I've pooled the latest **master commit 754403**

Actually, I'm unable to find such a commit in `master`. Please ensure you're really on *our* latest `master` (not e.g. `master` of some fork of yours) and you've properly built ORT from that commit.

**Comment by CleanHit** [comment]
Thanks for the link :). I've been using an old _rules.kts_ file as a base for my needs and it didn't have `packageConfigurationProvider` in it, after adding it the error went away. 

In the long run it might be better to use the **Gitflow-Workflow** approach together with this repository, so such changes won't get pass silently. Because this project gets only bigger and bigger :).
