### ISSUE TITLE
Too many levels of symbolic links in NPM package

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#2779]
I tested again with the latest master. The GC overhead limit error didn't occurred. But another issue was found.
`11:14:40.150 [ScanCode-1] ERROR java.lang.Object - Could not download 'NPM::coin-server:0.0.1': DownloadException: Download failed for 'NPM::coin-server:0.0.1'.
Suppressed: DownloadException: No VCS URL provided for 'NPM::coin-server:0.0.1'. Please define the "repository" in the package.json file, see: https://docs.npmjs.com/files/package.json#repository,
Suppressed: DownloadException: No source artifact URL provided for 'NPM::coin-server:0.0.1'.
Exception in thread "main" java.io.FileNotFoundException: /home/osc/user-test/osc_2397_coin/scanner-result_0625/downloads/NPM/unknown/walkdir/0.4.0/test/dir/symlinks/dir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/loop/dir1/sdir2/sdir1/sdir2/loop/dir1/sdir2/sdir1/sdir2/loop/dir2/loop/dir1/sdir2/loop/dir2/loop/dir2/loop/dir2/loop/dir1/sdir2/loop/dir1/sdir2/loop/dir2/loop/dir2/loop/file (Too many levels of symbolic links)`

_Originally posted by @dd-jy in https://github.com/oss-review-toolkit/ort/issues/2370#issuecomment-649202247_

**Comment by dd-jy** [comment]
@sschuberth 
It is litaral output on the console.

**Comment by sschuberth** [comment]
Ok, so [walkdir seems to deliberately contain a symbolic link loop for testing](https://github.com/soldair/node-walkdir/tree/v0.4.0/test/dir/symlinks) that ScanCode runs into when scanning the source code.

**Comment by sschuberth** [comment]
I can't reproduce the issue with `master`. Which version (Git commit) of ORT are you using? Does it already contain https://github.com/oss-review-toolkit/ort/pull/2748, or can you verify whether that PR fixes the issue?

**Comment by dd-jy** [comment]
I tested commit version(a9451c6c312812b6f7db98bb7392930a46f0f76b). And it already contains #2748.
But I reproduce this issue again. But the log is a little different.

Falling back to fetching all refs.
Exception in thread "main" java.io.FileNotFoundException: /home/osc/user-test/osc_2397_coin/scanner-result_0629/downloads/NPM/unknown/walkdir/0.4.0/test/dir/symlinks/dir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/sdir1/sdir2/loop/dir1/sdir2/sdir1/sdir2/sdir1/sdir2/loop/dir2/loop/dir2/loop/dir1/sdir2/loop/dir2/loop/dir1/sdir2/sdir1/sdir2/sdir1/sdir2/loop/dir2/loop/dir2/sdir1/sdir2/loop/dir2/loop/file (Too many levels of symbolic links)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt.sha1sum(SpdxUtils.kt:84)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt.access$sha1sum(SpdxUtils.kt:1)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt$calculatePackageVerificationCode$1.invoke(SpdxUtils.kt:78)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt$calculatePackageVerificationCode$1.invoke(SpdxUtils.kt)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:716)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:746)
        at kotlin.sequences.SequencesKt___SequencesKt$sorted$1.iterator(_Sequences.kt:517)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForStrings(SpdxUtils.kt:163)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForFiles(SpdxUtils.kt:78)
        at org.ossreviewtoolkit.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForDirectory(SpdxUtils.kt:123)
        at org.ossreviewtoolkit.scanner.scanners.ScanCode.generateSummary$scanner(ScanCode.kt:363)
        at org.ossreviewtoolkit.scanner.scanners.ScanCode.scanPathInternal(ScanCode.kt:323)
        at org.ossreviewtoolkit.scanner.LocalScanner.scanPackage(LocalScanner.kt:330)
        at org.ossreviewtoolkit.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:77)
        at org.ossreviewtoolkit.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$4.invokeSuspend(LocalScanner.kt:197)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by sschuberth** [comment]
Hmm, something does not seem to match up here:

> at org.ossreviewtoolkit.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForFiles(SpdxUtils.kt:78)
> at org.ossreviewtoolkit.spdx.SpdxUtilsKt.calculatePackageVerificationCodeForDirectory(SpdxUtils.kt:123)

In commit a9451c6, line 123 of `SpdxUtils.kt` does not contain a call to `calculatePackageVerificationCodeForFiles`. Can you please check once more that you've not only checked out commit a9451c6, but also built ORT from it?

**Comment by dd-jy** [comment]
There was a build issue. I built again and tested it.
And this issue was not reproduced. I am sorry for my mistake.

**Comment by sschuberth** [comment]
I'm glad it works for you now!
