### ISSUE TITLE
No source artifact URL provided for 'Gradle::testlicense:'

### ISSUE THREAD

**Issue by kneep** [oss-review-toolkit/ort#2837]
Hi. I created an Android App sample project named testlicense and scanned with ort (latest master) and I got the error in the title. I'm quite confused because testlicense is a project name, not an artifact. Here is the log:
```
PS D:\work\ort> .\cli\build\install\ort\bin\ort.bat --debug scan -i D:\work\result\analyzer-result.yml -o D:\work\scan\
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/D:/work/ort/cli/build/install/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'scan' under Java 11.0.7 on Windows 10 with
/    |    \    |   \ |    |    ORT_DATA_DIR = C:\Users\13817587682\.ort
\_______  /____|_  / |____|    OS = Windows_NT
        \/       \/
More environment variables:
COMSPEC = C:\WINDOWS\system32\cmd.exe
GOPATH = C:\Users\13817587682\go

Using scanner 'ScanCode' with storage 'FileBasedStorage with XZCompressedLocalFileStorage backend'.
Local file storage has 86 scan results files.
22:27:21.003 [main] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'D:\work\scancode-toolkit\scancode.bat --version' in 'D:\work\scancode-toolkit'...
22:27:26.164 [main] DEBUG org.ossreviewtoolkit.utils.ProcessCapture - ScanCode version 3.1.2
22:27:26.164 [main] DEBUG org.ossreviewtoolkit.utils.ProcessCapture -
22:27:26.193 [main] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'D:\work\scancode-toolkit\scancode.bat --version' in 'D:\work\scancode-toolkit'...
22:27:30.414 [main] DEBUG org.ossreviewtoolkit.utils.ProcessCapture - ScanCode version 3.1.2
22:27:30.414 [main] DEBUG org.ossreviewtoolkit.utils.ProcessCapture -
22:27:30.459 [FileBasedStorage with XZCompressedLocalFileStorage backend-3] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.activity:activity:1.1.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (3/162).
22:27:30.459 [FileBasedStorage with XZCompressedLocalFileStorage backend-4] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.annotation:annotation:1.0.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (4/162).
22:27:30.459 [FileBasedStorage with XZCompressedLocalFileStorage backend-2] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.activity:activity-ktx:1.1.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (2/162).
22:27:30.459 [FileBasedStorage with XZCompressedLocalFileStorage backend-1] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Gradle::testlicense: and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (1/162).
22:27:30.459 [FileBasedStorage with XZCompressedLocalFileStorage backend-5] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.annotation:annotation:1.1.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (5/162).
22:27:30.507 [FileBasedStorage with XZCompressedLocalFileStorage backend-4] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.appcompat:appcompat-resources:1.1.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --i22:27:30.511 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Maven:androidx.annotation:annotation:1.0.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag), scanning package in thread 'ScanCode-1' (4/162).
22:27:30.516 [FileBasedStorage with XZCompressedLocalFileStorage backend-1] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Maven:androidx.appcompat:appcompat:1.1.0 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag) (7/162).
22:27:30.519 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source code for 'Maven:androidx.annotation:annotation:1.0.0'.
22:27:30.522 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Gradle::testlicense: and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag), scanning package in thread 'ScanCode-1' (1/162).
22:27:30.526 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source code for 'Gradle::testlicense:'.
22:27:30.528 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download 'Gradle::testlicense:' sources to 'D:\work\scan\downloads\Gradle\unknown\testlicense\unknown' from VCS...
22:27:30.532 [ScanCode-1] DEBUG org.ossreviewtoolkit.downloader.Downloader - VCS download failed for 'Gradle::testlicense:': DownloadException: No VCS URL provided for 'Gradle::testlicense:'. Please make sure the release POM file includes the SCM connection, see: https://docs.gradle.org/current/userguide/publishing_maven.html#example_customizing_the_pom_file
22:27:30.539 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source artifact for 'Gradle::testlicense:' from ...
22:27:30.543 [ScanCode-1] DEBUG org.ossreviewtoolkit.downloader.Downloader - Source artifact download failed for 'Gradle::testlicense:': DownloadException: No source artifact URL provided for 'Gradle::testlicense:'.
22:27:30.548 [ScanCode-1] ERROR org.ossreviewtoolkit.scanner.LocalScanner - Could not download 'Gradle::testlicense:': DownloadException: Download failed for 'Gradle::testlicense:'.
Suppressed: DownloadException: No VCS URL provided for 'Gradle::testlicense:'. Please make sure the release POM file includes the SCM connection, see: https://docs.gradle.org/current/userguide/publishing_maven.html#example_customizing_the_pom_file,
Suppressed: DownloadException: No source artifact URL provided for 'Gradle::testlicense:'.
22:27:30.550 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - Finished scanning Gradle::testlicense: in thread 'ScanCode-1' (1/162).
Exception in thread "main" java.lang.IllegalArgumentException: The output directory 'D:\work\scan\downloads\Maven\androidx.annotation\annotation\1.0.0' must not contain any files yet.
        at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:115)
        at org.ossreviewtoolkit.downloader.Downloader.download$default(Downloader.kt:112)
        at org.ossreviewtoolkit.scanner.LocalScanner.scanPackage(LocalScanner.kt:296)
        at org.ossreviewtoolkit.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:77)
        at org.ossreviewtoolkit.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$3.invokeSuspend(LocalScanner.kt:199)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sschuberth** [comment]
See `The output directory 'D:\work\scan\downloads\Maven\androidx.annotation\annotation\1.0.0' must not contain any files yet`. You simply need to remove that directory (or all files within it) manually if you want to rerun ORT, as ORT by default refuses to overwrite any existing output files.

**Comment by sschuberth** [comment]
> I'm quite confused because testlicense is a project name, not an artifact.

The ids for artifacts / packages and projects are basically the same in ORT, and ORT also scans the project's source code, not only the ones of the artifacts / packages.

**Comment by kneep** [comment]
@sschuberth Hi Sebastian. Thanks for the hint. The scan is rerunning now. I thought the old directories would be used to check where it were before the exceptiont, seemed not the case.

BTW, how does ort reuse the results of scanned artifacts on interrupted scans and new scan on a updated project? Is there any documents for detailed behaviors?

**Comment by sschuberth** [comment]
No matter whether a scan has been interrupted or completed, already scanned packages are not scanned again if a [scan storage](https://github.com/oss-review-toolkit/ort#storage-backends) is configured (by default a storage based on local files is used).
