### ISSUE TITLE
Could not delete file after trying svn failed

### ISSUE THREAD

**Issue by kneep** [oss-review-toolkit/ort#2846]
```
12:46:58.749 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Maven:com.google.guava:failureaccess:1.0.1 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag), scanning package in thread 'ScanCode-1' (106/162).
12:46:58.750 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source code for 'Maven:com.google.guava:failureaccess:1.0.1'.
12:46:58.752 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download 'Maven:com.google.guava:failureaccess:1.0.1' sources to 'D:\work\scan\downloads\Maven\com.google.guava\failureaccess\1.0.1' from VCS...
12:46:58.753 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Using VcsInfo(type=Git, url=https://github.com/google/guava.git, revision=, resolvedRevision=null, path=).
12:46:58.787 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Could not detect VCS type from type name 'Git'.
12:47:01.454 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Subversion' from URL 'https://github.com/google/guava.git'.
12:47:44.909 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Adding Subversion revision 'tags/failureaccess-v1.0.1' (guessed from version '1.0.1') as a candidate.
12:47:44.911 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Trying revision candidate 'tags/failureaccess-v1.0.1' (1 of 1)...
14:12:07.116 [ScanCode-1] WARN  org.ossreviewtoolkit.downloader.vcs.Subversion - Failed to update the Subversion working tree at 'D:\work\scan\downloads\Maven\com.google.guava\failureaccess\1.0.1' to revision 'tags/failureaccess-v1.0.1':
SVNException: svn: E175002: Read timed out
svn: E175002: REPORT request failed on '/google/guava.git/!svn/vcc/default'
Caused by: SSLException: Read timed out
Caused by: SocketTimeoutException: Read timed out
14:12:07.118 [ScanCode-1] DEBUG org.ossreviewtoolkit.downloader.Downloader - VCS download failed for 'Maven:com.google.guava:failureaccess:1.0.1': DownloadException: Subversion failed to download from URL 'https://github.com/google/guava.git'.
14:12:08.557 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Maven:com.google.code.gson:gson:2.8.5 and ScannerDetails(name=ScanCode, version=3.1.2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp --license-diag), scanning package in thread 'ScanCode-1' (104/162).
14:12:08.558 [ScanCode-1] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download source code for 'Maven:com.google.code.gson:gson:2.8.5'.
Exception in thread "main" java.io.IOException: Could not delete file 'D:\work\scan\downloads\Maven\com.google.guava\failureaccess\1.0.1\.svn\svn.b8309ba0-c25b-4315-b77e-cba783f5f6da.tmp'.
        at org.ossreviewtoolkit.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:153)
        at org.ossreviewtoolkit.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:143)
        at org.ossreviewtoolkit.utils.ExtensionsKt.safeDeleteRecursively(Extensions.kt:143)
        at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:135)
        at org.ossreviewtoolkit.downloader.Downloader.download$default(Downloader.kt:112)
        at org.ossreviewtoolkit.scanner.LocalScanner.scanPackage(LocalScanner.kt:296)
        at org.ossreviewtoolkit.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:77)
        at org.ossreviewtoolkit.scanner.LocalScanner$scanPackages$2$invokeSuspend$$inlined$map$lambda$1$3.invokeSuspend(LocalScanner.kt:199)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: java.lang.IllegalArgumentException: The output directory 'D:\work\scan\downloads\Maven\com.google.code.gson\gson\2.8.5' must not contain any files yet.
                at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:115)
                ... 9 more
```

Seems like this line failed:
```kotlin
    // Clean up any left-over files (force to delete read-only files in ".git" directories on Windows).
    outputDirectory.safeDeleteRecursively(force = true)
```
Could svn.b8309ba0-c25b-4315-b77e-cba783f5f6da.tmp be still locked down by other threads after a connection timeout?

**Comment by sschuberth** [comment]
Looks like the first error is `Could not detect VCS type from type name 'Git'`, which sounds odd, but probably happens because you don't have the `git` CLI in your PATH. Because of that, ORT tries Subversion next, and somewhat seems to succeed to use GitHub's Subversion bridge, but then runs into a timeout.

**Comment by sschuberth** [comment]
Regarding

    Could not delete file 'D:\work\scan\downloads\Maven\com.google.guava\failureaccess\1.0.1\.svn\svn.b8309ba0-c25b-4315-b77e-cba783f5f6da.tmp'.

I guess you're on Windows if you see this. Could you maybe try running a tool like [LockHunter](https://lockhunter.com/) on that file to rule out a third-party process like [TortoiseSVN](https://tortoisesvn.net/) is locking that file?

**Comment by kneep** [comment]
@sschuberth I have no TortoiseSVN installed, nor other clients. ORT should be using the svn client libaray. Is it possible that the svn client libaray is still doing some bail out in another thread after it throws an SVNException? I suspected that but found no such documented behavior. After the failure, I can manually delete the file in question. 

BTW, can we have an option to try artifact source before vcs?

**Comment by sschuberth** [comment]
> Is it possible that the svn client libaray is still doing some bail out in another thread after it throws an SVNException?

I don't think so. SVNKit itself it single-threaded AFAIK, and no two ORT threads should lock the same SVN working tree. While quickly skimming through the code I did not find a possible cause for this.

> BTW, can we have an option to try artifact source before vcs?

This has been a topic of past internal discussions. We prefer VCS because of the better provenance data, but see how trying source artifacts first could make sense in some scenarios. I'll file an issue from your comment for it.

**Comment by kneep** [comment]
@sschuberth I just tried replace the ```delete()``` with ```Files.delete(toPath())```, which produces more informative Exceptions. The exception says the file is being used by others (something like that, because the error message is localized). I'll see if I can dig deeper.

**Comment by sschuberth** [comment]
> I'll see if I can dig deeper.

Any progress here, @kneep?

**Comment by kneep** [comment]
@sschuberth I'm very sorry. I'm currently not working on it.

**Comment by kneep** [comment]
@sschuberth Sure. Thanks.
