### ISSUE TITLE
How to use .ort.yml 

### ISSUE THREAD

**Issue by dd-jy** [oss-review-toolkit/ort#2902]
Hi, I want to exclude some pattern paths (ex, test/**) while scanning.
In the docs directory, it could be possible to use .ort.yml.
and then I wrote .ort.yml file.
```
excludes:
  paths:
  - pattern: "test/**"
    reason: "TEST_OF"
    comment: "Packages for test only."
```

And I ran the ORT.
`ort -c ~/.ort.yml scan -i source/Downloader/unknown/simplejson/unknown/ -o test -s scancode -f json`

But it occurred the below error message.
```
Exception in thread "main" com.typesafe.config.ConfigException$Parse: /home/osc/.ort.yml: 2: Expecting end of input or a comma, got ':' (if you intended ':' to be part of a key or string value, try enclosing the key or value in double quotes)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:535)
        at com.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:648)
        at com.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260)
        at com.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:180)
        at com.typesafe.config.impl.Parseable.parseValue(Parseable.java:174)
        at com.typesafe.config.impl.Parseable.parse(Parseable.java:299)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:689)
        at com.typesafe.config.ConfigFactory.parseFile(ConfigFactory.java:703)
        at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion.load(OrtConfiguration.kt:50)
        at org.ossreviewtoolkit.OrtMain.run(OrtMain.kt:127)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:187)

```

The .ort.yml file has the same format as the ORT's .ort.yml file.
Can you help me?

**Comment by sschuberth** [comment]
The `.ort.yml` is supposed to reside in the root of the project you analyze and will be automatically used if present. It's different from the ORT configuration file which uses HOCON format and gets passed via the `-c` command line option.

**Comment by dd-jy** [comment]
Thank you for replay.
Is there any way to set the path of .ort.yml?

**Comment by sschuberth** [comment]
Well, the *analyze* command has the `--repository-configuration-file` option to specify an alternate location for `.ort.yml`. The excludes read from that file are then "baked" into the intermediate ORT result file created by the analyzer, from which they are used by the *scan* command when running it with `--ort-file` instead of `--input-path`. So there's currently no way to specify an alternate location for `.ort.yml` when using the *scan* command stand-alone with the `--input-path` option.

**Comment by dd-jy** [comment]
Thank you for kindly reply!
