### ISSUE TITLE
Proxy settings have no effect when analyzing certain maven poms

### ISSUE THREAD

**Issue by oheger-bosch** [oss-review-toolkit/ort#2905]
I am running ort in a corporate network with the following settings:

```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'analyze' under Java 11.0.6 on Linux with
/    |    \    |   \ |    |    ORT_DATA_DIR = /var/lib/jenkins/workspace/ort-pipeline@tmp/.ort
\_______  /____|_  / |____|    http_proxy = http://172.17.0.1:3128
        \/       \/
More environment variables:
https_proxy = http://172.17.0.1:3128
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go

```
The project to analyze is [Apache Commons Configuration](https://commons.apache.org/proper/commons-configuration/) 2.7. This is not a multi-module project, but it refers to an external parent pom (commons parent, which is shared by all Apache Commons components).

When analyzing the pom the proxy settings are obviously not effective; resolution of the parent pom fails with an error message as below:

```
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.apache.commons:commons-configuration2:2.7: Could not transfer artifact org.apache.commons:commons-parent:pom:50 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Name or service not known and 'parent.relativePath' points at wrong local POM @ line 22, column 11
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:397)
	at org.ossreviewtoolkit.analyzer.managers.Maven.beforeResolution(Maven.kt:102)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:224)
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$$inlined$use$lambda$1$1$1.invokeSuspend(Analyzer.kt:141)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by oheger-bosch** [comment]
Obviously, the problem manifests itself only under very specific conditions: The maven environment (as configured by _settings.xml_) must be pretty initial; especially it must not define any repositories. In this constellation, Maven Central is used as the only repository, and here the proxy settings are not applied; therefore, resolving of the parent pom fails.

(This may well be considered an inconsistency in the way, Maven deals with remote repositories. The relevant class is `org.apache.maven.project.ProjectModelResolver`. This class is passed a list with uninitialized repositories at construction time. During processing of _settings.xml_, the repositories defined there are added to the instance via the _addRepository()_ method. In this method the repository is eventually assigned its proxy, which is required to resolve artifacts properly. But if no repositories are found in _settings.xml_, the single Maven Central repository is never assigned a proxy.)

A possible fix is to explicitly inject the proxy via the `MavenRepositorySystem` class into all remote repositories when a maven execution request is created in `MavenSupport`.
