### ISSUE TITLE
Exception in OrtResult.kt

### ISSUE THREAD

**Issue by NicolasToussaint** [oss-review-toolkit/ort#2911]
ORT scanner phase crashes when scanning on a non VCS folder:

```
./cli/build/install/ort/bin/ort --info --config /data/ort-home/ort.json scan --download-dir /data/ort-home/download/<project>_Licensee_20200806_105641 --ort-file /data/ort-home/projects/<project>/010-analyze/analyzer-result.json --scanner Licensee --output-dir /data/ort-home/projects/<project>/030-scan_Licensee_20200806_105641
```
At the end, it crashes with the following Exception:
```
09:35:18.791 [main] INFO  org.ossreviewtoolkit.model.OrtResult - Computing excluded projects which may take a while...
Exception in thread "main" java.lang.IllegalArgumentException: The VcsInfo(type=, url=https://<my-git-url>, revision=, resolvedRevision=null, path=) of project 'NPM::<project>:3.1.0-SNAPSHOT' cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=), vcsProcessed=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=), nestedRepositories={}, config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]), resolutions=Resolutions(issues=[], ruleViolations=[]), curations=Curations(licenseFindings=[]))).
        at org.ossreviewtoolkit.model.OrtResult.getFilePathRelativeToAnalyzerRoot(OrtResult.kt:267)
        at org.ossreviewtoolkit.model.OrtResult.getDefinitionFilePathRelativeToAnalyzerRoot(OrtResult.kt:253)
        at org.ossreviewtoolkit.model.config.Excludes.findPathExcludes(Excludes.kt:53)
        at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:102)
        at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:43)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.ossreviewtoolkit.model.OrtResult.getProjects(OrtResult.kt)
        at org.ossreviewtoolkit.model.OrtResult.getProject(OrtResult.kt:339)
        at org.ossreviewtoolkit.scanner.Scanner.scanOrtResult(Scanner.kt:121)
        at org.ossreviewtoolkit.commands.ScannerCommand.run(ScannerCommand.kt:161)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:170)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:179)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:174)
```

I make a pretty dirty workaround by hardcoding the path in case `relativeProjectVcsPath.getValue` returns NULL, here: https://github.com/oss-review-toolkit/ort/blob/master/model/src/main/kotlin/OrtResult.kt#L267
```
264     fun getFilePathRelativeToAnalyzerRoot(project: Project, path: String): String {
265         var vcsPath1 = relativeProjectVcsPath.getValue(project.id)
266         if (vcsPath1 == null) {
267                 csPath1 = "/data/<project-path>"
268         }
269         val vcsPath = vcsPath1
270 
271         requireNotNull(vcsPath) {
272             "The ${project.vcsProcessed} of project '${project.id.toCoordinates()}' cannot be found in $repository."
273         }
```

The folder I am scanning is a git clone, in which the root `.git` has been removed.
Maybe that's not supported, and it wouldn't be a big deal, but there may also be a way to avoid the crash, and continue scanning.

**Comment by NicolasToussaint** [comment]
I keep getting  Exceptions, I think when no SCM is configured in the project.
An example below with a Maven project, stored in a git repository, run via Docker.

The `pow.xml` is simple Sonar plugin, and contains no `<scm>` block.
I get this Exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: 
The VcsInfo(type=Git, url=https://github.com/SonarSource/parent-oss.git, revision=, 
resolvedRevision=null, path=) of project 'Maven:org.sonar.mobsf:mobsf-sonar-plugin:1.3'
cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=),
vcsProcessed=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=), nestedRepositories={},
config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]),
resolutions=Resolutions(issues=[], ruleViolations=[]), curations=Curations(licenseFindings=[]))).
```

When I add an `<scm>` block in the projet: (url replaced by `git-url`)
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.sonarsource.parent</groupId>
        <artifactId>parent</artifactId>
        <version>50</version>
    </parent>
(...)
    <scm>
      <connection>scm:git:https://git-url.git</connection>
      <url>https://git-url</url>
    </scm>
    <modules>
```

Then the Exception happens with the URL I just added:
```
Exception in thread "main" java.lang.IllegalArgumentException:
The VcsInfo(type=Git, url=https://git-url.git, revision=,
resolvedRevision=null, path=) of project 'Maven:org.sonar.mobsf:mobsf-sonar-plugin:1.3'
cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=),
vcsProcessed=VcsInfo(type=, url=, revision=, resolvedRevision=null, path=), nestedRepositories={},
config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]),
resolutions=Resolutions(issues=[], ruleViolations=[]), curations=Curations(licenseFindings=[]))).
```

I guess I should be able to get a scan result, even if not SCM URL is provided, at least with a declared license list ?

**Comment by sschuberth** [comment]
> The folder I am scanning is a git clone, in which the root `.git` has been removed.
> Maybe that's not supported, and it wouldn't be a big deal, but there may also be a way to avoid the crash, and continue scanning.

Running specifically the *Scanner* on a "plain" directory that is not version controlled indeed is something that is not well tested. I remember it used to work at some point, but we were actually considering to remove support for that use-case altogether, as it makes hard to determine what the "provenance" of such a directory is.

But I agree we should either support or not support it, and not crash.

**Comment by NicolasToussaint** [comment]
> Running specifically the Scanner on a "plain" directory that is not version controlled indeed is something that is not well tested. I remember it used to work at some point, but we were actually considering to remove support for that use-case altogether, as it makes hard to determine what the "provenance" of such a directory is.

Ok, thanks for the info, it make sense.

But in my second post is a scan of an original, unmodified git clone, and I have an exception pointing at the same place

**Comment by sschuberth** [comment]
> But my second post is a scan of an original, unmodified git clone, and I have an exception pointing at the same place

Did you happen to pass a relative directory to ORT on the CLI in that case? I believe we could be missing to ensure using absolute paths somewhere in that code area.

**Comment by NicolasToussaint** [comment]
> > But my second post is a scan of an original, unmodified git clone, and I have an exception pointing at the same place
> 
> Did you happen to pass a relative directory to ORT on the CLI in that case? I believe we could be missing to ensure using absolute paths somewhere in that code area.

No, actually I ran this one using Docker, only absolute paths.

**Comment by NicolasToussaint** [comment]
Got it ! It was a permission problem...

Maybe a more explicit error could help the next person falling in this trap :)

Many thanks @sschuberth for helping out

**Comment by sschuberth** [comment]
> Got it ! It was a permission problem...
> 
> Maybe a more explicit error could help the next person falling in this trap :)

Probably :grinning: Can you share a bit more details on what kind of permission problem this was? Or ideally contribute a patch that would show a more meaningful error message for your case?
