### ISSUE TITLE
Evaluator: Type inference List<LicenseSource> vs Set<LicenseSource>

### ISSUE THREAD

**Issue by VaeterchenFrost** [oss-review-toolkit/ort#2999]
After around https://github.com/oss-review-toolkit/ort/commit/1c0f9858e4fd13f3fbcc1386e920a8ce630df548 I get the error in the Evaluator : 
`Expected type mismatch: inferred type is List<LicenseSource> but Set<LicenseSource> was expected`
and the stacktrace

```
Exception in thread "main" javax.script.ScriptException: Type inference failed. Expected type mismatch: inferred type is List<LicenseSource> but Set<LicenseSource> was expected
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.asJsr223EvalResult(KotlinJsr223JvmScriptEngineBase.kt:104)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.compileAndEval(KotlinJsr223JvmScriptEngineBase.kt:63)
	at kotlin.script.experimental.jvmhost.jsr223.KotlinJsr223ScriptEngineImpl.compileAndEval(KotlinJsr223ScriptEngineImpl.kt:93)
	at org.jetbrains.kotlin.cli.common.repl.KotlinJsr223JvmScriptEngineBase.eval(KotlinJsr223JvmScriptEngineBase.kt:31)
	at java.scripting/javax.script.AbstractScriptEngine.eval(Unknown Source)
	at org.ossreviewtoolkit.utils.ScriptRunner.run(ScriptRunner.kt:68)
	at org.ossreviewtoolkit.evaluator.Evaluator.run(Evaluator.kt:67)
	at org.ossreviewtoolkit.commands.EvaluatorCommand$run$evaluatorRun$2.invoke(EvaluatorCommand.kt:193)
	at org.ossreviewtoolkit.commands.EvaluatorCommand$run$evaluatorRun$2.invoke(EvaluatorCommand.kt:59)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.commands.EvaluatorCommand.run(EvaluatorCommand.kt:196)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:170)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:179)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:258)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:255)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:273)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:298)
	at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:174)
```

The rules file is very similar to the current example - I could not find the error yet.

**Comment by VaeterchenFrost** [comment]
Rules file attached for reference
[zeiss-rules.zip](https://github.com/oss-review-toolkit/ort/files/5142202/zeiss-rules.zip)

**Comment by sschuberth** [comment]
In line 280 of your rules,

    LicenseView(listOf(LicenseSource.CONCLUDED, LicenseSource.DECLARED))

should be replaced with

    LicenseView(setOf(LicenseSource.CONCLUDED, LicenseSource.DECLARED))

now.

**Comment by VaeterchenFrost** [comment]
That was the change needed, thank you.
// Closed
