### ISSUE TITLE
ORT and Artifactory storage issue

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3137]
Hello
Recently I am facing an issue with storing ORT scan results file on artifactory file based storage
I use company's artifactory server with a read/deploy access (no delete) and during a second scan of the same project, pointing the same artifactory repository path, I obtain quite ofter a message 403 Forbidden.

Have you faced a similar issue?
What are the privileges I need to have on my account to operate on artifactory service as a file based storage ?
```
12:44:51.744 [ScanCode-1] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running '/usr/local/bin/scancode --version' in '/usr/local/bin'...
java.io.IOException: Could not store file at 'https://artifactory-iva.si.*************/artifactory/gen-virt-product-devops/ort/NPM/unknown/nodejs-test-01/0.0.1/scan-results.yml': 403 - Forbidden
	at org.ossreviewtoolkit.utils.storage.HttpFileStorage.write(HttpFileStorage.kt:103)
	at org.ossreviewtoolkit.scanner.storages.FileBasedStorage.addToStorage(FileBasedStorage.kt:126)
	at org.ossreviewtoolkit.scanner.ScanResultsStorage.add(ScanResultsStorage.kt:227)
	at org.ossreviewtoolkit.scanner.LocalScanner.scanPackage(LocalScanner.kt:355)
	at org.ossreviewtoolkit.scanner.LocalScanner.access$scanPackage(LocalScanner.kt:78)
	at org.ossreviewtoolkit.scanner.LocalScanner$scanPackage$4.invokeSuspend(LocalScanner.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
12:44:53.315 [ScanCode-1] WARN  org.ossreviewtoolkit.scanner.storages.FileBasedStorage - Could not store scan result for 'NPM::nodejs-test-01:0.0.1' at path 'NPM/unknown/nodejs-test-01/0.0.1/scan-results.yml': IOException: Could not store file at 'https://artifactory-iva.si.************/artifactory/gen-virt-product-devops/ort/NPM/unknown/nodejs-test-01/0.0.1/scan-results.yml': 403 - Forbidden
```
Thank you in advance for any help

**Comment by sschuberth** [comment]
I don't think this is a privileges issues, because if it was, I'd expect to see a message like "Could not store scan result for ...".

ORT uses regular HTTP PUT calls to store the files. However, we also need to be able to overwrite existing files. Maybe (some version of) Artifactory interprets overwriting files as create + delete? Then we'd also need delete privileges.

**Comment by woznik** [comment]
Yes, it seems to be the case. I need to operate on the artifactory with overwrite access.

**Comment by sschuberth** [comment]
So, good to close this issue?

**Comment by woznik** [comment]
yes, thank you

**Comment by sschuberth** [comment]
Then please just do that yourself 😉
