### ISSUE TITLE
[Observation] ClearlyDefinedStorage - Could not obtain ClearlyDefined coordinates

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3239]
Hello

I've noticed a stracktrace thrown on a console in a quite standard action
One artifact wasn't found in the CD repository and I obtained a following output:
```
15:34:44.026 [composite[readers:[FileBasedStorage with HttpFileStorage backend, ClearlyDefinedStorage], writers:[FileBasedStorage with HttpFileStorage backend]]-1] INFO  kotlinx.coroutines.CoroutineScope - Looking for stored scan results for Unmanaged::marmitmargot:ae64a281fdb9bbf6ae426010db71c1b7278ce1f8 and ScannerDetails(name=ScanCode, version=3.2.1-rc2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp) (1/1).
15:34:44.958 [composite[readers:[FileBasedStorage with HttpFileStorage backend, ClearlyDefinedStorage], writers:[FileBasedStorage with HttpFileStorage backend]]-1] INFO  org.ossreviewtoolkit.scanner.storages.FileBasedStorage - Could not read scan results for 'Unmanaged::marmitmargot:ae64a281fdb9bbf6ae426010db71c1b7278ce1f8' from path 'Unmanaged/unknown/marmitmargot/ae64a281fdb9bbf6ae426010db71c1b7278ce1f8/scan-results.yml': IOException: Could not read from 'https://***********************/artifactory/gen-depot-orange-project-ort//Unmanaged/unknown/marmitmargot/ae64a281fdb9bbf6ae426010db71c1b7278ce1f8/scan-results.yml': 404 - Not Found
15:34:44.968 [composite[readers:[FileBasedStorage with HttpFileStorage backend, ClearlyDefinedStorage], writers:[FileBasedStorage with HttpFileStorage backend]]-1] WARN  org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorage - Could not obtain ClearlyDefined coordinates for package 'Unmanaged::marmitmargot:ae64a281fdb9bbf6ae426010db71c1b7278ce1f8'.
java.lang.IllegalArgumentException: Unable to create ClearlyDefined coordinates for 'Unmanaged::marmitmargot:ae64a281fdb9bbf6ae426010db71c1b7278ce1f8'.
	at org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorageKt.packageCoordinates(ClearlyDefinedStorage.kt:77) ~[scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorageKt.access$packageCoordinates(ClearlyDefinedStorage.kt:1) ~[scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorage.readPackageFromClearlyDefined(ClearlyDefinedStorage.kt:128) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.ClearlyDefinedStorage.readFromStorage(ClearlyDefinedStorage.kt:112) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.ScanResultsStorage.read(ScanResultsStorage.kt:202) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.CompositeStorage$readFromStorage$2.invoke(CompositeStorage.kt:68) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.CompositeStorage$readFromStorage$2.invoke(CompositeStorage.kt:45) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.CompositeStorage.fetchReadResult(CompositeStorage.kt:97) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.storages.CompositeStorage.readFromStorage(CompositeStorage.kt:68) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.ScanResultsStorage.read(ScanResultsStorage.kt:202) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.LocalScanner.readFromStorage(LocalScanner.kt:286) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.LocalScanner.access$readFromStorage(LocalScanner.kt:78) [scanner-0.1.0-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.scanner.LocalScanner$scanPackage$storedResults$1.invokeSuspend(LocalScanner.kt:209) [scanner-0.1.0-SNAPSHOT.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-jvm-1.3.9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
15:34:44.991 [ScanCode-1] INFO  kotlinx.coroutines.CoroutineScope - No stored result found for Unmanaged::marmitmargot:ae64a281fdb9bbf6ae426010db71c1b7278ce1f8 and ScannerDetails(name=ScanCode, version=3.2.1-rc2, configuration=--copyright --license --ignore *.ort.yml --info --strip-root --timeout 300 --ignore HERE_NOTICE --ignore META-INF/DEPENDENCIES --json-pp), scanning package in thread 'ScanCode-1' (1/1).
```

as for the HttpFileStorage ORT displays a handled exception `404` of `INFO` type for `ClearlyDefined` it prints a full trace with a `WARN` type.

For the scan I have used a sample internal python project

**Comment by sschuberth** [comment]
That's actually expected, as ORT's unique "Unmanaged" type cannot be mapped to ClearlyDefined. It's only a warning after all, not an error. However, you probably shouldn't see that stacktrace. I'll address that.

**Comment by woznik** [comment]
Yes, I meant just the stacktracke. The overall behavior is OK.
Thank you Sebastien

**Comment by sschuberth** [comment]
I've improved the logging in https://github.com/oss-review-toolkit/ort/pull/3240 so it should be less confusing, so I'm closing this.
