### ISSUE TITLE
Is it possible or desirable to share the scanner download directory for caching?

### ISSUE THREAD

**Issue by intelfx** [oss-review-toolkit/ort#3241]
Trying to make `ort scan` runs faster (a cold run of `ort scan` on a Java project I'm working with takes 43 CPU-hours!), I attempted to investigate using a persistent directory to cache ORT's intermediate files. Something like this:
```
docker run
        --rm
        -v ./path/to/code:/code
        -v ./gradle-user-home:/gradle-user-home
        -v ./ort-data-dir:/ort-data-dir
        -v ./ort-download-dir:/ort-download-dir
        -e GRADLE_USER_HOME=/gradle-user-home
        -e ORT_DATA_DIR=/ort-data-dir
        -w /code
        localhost/ort
        --info scan -f json -i ort/analyzer-result.json -o ort --download-dir /ort-download-dir
```

However, trying to use a persistent download directory produces an error:
```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 0.1.0-SNAPSHOT.
 /   |   \|       _/ |    |    Running 'scan' under Java 11.0.8 on Linux with
/    |    \    |   \ |    |    ORT_CONFIG_DIR = /ort-data-dir/config
\_______  /____|_  / |____|    ORT_DATA_DIR = /ort-data-dir
        \/       \/
More environment variables:
TERM = xterm
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /go

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.IllegalArgumentException: The download directory '/ort-download-dir' must not exist yet.
        at org.ossreviewtoolkit.commands.ScannerCommand.run(ScannerCommand.kt:160)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:171)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:180)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:16)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:194)
```

Caching downloads in a persistent directory seems like a logical thing to do, but it appears that ORT expressly disallows that. Maybe I don't understand how ORT works and it makes no sense to cache downloads?

**Comment by sschuberth** [comment]
Indeed caching downloads only makes limited sense in the current architecture. What we do instead is to cache the scan results, because if you do that, even the download can be skipped. By default a file-based scan storage in the ORT data directory is used. So if you want to benefit from that between Docker runs, you need to persist the ORT data directory basically like you do, but not the download directory.

**Comment by sschuberth** [comment]
Feel free to reopen if you still have questions.
