### ISSUE TITLE
Out of memory even with 8Gb heap

### ISSUE THREAD

**Issue by jagusztinl** [oss-review-toolkit/ort#3438]
We are scanning an android applicaton. The scan runs for 6 hours then we got always out of memory. Debug log (attached also)

[2020-12-09T15:47:15.744Z] 16:47:15.396 [Analyzer-1] DEBUG org.apache.http.headers - >> Accept-Encoding: gzip,deflate
[2020-12-09T15:47:15.744Z] 16:47:15.396 [Analyzer-1] DEBUG org.apache.http.headers - >> Host: nexus.hu
[2020-12-09T15:47:15.744Z] 16:47:15.396 [Analyzer-1] DEBUG org.apache.http.headers - >> Connection: Keep-Alive
[2020-12-09T15:47:15.744Z] 16:47:15.396 [Analyzer-1] DEBUG org.apache.http.headers - >> User-Agent: Apache-Maven/3.6.3 (Java 11.0.9; Mac OS X 10.15.6)
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "HTTP/1.1 200 OK[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Date: Wed, 09 Dec 2020 15:47:15 GMT[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Server: Nexus/3.24.0-02 (OSS)[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "X-Content-Type-Options: nosniff[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "X-XSS-Protection: 1; mode=block[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Last-Modified: Tue, 11 Dec 2018 01:45:34 GMT[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "ETag: "ecdc8e22fb7e69089044acbeda8ebf4b"[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Content-Type: text/plain; charset=UTF-8[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Content-Length: 40[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Keep-Alive: timeout=5, max=89[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "Connection: Keep-Alive[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "[\r][\n]"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.impl.conn.DefaultClientConnection - Receiving response: HTTP/1.1 200 OK
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << HTTP/1.1 200 OK
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Date: Wed, 09 Dec 2020 15:47:15 GMT
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Server: Nexus/3.24.0-02 (OSS)
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << X-Content-Type-Options: nosniff
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << X-XSS-Protection: 1; mode=block
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Last-Modified: Tue, 11 Dec 2018 01:45:34 GMT
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << ETag: "ecdc8e22fb7e69089044acbeda8ebf4b"
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Content-Type: text/plain; charset=UTF-8
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Content-Length: 40
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Keep-Alive: timeout=5, max=89
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.headers - << Connection: Keep-Alive
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.impl.client.DefaultHttpClient - Connection can be kept alive for 5000 MILLISECONDS
[2020-12-09T15:47:16.012Z] 16:47:15.407 [Analyzer-1] DEBUG org.apache.http.wire -  << "11c277d47d012b2830b37f3750ff040c1f38883e"
[2020-12-09T15:47:16.013Z] 16:47:15.408 [Analyzer-1] DEBUG org.apache.http.impl.conn.PoolingClientConnectionManager - Connection [id: 730][route: {s}->https://nexus.hu:443] can be kept alive for 5000 MILLISECONDS
[2020-12-09T15:47:16.013Z] 16:47:15.408 [Analyzer-1] DEBUG org.apache.http.impl.conn.PoolingClientConnectionManager - Connection released: [id: 730][route: {s}->https://nexus.hu:443][total kept alive: 5; route allocated: 1 of 50; total allocated: 5 of 100]
[2020-12-09T15:47:16.013Z] 16:47:15.408 [Analyzer-1] DEBUG org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport - Writing remote artifact for 'com.google.auto.value:auto-value-annotations:jar:sources:1.6.3' to disk cache.
[2020-12-09T16:53:50.809Z] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
[2020-12-09T16:53:50.809Z] 	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
[2020-12-09T16:53:50.809Z] 	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:448)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.Identifier$toCoordinates$1.invoke(Identifier.kt:193)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.Identifier$toCoordinates$1.invoke(Identifier.kt:31)
[2020-12-09T16:53:50.809Z] 	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
[2020-12-09T16:53:50.809Z] 	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3304)
[2020-12-09T16:53:50.809Z] 	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3321)
[2020-12-09T16:53:50.809Z] 	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3320)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.Identifier.toCoordinates(Identifier.kt:113)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.Identifier.compareTo(Identifier.kt:90)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.PackageReference.compareTo(PackageReference.kt:103)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.model.PackageReference.compareTo(PackageReference.kt:42)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.TreeMap.compare(TreeMap.java:1291)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.TreeMap.put(TreeMap.java:536)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.TreeSet.add(TreeSet.java:255)
[2020-12-09T16:53:50.809Z] 	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1244)
[2020-12-09T16:53:50.809Z] 	at kotlin.collections.CollectionsKt___CollectionsJvmKt.toSortedSet(_CollectionsJvm.kt:50)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:334)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.parseDependency(Gradle.kt:326)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.access$parseDependency(Gradle.kt:68)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:235)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:68)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.utils.UtilsKt.temporaryProperties(Utils.kt:283)
[2020-12-09T16:53:50.809Z] 	at org.ossreviewtoolkit.analyzer.managers.Gradle.resolveDependencies(Gradle.kt:188)
[2020-12-09T16:53:50.809Z] Dec 09, 2020 5:53:44 PM org.tmatesoft.svn.core.internal.util.DefaultSVNDebugLogger log
[2020-12-09T16:53:50.809Z] SEVERE: WC: Java heap space
[2020-12-09T16:53:50.809Z] java.lang.OutOfMemoryError: Java heap space
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.HashMap$KeySet.iterator(HashMap.java:912)
[2020-12-09T16:53:50.809Z] 	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool.shutdownInactiveRepositories(DefaultSVNRepositoryPool.java:518)
[2020-12-09T16:53:50.809Z] 	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool.access$200(DefaultSVNRepositoryPool.java:69)
[2020-12-09T16:53:50.809Z] 	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool$TimeoutTask.run(DefaultSVNRepositoryPool.java:532)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[2020-12-09T16:53:50.809Z] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[2020-12-09T16:53:50.809Z] 	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jagusztinl** [comment]
[
[Android-ort-debug.zip](https://github.com/oss-review-toolkit/ort/files/5671516/Android-ort-debug.zip)


](url)

**Comment by jagusztinl** [comment]
[gradle.zip](https://github.com/oss-review-toolkit/ort/files/5671520/gradle.zip)

**Comment by ZsanettMagyar** [comment]
Additional informations:
- the Android build server is a MacMini
- gradle.properties jvmargs values: 
org.gradle.jvmargs=-Xms512M -Xmx8g -XX:MaxPermSize=1024m -XX:MaxMetaspaceSize=1g -Dkotlin.daemon.jvm.options="-Xmx1g"
(https://github.com/oss-review-toolkit/ort/issues/2272#issuecomment-591321243)
- we use Jenkins pipeline, the error is during the analyze step:

```
stage('Dependency Track') {
  when {
      expression { params.DependencyTrack }
  }
  environment {
      JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.9.jdk/Contents/Home"
      JAVA_OPTS="-Xmx8g"
      OSS_REVIEW_TOOLKIT = "/Users/Shared/Jenkins/jenkins_home/oss-review-toolkit"
  }
  steps {
    echo '========= OSS review toolkit BOM generation =========='
    sh "rm -rf _no_android_project"
    sh "sh $OSS_REVIEW_TOOLKIT/bin/ort --debug --stacktrace analyze -i . -o ./ort/analyzer -m gradle"
    sh "sh $OSS_REVIEW_TOOLKIT/bin/ort --debug --stacktrace report --ort-file ./ort/analyzer/analyzer-result.yml -o ./ort/reporter -f CycloneDx -O CycloneDx=single.bom=true"
  }
}
```

**Comment by sschuberth** [comment]
Thanks for the report. Esp. for the Android case, we're tracking the issue already as https://github.com/oss-review-toolkit/ort/issues/3321. Would you be fine with closing this issue in favor of the linked one?

**Comment by jagusztinl** [comment]
> Thanks for the report. Esp. for the Android case, we're tracking the issue already as #3321. Would you be fine with closing this issue in favor of the linked one?

Yes, you can close this, thx
