### ISSUE TITLE
Failure case: Analyzer output causes failure in Downloader

### ISSUE THREAD

**Issue by unique-identifier** [oss-review-toolkit/ort#3563]
Generating an Analyzer results file for the Ant Design (https://github.com/ant-design/ant-design.git) project and running a scan on it causes the following exception: 

`Exception in thread "main" java.lang.IllegalArgumentException: The output directory '/home/someuser/output/downloads/NPM/unknown/antd/4.10.2' must not contain any files yet. 
at org.ossreviewtoolkit.downloader.Downloader.verifyOutputDirectory(Downloader.kt:99) 
at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:112) 
at org.ossreviewtoolkit.downloader.Downloader.download$default(Downloader.kt:111) 
at org.ossreviewtoolkit.scanner.LocalScanner.scanPackage(LocalScanner.kt:358) 
at org.ossreviewtoolkit.scanner.LocalScanner$scanPackage$5.invokeSuspend(LocalScanner.kt:285) 
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) 
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) 
at java.base/java.lang.Thread.run(Thread.java:834) `

We tested this using several versions of ORT, including the latest code, with the same result. Each time, our PostgreSQL-based cache is cleared before we start the scan. It appears that several minutes into the scan, Downloader successfully downloads package 'NPM::antd:4.10.2', processes it successfully, and moves onto other packages. Roughly 40 minutes to an hour later, we get the above exception. NPM::antd:4.10.2 is found in analyzer->result->projects[0] and analyzer->result->packages[n]. It is fatally exiting because the directory for antd 4.10.2 already exists. I have confirmed during trials that the directory exists several minutes into the scan.

**Comment by unique-identifier** [comment]
Also, this behavior occurs whether we specify ScanCode or a different third-party scanner.

**Comment by mnonnenmacher** [comment]
I could reproduce the issue. It looks like a bug in the NPM implementation which should not add antd to the package list, especially because it does never appear as a dependency of any project.

**Comment by mnonnenmacher** [comment]
@unique-identifier I would expect that #3811 also fixes this issue, could you verify that?

**Comment by mnonnenmacher** [comment]
@unique-identifier Please reopen this issue if you can still reproduce this error.
