### ISSUE TITLE
SEVERE: Error executing FreeMarker template

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#3681]
Hello
I have discovered an error while generating a NOTICE TEMPLATE report from scan-results file. I have used the ORT from a commit `a29c8c7237032c7e79daea2f763c508b58356c18`

```
18:31:16.925 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor - Generating output file '/builds/sqsc/gopro/ort/reporter/NOTICE_default' using template id 'default'.
Feb 24, 2021 6:31:17 PM freemarker.log._JULLoggerFactory$JULLogger error
SEVERE: Error executing FreeMarker template
FreeMarker template error:
An error has occurred when reading existing sub-variable "licenseFiles"; see cause exception! The type of the containing value was: extended_hash+string (org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor$PackageModel wrapped into f.e.b.StringModel)
----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list package.licenseFiles.files as l...  [in template "default.ftl" at line 78, column 1]
----
Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:185)
	at freemarker.core.Dot._eval(Dot.java:43)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:376)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:321)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:644)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:334)
	at freemarker.core.Environment.visit(Environment.java:340)
	at freemarker.core.Environment.process(Environment.java:313)
	at freemarker.template.Template.process(Template.java:383)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor.processTemplatesInternal(FreemarkerTemplateProcessor.kt:149)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor.processTemplates(FreemarkerTemplateProcessor.kt:83)
	at org.ossreviewtoolkit.reporter.reporters.NoticeTemplateReporter.generateReport(NoticeTemplateReporter.kt:66)
	at org.ossreviewtoolkit.commands.ReporterCommand$run$$inlined$measureTimedValue$lambda$1$1.invokeSuspend(ReporterCommand.kt:266)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
	... 28 more
Caused by: java.lang.NullPointerException
	at org.ossreviewtoolkit.model.utils.FileArchiverKt.hash(FileArchiver.kt:152)
	at org.ossreviewtoolkit.model.utils.FileArchiverKt.getArchivePath(FileArchiver.kt:142)
	at org.ossreviewtoolkit.model.utils.FileArchiverKt.access$getArchivePath(FileArchiver.kt:1)
	at org.ossreviewtoolkit.model.utils.FileArchiver.unarchive(FileArchiver.kt:114)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.createLicenseFileInfo(LicenseInfoResolver.kt:210)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLicenseFiles(LicenseInfoResolver.kt:64)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor$PackageModel$licenseFiles$2.invoke(FreemarkerTemplateProcessor.kt:194)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor$PackageModel$licenseFiles$2.invoke(FreemarkerTemplateProcessor.kt:174)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor$PackageModel.getLicenseFiles(FreemarkerTemplateProcessor.kt)
	... 35 more
18:31:19.647 [main] ERROR org.ossreviewtoolkit.commands.ReporterCommand - Could not create 'NoticeTemplate' report in 0.207224318s: _TemplateModelException: An error has occurred when reading existing sub-variable "licenseFiles"; see cause exception! The type of the containing value was: extended_hash+string (org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor$PackageModel wrapped into f.e.b.StringModel)
----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list package.licenseFiles.files as l...  [in template "default.ftl" at line 78, column 1]
----
Caused by: InvocationTargetException: null
Caused by: NullPointerException: null
```

**Comment by sschuberth** [comment]
@fviernau, looks like this was introduced by

https://github.com/oss-review-toolkit/ort/pull/3660/files#diff-daad7748865c8dbc47c630e91abca16b47e7c02a6d977d6f3c4e5e34c707a87dR152

Any idea why it seems both `vcsInfo` and `sourceArtifact` are `null` in a `Provenance`?

**Comment by sschuberth** [comment]
@woznik can you give https://github.com/oss-review-toolkit/ort/pull/3682 a try?

**Comment by woznik** [comment]
Hi
I am not able to build a docker image due to permission issues:

```
#15 316.1 > Task :cli:classes
#15 316.1 > Task :cli:inspectClassesForKotlinIC
#15 316.3 > Task :cli:jar
#15 316.4 > Task :helper-cli:startScripts
#15 330.6 
#15 330.6 > Task :reporter-web-app:yarnInstall
#15 330.6 [4/4] Building fresh packages...
#15 330.8 error /usr/local/src/ort/reporter-web-app/node_modules/core-js-pure: Command failed.
#15 330.8 Exit code: 126
#15 330.8 Command: node -e "try{require('./postinstall')}catch(e){}"
#15 330.8 Arguments: 
#15 330.8 Directory: /usr/local/src/ort/reporter-web-app/node_modules/core-js-pure
#15 330.8 Output:
#15 330.8 /bin/sh: node: Permission denied
#15 330.8 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#15 347.6 
#15 347.6 > Task :reporter-web-app:yarnInstall FAILED
#15 347.7 
#15 347.7 FAILURE: Build failed with an exception.
#15 347.7 
#15 347.7 * What went wrong:
#15 347.7 Execution failed for task ':reporter-web-app:yarnInstall'.
#15 347.7 > Process 'command '/root/.gradle/nodejs/node-v12.16.1-linux-x64/bin/node'' finished with non-zero exit value 126
#15 347.7 
#15 347.7 * Try:
#15 347.7 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#15 347.7 
#15 347.7 * Exception is:
#15 347.7 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':reporter-web-app:yarnInstall'.
#15 347.7 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$3(ExecuteActionsTaskExecuter.java:186)
#15 347.7 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:268)
```

**Comment by sschuberth** [comment]
> error /usr/local/src/ort/reporter-web-app/node_modules/core-js-pure: Command failed.

No idea what's causing this. Multiple Docker builds worked fine since the merge on our side.

**Comment by woznik** [comment]
The error must have come from my gitlab runner. Now the image is build. Testing new image on the same project...

**Comment by woznik** [comment]
Hello again
I report no issue at the moment

```
Successfully created the 'NoticeTemplate' report at [/builds/sqsc/gopro/ort/reporter/NOTICE_default] in 0.41677391s.
Successfully created the 'Excel' report at [/builds/sqsc/gopro/ort/reporter/scan-report.xlsx] in 2.788442216s.
Successfully created the 'WebApp' report at [/builds/sqsc/gopro/ort/reporter/scan-report-web-app.html] in 1.108324198s.
Created 3 of 3 report(s) in 2.818156217s.
```

We can close that one. Thank you very much

**Comment by sschuberth** [comment]
> We can close that one.

It was already closed 😉 

> Thank you very much

You're welcome!
