### ISSUE TITLE
ORT should ignore empty .ort.yml files

### ISSUE THREAD

**Issue by sschuberth** [oss-review-toolkit/ort#3861]
Currently, ORT chokes on empty `.ort.yml` files:

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 3, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4688)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4586)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3433)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyze(Analyzer.kt:170)
	at org.ossreviewtoolkit.commands.AnalyzerCommand.run(AnalyzerCommand.kt:166)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:180)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at org.ossreviewtoolkit.OrtMainKt.main(OrtMain.kt:217)
```

We should simply ignore empty files instead of failing. but still fail on files with real syntax errors.

**Comment by sschuberth** [comment]
Alse see https://github.com/fasterxml/jackson-databind/issues/1406#issuecomment-252676674.
