### ISSUE TITLE
GoMod: Expected exactly one unique package without version but got .

### ISSUE THREAD

**Issue by grollinger** [oss-review-toolkit/ort#4139]
I'm trying to analyze a project which includes a Go module.

When running the analyzer, it outputs the following `ERROR`:

`Expected exactly one unique package without version but got .`

Which seems to indicate that the check in [this line](https://github.com/oss-review-toolkit/ort/blob/bd2494938a82843932738780ce27707900976334/analyzer/src/main/kotlin/managers/GoMod.kt#L101) failed.

<details>
  <summary>(partial) stacktrace</summary>

```
07:57:48 07:57:48.475 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'go mod vendor -v' in '/workspace/project/project'...
07:57:48 java.lang.IllegalArgumentException: Expected exactly one unique package without version but got .
07:57:48 	at org.ossreviewtoolkit.analyzer.managers.GoMod.resolveDependencies(GoMod.kt:101)
07:57:48 	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:237)
07:57:48 	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:122)
07:57:48 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07:57:48 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07:57:48 07:57:48.623 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator is already installed.
07:57:48 07:57:48.624 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
07:57:49 07:57:48.859 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for 'project/go.mod' failed with: IllegalArgumentException: Expected exactly one unique package without version but got .
```
</details>

The reason seems to be that we filter out the root package of the project [a few lines before](https://github.com/oss-review-toolkit/ort/blob/bd2494938a82843932738780ce27707900976334/analyzer/src/main/kotlin/managers/GoMod.kt#L97) because the `go mod why` output contains the following:
```
# myproject.com/project
(main module does not need package myproject.com/project)
```
<details>
  <summary>Full `go mod why` output</summary>

 ```console
> go mod why myproject.com/project github.com/fsnotify/fsnotify github.com/go-playground/validator/v10 github.com/go-test/deep github.com/google/uuid github.com/sirupsen/logrus github.com/stretchr/testify github.com/davecgh/go-spew github.com/pmezard/go-difflib github.com/stretchr/testify golang.org/x/sys golang.org/x/sys github.com/davecgh/go-spew github.com/stretchr/objx gopkg.in/yaml.v2 gopkg.in/check.v1 github.com/go-playground/assert/v2 github.com/go-playground/locales github.com/go-playground/universal-translator github.com/leodido/go-urn golang.org/x/crypto golang.org/x/net golang.org/x/sys golang.org/x/crypto golang.org/x/text golang.org/x/sys golang.org/x/text golang.org/x/tools
# myproject.com/project
(main module does not need package myproject.com/project)

# github.com/fsnotify/fsnotify
myproject.com/project/internal/config
github.com/fsnotify/fsnotify

# github.com/go-playground/validator/v10
myproject.com/project/internal/config
github.com/go-playground/validator/v10

# github.com/go-test/deep
myproject.com/project/internal/config
github.com/go-test/deep

# github.com/google/uuid
myproject.com/project/internal/project
myproject.com/project/internal/project.test
github.com/google/uuid

# github.com/sirupsen/logrus
myproject.com/project/cmd/cli
github.com/sirupsen/logrus

# github.com/stretchr/testify
(main module does not need package github.com/stretchr/testify)

# github.com/davecgh/go-spew
(main module does not need package github.com/davecgh/go-spew)

# github.com/pmezard/go-difflib
(main module does not need package github.com/pmezard/go-difflib)

# github.com/stretchr/testify
(main module does not need package github.com/stretchr/testify)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# github.com/davecgh/go-spew
(main module does not need package github.com/davecgh/go-spew)

# github.com/stretchr/objx
(main module does not need package github.com/stretchr/objx)

# gopkg.in/yaml.v2
myproject.com/project/internal/config
myproject.com/project/internal/config.test
github.com/stretchr/testify/assert
gopkg.in/yaml.v2

# gopkg.in/check.v1
myproject.com/project/internal/config
myproject.com/project/internal/config.test
github.com/stretchr/testify/assert
gopkg.in/yaml.v2
gopkg.in/yaml.v2.test
gopkg.in/check.v1

# github.com/go-playground/assert/v2
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/validator/v10.test
github.com/go-playground/assert/v2

# github.com/go-playground/locales
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/universal-translator
github.com/go-playground/locales

# github.com/go-playground/universal-translator
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/universal-translator

# github.com/leodido/go-urn
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/leodido/go-urn

# golang.org/x/crypto
(main module does not need package golang.org/x/crypto)

# golang.org/x/net
(main module does not need package golang.org/x/net)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/crypto
(main module does not need package golang.org/x/crypto)

# golang.org/x/text
(main module does not need package golang.org/x/text)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/text
(main module does not need package golang.org/x/text)

# golang.org/x/tools
(main module does not need package golang.org/x/tools)
```
</details>

That's because the root package doesn't contain any code by itself.
The code is split into sub-packages in  `cmd`, `internal` and `pkg` as demonstrated by https://github.com/golang-standards/project-layout

**Comment by sschuberth** [comment]
@oheger-bosch could you have a look at this as part of your current work?

**Comment by oheger-bosch** [comment]
Thank you very much for this detailed report. I have created #4151, which should hopefully fix this problem.
