### ISSUE TITLE
jruby crashes analyzer requirement version check

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#4177]
If ORT is used with jruby enabled with rvm, the requirement version check panics even if ignoreToolVersions is set to true as the version "jruby 9.1.17.0 (2.3.3)" can not be parsed as major version.

```
Exception in thread "main" com.vdurmont.semver4j.SemverException: Invalid version (no major version): jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 O
	at com.vdurmont.semver4j.Semver.<init>(Semver.java:61)
	at com.vdurmont.semver4j.Requirement.isSatisfiedBy(Requirement.java:547)
	at org.ossreviewtoolkit.utils.CommandLineTool$DefaultImpls.checkVersion(CommandLineTool.kt:100)
	at org.ossreviewtoolkit.analyzer.managers.Bundler.checkVersion(Bundler.kt:65)
	at org.ossreviewtoolkit.utils.CommandLineTool$DefaultImpls.checkVersion$default(CommandLineTool.kt:96)
	at org.ossreviewtoolkit.analyzer.managers.Bundler.beforeResolution(Bundler.kt:89)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:229)
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by sschuberth** [comment]
That's funny because we're actually not checking the version of Ruby, but the version of Bundler. Does `bundler --version` on the command line indeed return `jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 O` on your machine?

**Comment by mmurto** [comment]
> That's funny because we're actually not checking the version of Ruby, but the version of Bundler. Does `bundler --version` on the command line indeed return `jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 O` on your machine?

Getting mixed with my ORT versions here, sorry for confusion. This was using https://github.com/oss-review-toolkit/ort/pull/3514, which checks for Ruby's version instead of bundler. I'll close the issue and continue in the PR.
