### ISSUE TITLE
Missing package for npm ERR! Failed at the openzwave-shared@1.6.1 install script.

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#4193]
Hello
Context: Analysis using ORT docker container
Source code: Nodejs
During I encoutered an error `npm ERR! Failed at the openzwave-shared@1.6.1 install script.`

```
17:26:12.274 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.managers.Npm - Resolving NPM dependencies for 'homein/iotcontroller/homein-iot-manager/oim-delivery/oim-api-soft/package.json' failed with: IOException: Running 'npm ci' in '/builds/sqsc/home-in/homein/iotcontroller/homein-iot-manager/oim-delivery/oim-api-soft' failed with exit code 1:
grep: /usr/*/include/value_classes: No such file or directory
gyp: Call to 'grep -r GetTypeNameFromEnum /usr/*/include/value_classes | wc -l' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.10.38-flatcar
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /builds/sqsc/home-in/homein/iotcontroller/homein-iot-manager/oim-delivery/oim-api-soft/node_modules/openzwave-shared
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-17T17_26_11_741Z-debug.log
```

After the investigation I discovered that ORT bionic image requires additional packages
When I applied `apt install libopenzwave1.5-dev libopenzwave1.5 build-essential`
The ORT Analyser issue was resolved.
Should it be a part of the image or is it a custom case?

**Comment by sschuberth** [comment]
> Should it be a part of the image or is it a custom case?

It's indeed a custom case, IMO.

**Comment by woznik** [comment]
OK, thank you
closing
