### ISSUE TITLE
analyzer: Exits with NPE when analyzing certain SBT projects

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#4543]
The project is internal an cannot be shared.
It's been using scala version 2.10.7 and sbt version 0.13.17.
```
Exception in thread "main" java.io.IOException: Running 'sbt -batch -Dsbt.ci=true -Dsbt.color=false -Djline.terminal=none projects' in '/workspace/project' failed with exit code 1:
java.lang.NullPointerException
	at scala.reflect.io.JavaToolsPlatformArchive.iterator(ZipArchive.scala:242)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.reflect.io.AbstractFile.foreach(AbstractFile.scala:92)
	at scala.tools.nsc.util.DirectoryClassPath.traverse(ClassPath.scala:308)
	at scala.tools.nsc.util.DirectoryClassPath.x$16$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.x$16(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages$lzycompute(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:317)
	at scala.tools.nsc.util.DirectoryClassPath.packages(ClassPath.scala:297)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath$$anonfun$packages$1.apply(ClassPath.scala:375)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.tools.nsc.util.MergedClassPath.packages$lzycompute(ClassPath.scala:375)
	at scala.tools.nsc.util.MergedClassPath.packages(ClassPath.scala:370)
	at scala.tools.nsc.symtab.SymbolLoaders$PackageLoader.doComplete(SymbolLoaders.scala:243)
	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:194)
[...skipping 107 lines...]
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:61)
	at sbt.xMain.run(Main.scala:35)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
	at xsbt.boot.Launch$.run(Launch.scala:111)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
	at xsbt.boot.Launch$.launch(Launch.scala:119)
	at xsbt.boot.Launch$.apply(Launch.scala:20)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NullPointerException
[error] Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
(Above output is limited to each 20 heading and tailing lines.)
	at org.ossreviewtoolkit.utils.ProcessCapture.requireSuccess(ProcessCapture.kt:147)
	at org.ossreviewtoolkit.utils.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:75)
	at org.ossreviewtoolkit.analyzer.managers.Sbt.run(Sbt.kt:47)
	at org.ossreviewtoolkit.analyzer.managers.Sbt$mapDefinitionFiles$runSbt$1.invoke(Sbt.kt:145)
	at org.ossreviewtoolkit.analyzer.managers.Sbt$mapDefinitionFiles$runSbt$1.invoke(Sbt.kt:144)
	at org.ossreviewtoolkit.utils.RedirectionKt.suppressInput(Redirection.kt:62)
	at org.ossreviewtoolkit.analyzer.managers.Sbt.mapDefinitionFiles$runSbt(Sbt.kt:144)
	at org.ossreviewtoolkit.analyzer.managers.Sbt.mapDefinitionFiles(Sbt.kt:149)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyze(Analyzer.kt:71)
	at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:189)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:108)
```

**Comment by fviernau** [comment]
Ticket is missing information making it impossible to work on it.
