### ISSUE TITLE
Advisor OssIndexService MissingFieldException Field 'description' is missing

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#4557]
Hello
I encoutered an error trying to start the advisor with OssIndex as the agent.
In the `README` file it is mentioned that no additional configuration is required but maybe I should add somewhere the configuration of that agent. I tried that on ORT Docker Image build from the sources with commit: `9bdca87488e5ad2c44dcab7c36573e0ded1db0eb`, dated on `2021-09-30`

```
.
.
The following advisors are activated:
        OssIndex
13:32:23.417 [main] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator was successfully installed.
13:32:23.441 [main] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector was successfully installed.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/opt/ort/lib/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'description' is required for type with serial name 'org.ossreviewtoolkit.clients.ossindex.OssIndexService.ComponentReport', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at org.ossreviewtoolkit.clients.ossindex.OssIndexService$ComponentReport.<init>(OssIndexService.kt:91)
        at org.ossreviewtoolkit.clients.ossindex.OssIndexService$ComponentReport$$serializer.deserialize(OssIndexService.kt:91)
        at org.ossreviewtoolkit.clients.ossindex.OssIndexService$ComponentReport$$serializer.deserialize(OssIndexService.kt:91)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
        at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:30)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

Thanks in advance for your help

**Comment by sschuberth** [comment]
Thanks for reporting @woznik. This should be fixed with https://github.com/oss-review-toolkit/ort/pull/4558.
