### ISSUE TITLE
Excluded path crash when using SPDX package scan

### ISSUE THREAD

**Issue by tardyp** [oss-review-toolkit/ort#4563]
Following up #4505, we find following crash
```
22:45:16.488 [main] PERFORMANCE org.ossreviewtoolkit.model.OrtResult - Computing excluded projects...
Exception in thread "main" java.lang.IllegalArgumentException: The VcsInfo(type=Git, url=https://github.com/tardyp/proj1.git, revision=main, path=) of project 'SpdxDocumentFile::proj1:main' cannot be found in Repository(vcs=VcsInfo(type=, url=, revision=, path=), vcsProcessed=VcsInfo(type=, url=, revision=, path=), nestedRepositories={}, config=RepositoryConfiguration(excludes=Excludes(paths=[], scopes=[]), resolutions=Resolutions(issues=[], ruleViolations=[], vulnerabilities=[]), curations=Curations(packages=[], licenseFindings=[]), packageConfigurations=[], licenseChoices=LicenseChoices(repositoryLicenseChoices=[], packageLicenseChoices=[]))).
	at org.ossreviewtoolkit.model.OrtResult.getFilePathRelativeToAnalyzerRoot(OrtResult.kt:279)
	at org.ossreviewtoolkit.model.OrtResult.getDefinitionFilePathRelativeToAnalyzerRoot(OrtResult.kt:265)
	at org.ossreviewtoolkit.model.config.Excludes.findPathExcludes(Excludes.kt:52)
	at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:116)
	at org.ossreviewtoolkit.model.OrtResult$projects$2.invoke(OrtResult.kt:109)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.model.OrtResult.getProjects(OrtResult.kt:109)
	at org.ossreviewtoolkit.model.OrtResult.getProject(OrtResult.kt:355)
	at org.ossreviewtoolkit.scanner.ScannerKt.scanOrtResult(Scanner.kt:142)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:233)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:184)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:204)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:213)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:17)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:396)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:411)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:436)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:108)
```

@sschuberth says it is a bit tricky so I file a separate issue for it.

**Comment by sschuberth** [comment]
> Another usecase with SPDX is to have our suppliers deliver us spdxlite swbom, and use ORT's reporter, advisor and evaluator features based on that info to manage our compliance and vulnerability assesment needs.

That relates a bit to https://github.com/oss-review-toolkit/ort/issues/3797, though I still believe the concrete implementation suggested there is not the right way to go. Instead of making each ORT tool (evaluator, advisor) accept SPDX input, we should let the analyzer transform SPDX input to ORT own result format. Then we could implicitly use all of ORT's tool with SPDX input.

**Comment by tardyp** [comment]
I just verified that the crash is not happening anymore. 
one step more forward... Thanks!

**Comment by sschuberth** [comment]
Actually, it's a step forwards and backward again, as in exchange you'll probably run into you [original issue](https://github.com/oss-review-toolkit/ort/issues/4505#issuecomment-931597494) again as my fix in https://github.com/oss-review-toolkit/ort/pull/4547 was partly reverted.
