### ISSUE TITLE
Advisor OssIndexService MissingFieldException Field 'cvssVector' is missing

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#4607]
Hello
I encoutered a similar error as #4557 executing Advisor with OssIndex as the agent. I tried that on ORT Docker Image build from the sources with commit: https://github.com/oss-review-toolkit/ort/commit/35d8b2460c7cb70743a7284af0711bf42a303349 , dated on 2021-10-07

```
Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'cvssVector' is required for type with serial name 'org.ossreviewtoolkit.clients.ossindex.OssIndexService.Vulnerability', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at org.ossreviewtoolkit.clients.ossindex.OssIndexService$Vulnerability.<init>(OssIndexService.kt:107)
	at org.ossreviewtoolkit.clients.ossindex.OssIndexService$Vulnerability$$serializer.deserialize(OssIndexService.kt:107)
	at org.ossreviewtoolkit.clients.ossindex.OssIndexService$Vulnerability$$serializer.deserialize(OssIndexService.kt:107)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:35)
..
.
```

On the OssIndexService sometimes there are raised vulnerabilities but no vector is calculated yet. Maybe that field also should be optional. Thanks for your help

**Comment by sschuberth** [comment]
Closing as a duplicate of https://github.com/oss-review-toolkit/ort/issues/4601 (which has already been fixed).
