### ISSUE TITLE
NPE in default.ftl

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#4659]
Hello, I would like to configurate a customized NOTICE file derived from default.ftl

At first I just wanted to run the script with `-O NoticeTemplate=template.path=/pxs-project/ort/customized_license_report.ftl,/pxs-project/ort/customized_license_text_summary.ftl`

For `customized_license_report.ftl` I just took the code from [default.ftl](https://github.com/oss-review-toolkit/ort/blob/master/reporter/src/main/resources/templates/notice/default.ftl) but I got a NPE for `LicenseView` in line 101

`The following has evaluated to null or missing:
==> LicenseView  [in template "customized_license_report.ftl"`

`[#assign licensesFilteredBySource = LicenseView.CONCLUDED_OR_DECLARED_AND_DETECTED.filter(package.license.licenses)]`

Do you have an idea what I could have done wrong?

Thank you for your help.

Java stack trace (for programmers):
----
`freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
	at freemarker.core.UnexpectedTypeException.newDescriptionBuilder(UnexpectedTypeException.java:85)
	at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:48)
	at freemarker.core.NonHashException.<init>(NonHashException.java:49)
	at freemarker.core.Dot._eval(Dot.java:48)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.MethodCall._eval(MethodCall.java:55)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Assignment.accept(Assignment.java:134)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor.processTemplatesInternal(FreemarkerTemplateProcessor.kt:166)
	at org.ossreviewtoolkit.reporter.utils.FreemarkerTemplateProcessor.processTemplates(FreemarkerTemplateProcessor.kt:86)
	at org.ossreviewtoolkit.reporter.reporters.NoticeTemplateReporter.generateReport(NoticeTemplateReporter.kt:66)
	at org.ossreviewtoolkit.commands.ReporterCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReporterCommand.kt:266)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**Comment by schvvarzekatze** [comment]
These are my configuration files: ![configurationFiles](https://user-images.githubusercontent.com/93649020/140063832-c668df2b-19f7-4801-af53-a4855f321e6a.png)

**Comment by schvvarzekatze** [comment]
I just try to update the docker image as it is from March 2021. Perhaps this explains the script failure?

**Comment by sschuberth** [comment]
Sometimes there are breaking API changes in ORT which require adjustments to your custom templates. So if you use a recently built Docker image of ORT, you should also compare your custom NOTICE template with the default templates coming with ORT to detect any syntax changes e.g. when calling the various helper functions.

**Comment by schvvarzekatze** [comment]
Thank you. With new docker image I can execute the report with custom NOTICE template.
