### ISSUE TITLE
Error `for com.sun:tools:jar must specify an absolute path but is ${tools.jar}` in Gradle project

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#4666]
To compile the NOTICE File default.ftl I need to update the docker image.

It seems not to work with Java 8 and to require Java 11. But to test the new image locally using the `ort-gradle.sh` script with 
`ortImage="${ORT_IMAGE:-ort}"` it required Java 8 in `Dockerfile`. This is why I changed in the Dockerfile to `FROM adoptopenjdk/openjdk8:alpine-slim AS build`

When I try to build the docker image with Java 8 using the task `DOCKER_BUILDKIT=1 docker build -t ort .` I get an error as follows:

```
#14 92.47 * What went wrong:
#14 92.47 At least Java 11 is required, but Java 1.8 is being used.
#14 92.47 
#14 92.47 * Try:
#14 92.47 Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#14 92.47 
#14 92.47 * Exception is:
#14 92.47 org.gradle.api.GradleException: At least Java 11 is required, but Java 1.8 is being used.
#14 92.47 	at Build_gradle.<init>(build.gradle.kts:79)
#14 92.47 	at Program.execute(Unknown Source)
#14 92.47 	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:528)
#14 92.47 	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.evaluateSecondStageOf(Interpreter.kt:452)
#14 92.47 	at Program.execute(Unknown Source)
#14 92.47 	at org.gradle.kotlin.dsl.execution.Interpreter$ProgramHost.eval(Interpreter.kt:528)
#14 92.47 	at org.gradle.kotlin.dsl.execution.Interpreter.eval(Interpreter.kt:205)
#14 92.47 	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator.evaluate(KotlinScriptEvaluator.kt:114)
#14 92.47 	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:51)
#14 92.47 	at org.gradle.kotlin.dsl.provider.KotlinScriptPluginFactory$create$1.invoke(KotlinScriptPluginFactory.kt:36)
#14 92.47 	at org.gradle.kotlin.dsl.provider.KotlinScriptPlugin.apply(KotlinScriptPlugin.kt:34)
#14 92.48 	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
#14 92.48 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
#14 92.48 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
#14 92.48 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
#14 92.48 	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
#14 92.48 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
```

Our project code is Java 8.

What is the problem in my case? Is it the problem that our project is in Java 8 but update the ort docker image only Java 11 is allowed?

Thank you very much.

**Comment by sschuberth** [comment]
The Java version required to build and run ORT should be independent of the Java version required by a project analyzed by ORT. So there should be no need to change the `Dockerfile`.

So, to be able to help you with your actual problem, please share what error you're seeing when analyzing your Java 8 project.

**Comment by schvvarzekatze** [comment]
I just retried it with unchanged Dockerfile (Java 11) and still get the following error:

`[ERROR] 'dependencyManagement.dependencies.dependency.systemPath' for com.sun:tools:jar must specify an absolute path but is ${tools.jar} @ line 188, column 29

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:207) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.initParent(DefaultProjectBuilder.java:960) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:680) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.initParent(DefaultProjectBuilder.java:960) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.initProject(DefaultProjectBuilder.java:680) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:342) ~[maven-core-3.8.3.jar:3.8.3]
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:299) ~[maven-core-3.8.3.jar:3.8.3]
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport$parsePackage$mavenProject$2$1.invoke(MavenSupport.kt:614) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport$parsePackage$mavenProject$2$1.invoke(MavenSupport.kt:613) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport.wrapMavenSession(MavenSupport.kt:718) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport.parsePackage(MavenSupport.kt:613) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport.parsePackage$default(MavenSupport.kt:589) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.GradleDependencyHandler.createPackage(GradleDependencyHandler.kt:100) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.GradleDependencyHandler.createPackage(GradleDependencyHandler.kt:44) ~[analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.model.utils.DependencyGraphBuilder.updateResolvedPackages$lambda-25(DependencyGraphBuilder.kt:389) ~[model-DOCKER-SNAPSHOT.jar:?]
	at java.util.HashMap.compute(Unknown Source) [?:?]
	at org.ossreviewtoolkit.model.utils.DependencyGraphBuilder.updateResolvedPackages(DependencyGraphBuilder.kt:389) [model-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.model.utils.DependencyGraphBuilder.updateDependencyMappingAndPackages(DependencyGraphBuilder.kt:274) [model-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.model.utils.DependencyGraphBuilder.addDependencyToGraph(DependencyGraphBuilder.kt:242) [model-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.model.utils.DependencyGraphBuilder.addDependency(DependencyGraphBuilder.kt:149) [model-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:244) [analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:189) [analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.utils.common.UtilsKt.temporaryProperties(Utils.kt:110) [common-utils-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.managers.Gradle.resolveDependencies(Gradle.kt:189) [analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:241) [analyzer-DOCKER-SNAPSHOT.jar:?]
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:132) [analyzer-DOCKER-SNAPSHOT.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.5.31.jar:1.5.31-release-548(1.5.31)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
Caused by: org.apache.maven.model.building.ModelBuildingException: 2 problems were encountered while building the effective model for com.sun.xml.bind.mvn:jaxb-parent:2.2.11`

**Comment by sschuberth** [comment]
@schvvarzekatze I took the liberty to slightly reformat your logs to make them more readable. Can you share the project you're scanning?

**Comment by schvvarzekatze** [comment]
An empty sample gradle project with the dependency `dependencies.add("runtimeOnly", "com.sun.xml.bind:jaxb-impl:2.2.11")` will reproduce this error.

**Comment by sschuberth** [comment]
I wonder whether this error might go away when [switching to the maven-dependency-tree library](https://github.com/oss-review-toolkit/ort/issues/4720#issuecomment-973827143).

**Comment by Sukhija-Aniket** [comment]
facing the same error is there a fix or an alternative?

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
