### ISSUE TITLE
java.lang.IllegalArgumentException for EXCEL report format

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#4830]
If I want to generate an EXCEL report I get the following error:
```
13:29:59.944 [DefaultDispatcher-worker-4] WARN  org.apache.poi.util.XMLHelper - SAX Feature unsupported [log suppressed for 5 minutes]http://javax.xml.XMLConstants/property/accessExternalDTD
java.lang.IllegalArgumentException: Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:571) ~[xalan-2.7.2.jar:?]
	at org.apache.poi.util.XMLHelper.trySet(XMLHelper.java:284) [poi-5.1.0.jar:5.1.0]
	at org.apache.poi.util.XMLHelper.getTransformerFactory(XMLHelper.java:224) [poi-5.1.0.jar:5.1.0]
	at org.apache.poi.util.XMLHelper.newTransformer(XMLHelper.java:231) [poi-5.1.0.jar:5.1.0]
	at org.apache.poi.openxml4j.opc.StreamHelper.saveXmlInStream(StreamHelper.java:56) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.saveImpl(ZipContentTypeManager.java:68) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.save(ContentTypeManager.java:450) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:554) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1487) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:227) [poi-ooxml-5.1.0.jar:5.1.0]
	at org.ossreviewtoolkit.reporter.reporters.ExcelReporter.generateReport(ExcelReporter.kt:194) [reporter-DOCKER-SNAPSHOT.jar:DOCKER-SNAPSHOT]
	at org.ossreviewtoolkit.cli.commands.ReporterCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReporterCommand.kt:268) [cli-DOCKER-SNAPSHOT.jar:DOCKER-SNAPSHOT]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.5.2.jar:?]
```

On the other side all report documents are created sucessfully. `Successfully created 'Excel' report(s) at '/pxs-project/build/oss-review-toolkit/gradle/report/scan-report.xlsx' in 2s.` . If I do not want to create EXCEL report there is no such error.

**Comment by sschuberth** [comment]
This seems to be a [known bug](Not supported: http://javax.xml.XMLConstants/property/accessExternalDTD) with some JRE version. Which JRE version are you running ORT on?

**Comment by schvvarzekatze** [comment]
java.runtime.name = OpenJDK Runtime Environment
java.runtime.version = 11.0.11+9-Ubuntu-0ubuntu2.20.04

**Comment by woznik** [comment]
On my side I have the same observation
In my case it is java 11.0.8 on built docker image from the provided Dockerfile

**Comment by porsche-rbieniek** [comment]
We experienced the same issue w/ our own reporter implementation. We chose to use Saxon HE as a replacement for the embedded Xalan XSLT implementation.

A pull request has been submitted for solving this issue
