### ISSUE TITLE
`orth list-licenses` doesn't use source artifact if VCS fails

### ISSUE THREAD

**Issue by mmurto** [oss-review-toolkit/ort#4849]
I've got a result file with `Maven:com.google.guava:guava:28.0-jre` as follows:

```yaml
- package:
    id: "Maven:com.google.guava:guava:28.0-jre"
    purl: "pkg:maven/com.google.guava/guava@28.0-jre"
    authors:
    - "Google"
    declared_licenses:
    - "Apache License, Version 2.0"
    declared_licenses_processed:
      spdx_expression: "Apache-2.0"
      mapped:
        Apache License, Version 2.0: "Apache-2.0"
    description: "Guava is a suite of core and expanded libraries that include\n\
      \    utility classes, google's collections, io classes, and much\n    much\
      \ more."
    homepage_url: "https://github.com/google/guava/guava"
    binary_artifact:
      url: "https://repo.maven.apache.org/maven2/com/google/guava/guava/28.0-jre/guava-28.0-jre.jar"
      hash:
        value: "54fed371b4b8a8cce1e94a9abd9620982d3aa54b"
        algorithm: "SHA-1"
    source_artifact:
      url: "https://repo.maven.apache.org/maven2/com/google/guava/guava/28.0-jre/guava-28.0-jre-sources.jar"
      hash:
        value: "2d1dca555245ef4bacb35f25299f323d8dd10b27"
        algorithm: "SHA-1"
    vcs:
      type: "Git"
      url: "https://github.com/google/guava.git"
      revision: ""
      path: ""
    vcs_processed:
      type: "Git"
      url: "https://github.com/google/guava.git"
      revision: ""
      path: ""
  curations: []
```

Scanner uses the source artifact, but `orth list-licenses` fails with the following message:

```
Downloading sources for package 'Maven:com.google.guava:guava:28.0-jre'...
Exception in thread "main" org.ossreviewtoolkit.downloader.DownloadException: Download failed for 'Maven:com.google.guava:guava:28.0-jre'.
        at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:75)
        at org.ossreviewtoolkit.downloader.Downloader.download$default(Downloader.kt:70)
        at org.ossreviewtoolkit.helper.common.UtilsKt.fetchScannedSources(Utils.kt:189)
        at org.ossreviewtoolkit.helper.commands.ListLicensesCommand.run(ListLicensesCommand.kt:165)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at org.ossreviewtoolkit.helper.HelperMainKt.main(HelperMain.kt:61)
        Suppressed: org.ossreviewtoolkit.downloader.DownloadException: Unable to determine a revision to checkout.
                at org.ossreviewtoolkit.downloader.VersionControlSystem.getRevisionCandidates(VersionControlSystem.kt:270)
                at org.ossreviewtoolkit.downloader.VersionControlSystem.download(VersionControlSystem.kt:219)
                at org.ossreviewtoolkit.downloader.Downloader.downloadFromVcs(Downloader.kt:249)
                at org.ossreviewtoolkit.downloader.Downloader.downloadFromVcs$default(Downloader.kt:184)
                at org.ossreviewtoolkit.downloader.Downloader.handleVcsDownload(Downloader.kt:107)
                at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:79)
                ... 11 more
                Suppressed: java.io.IOException: No matching tag for version '28.0-jre' found in [v28.2, jdk5-backport-v16.0, jdk5-backport-v17.0-post, v28.1, v22.0, v24.0, jdk5-backport-release, v26.0, v19.0-rc3, v24.1, v11.0.1, v19.0-rc2, v24.1.1, v28.0, v11.0.2, v19.0-rc1, v2.0, v4.0, jdk5-backport-base, jdk5-backport-v16.0-rc1, release, v20.0, v16.0-rc1, v13.0-rc2, v23.0-rc1, v13.0-rc1, v6.0, v27.0.1, v8.0, v10.0.1, v13.0.1, v19.0, v15.0-rc1, jdk5-backport-v17.0-compatibility, v15.0-cdi1.0, v11.0, v13.0, v15.0, failureaccess-v1.0.1, v17.0, v20.0-rc1, jdk5-backport-branch-point, v12.0-rc2, v12.0-rc1, v30.0, v30.1, released-all-futures, v12.0.1, jdk5-backport-v17.0, v23.6, v29.0, v14.0-rc1, v21.0, v23.1, v23.0, v14.0-rc2, v23.3, v25.1, v14.0-rc3, v23.2, v25.0, jdk5-backport-v17.0-rc2, v23.5, v27.1, jdk5-backport-v17.0-rc1, v23.4, v27.0, v23.6.1, v1.0, v18.0-rc2, v21.0-rc1, v14.0.1, v3.0, v11.0-rc1, v18.0-rc1, v21.0-rc2, v31.0.1, v9.0, v5.0, v7.0, v18.0, v13.0-final, v30.1.1, v10.0-rc1, v10.0, v12.0, v14.0, v10.0-rc3, v10.0-rc2, v16.0, v31.0, v16.0.1, v17.0-rc1, v22.0-rc1, v17.0-rc2]. Please create a tag whose name contains the version.
                        at org.ossreviewtoolkit.downloader.WorkingTree.guessRevisionName(WorkingTree.kt:97)
                        at org.ossreviewtoolkit.downloader.VersionControlSystem.getRevisionCandidates$addGuessedRevision(VersionControlSystem.kt:294)
                        at org.ossreviewtoolkit.downloader.VersionControlSystem.getRevisionCandidates(VersionControlSystem.kt:313)
                        ... 16 more
        Suppressed: org.ossreviewtoolkit.downloader.DownloadException: No source artifact URL provided for 'Maven:com.google.guava:guava:28.0-jre'.
                at org.ossreviewtoolkit.downloader.Downloader.downloadSourceArtifact(Downloader.kt:291)
                at org.ossreviewtoolkit.downloader.Downloader.handleSourceArtifactDownload(Downloader.kt:149)
                at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:80)
                ... 11 more
```

Should `list-licenses` use the source artifact as well?

**Comment by mnonnenmacher** [comment]
@mmurto The command uses this function to download the source code:

https://github.com/oss-review-toolkit/ort/blob/b2cd9eeeb3275c0b1371f62ec94ca64d622f32ca/helper-cli/src/main/kotlin/common/Utils.kt#L178-L192

It already checks the provenance of the scan result and only downloads from there. Please check what the `provenance` property is in the scan result for Maven:com.google.guava:guava:28.0-jre in your ORT result.

/cc  @fviernau

**Comment by fviernau** [comment]
As @mnonnenmacher outline: it should download the source artifact only if it actually was scanned. So looking into the `scan-result.json` whether it was scanned should be the right direction. (Haven't checked if the command works still for that, it did so in the past).

**Comment by mmurto** [comment]
The provenance seems to include source archive:

```yaml
Maven:com.google.guava:guava:28.0-jre:
- provenance:
    source_artifact:
      url: "https://repo.maven.apache.org/maven2/com/google/guava/guava/28.0-jre/guava-28.0-jre-sources.jar"
      hash:
        value: "2d1dca555245ef4bacb35f25299f323d8dd10b27"
        algorithm: "SHA-1"
```

 I created [a test repo](https://github.com/mmurto/orth-test-repo) that reproduces the error for me. Here's also a [scan-result.zip](https://github.com/oss-review-toolkit/ort/files/7734351/scan-result.zip) for the repo above, if it's faster for you to check that way.

**Comment by mnonnenmacher** [comment]
@mmurto Thanks for the scan result, this helped finding the issue (see #4886).
