### ISSUE TITLE
Test cases of ScanCodeScannerFunTest failed

### ISSUE THREAD

**Issue by ldang0** [oss-review-toolkit/ort#5002]
```
$ ./gradlew :scanner:funTest --tests org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest

> Configure project :
Building ORT version 64bfa05d8d.

> Task :scanner:funTest

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > Scanning a single file succeeds STARTED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > Scanning a single file succeeds PASSED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > Scanning a directory succeeds STARTED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > Scanning a directory succeeds PASSED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the full license text for the HERE proprietary license STARTED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the full license text for the HERE proprietary license FAILED
    java.lang.AssertionError: Expecting actual not to be null
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$1.invokeSuspend(ScanCodeScannerFunTest.kt:43)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$1.invoke(ScanCodeScannerFunTest.kt)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$1.invoke(ScanCodeScannerFunTest.kt)

        Caused by:
        java.lang.AssertionError: Expecting actual not to be null
            at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$1.invokeSuspend(ScanCodeScannerFunTest.kt:43)
            ... 2 more

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the full license text for a known SPDX LicenseRef STARTED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the full license text for a known SPDX LicenseRef FAILED
    java.lang.AssertionError: Expecting actual not to be null
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$2.invokeSuspend(ScanCodeScannerFunTest.kt:50)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$2.invoke(ScanCodeScannerFunTest.kt)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$2.invoke(ScanCodeScannerFunTest.kt)

        Caused by:
        java.lang.AssertionError: Expecting actual not to be null
            at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$2.invokeSuspend(ScanCodeScannerFunTest.kt:50)
            ... 2 more

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the ort license text for a license ID known by ort and also in custom dir STARTED

org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest > return the ort license text for a license ID known by ort and also in custom dir FAILED
    java.lang.AssertionError: Expected null but actual was "x
    y
    "
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$3.invokeSuspend(ScanCodeScannerFunTest.kt:60)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$3.invoke(ScanCodeScannerFunTest.kt)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$3.invoke(ScanCodeScannerFunTest.kt)

        Caused by:
        java.lang.AssertionError: Expected null but actual was "x
        y
        "
            at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeScannerFunTest$3.invokeSuspend(ScanCodeScannerFunTest.kt:60)
            ... 2 more

5 tests completed, 3 failed
```

**Comment by sschuberth** [comment]
Can you set a breakpoint in ScanCode's `bootstrap()` function and debug the test from the IDE to verify ScanCode has actually been bootstrapped correctly?

**Comment by ldang0** [comment]
> Can you set a breakpoint in ScanCode's `bootstrap()` function and debug the test from the IDE to verify ScanCode has actually been bootstrapped correctly?

Did that and ScanCode has been bootstrapped successfully.

**Comment by sschuberth** [comment]
I guess this issue is obsolete now that we do not bootstrap scanners anymore but require the environment to provide them. I cannot reproduce the issue either, esp. not with https://github.com/oss-review-toolkit/ort/pull/10134 merged, which gives better error messages if scanners are not available in the PATH environment.
