### ISSUE TITLE
Miscellaneous experimental scanner crashes

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#5187]
I've run a couple of test scans with the experimental scanner using ORT revision 2c87d01. I found the following crashes:

**From a Git-Repo project**

```
Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/Automattic/engine.io-client.git, revision=57ca9fea8ebf7d0762d6d1eeda302d622226243c, path=support/web-socket-js), resolvedRevision=57ca9fea8ebf7d0762d6d1eeda302d622226243c) with path scanner ScanCode finished.
org.ossreviewtoolkit.scanner.experimental.ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
	at org.ossreviewtoolkit.scanner.experimental.UtilsKt.requireEmptyVcsPath(Utils.kt:30)
	at org.ossreviewtoolkit.scanner.experimental.ProvenanceBasedPostgresStorage.write(ProvenanceBasedPostgresStorage.kt:130)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.storeProvenanceScanResult(ExperimentalScanner.kt:435)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.runPathScanners(ExperimentalScanner.kt:267)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:143)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:92)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runExperimental$1.invokeSuspend(ScannerCommand.kt:342)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runExperimental(ScannerCommand.kt:341)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:205)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
14:35:47.335 [main] WARN  org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner - Could not write scan result for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/Automattic/engine.io-client.git, revision=57ca9fea8ebf7d0762d6d1eeda302d622226243c, path=support/web-socket-js), resolvedRevision=57ca9fea8ebf7d0762d6d1eeda302d622226243c) to ProvenanceBasedPostgresStorage: ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
Exception in thread "main" java.util.NoSuchElementException: Key RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/cucumber/cucumber-ruby.git, revision=, path=), resolvedRevision=5066ada198a13431f39421ab07d316f3efd751e8) is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenance(ScanController.kt:122)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenancesByPackage(ScanController.kt:129)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:145)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:92)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runExperimental$1.invokeSuspend(ScannerCommand.kt:342)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runExperimental(ScannerCommand.kt:341)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:205)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
```
**From a Git-Repo project**
```
17:17:52.487 [main] INFO  org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner - Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://android.googlesource.com/platform/libcore, revision=87cb925a53fb5fbe38cdce61727d8f9ec9362945, path=), resolvedRevision=87cb925a53fb5fbe38cdce61727d8f9ec9362945) with path scanner ScanCode finished.
Exception in thread "main" java.util.NoSuchElementException: Key RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/cucumber/cucumber-ruby.git, revision=, path=), resolvedRevision=5066ada198a13431f39421ab07d316f3efd751e8) is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenance(ScanController.kt:122)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenancesByPackage(ScanController.kt:129)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:145)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:92)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runExperimental$1.invokeSuspend(ScannerCommand.kt:342)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runExperimental(ScannerCommand.kt:341)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:205)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
```
**From a Git project (why does it have SVN nested?)**
```
15:08:01.531 [main] INFO  org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner - Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/google/benchmark.git, revision=360e66c1c4777c99402cf8cd535aa510fee16573, path=), resolvedRevision=360e66c1c4777c99402cf8cd535aa510fee16573) with path scanner ScanCode finished.
Exception in thread "main" java.util.NoSuchElementException: Key RepositoryProvenance(vcsInfo=VcsInfo(type=Subversion, url=https://svn.apache.org/repos/asf/xerces/xml-commons, revision=tags/xml-commons-external-1_3_04, path=), resolvedRevision=478305) is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenance(ScanController.kt:122)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedProvenancesByPackage(ScanController.kt:129)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:145)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:92)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runExperimental$1.invokeSuspend(ScannerCommand.kt:342)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runExperimental(ScannerCommand.kt:341)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:205)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
Build step 'Execute shell' marked build as failure
```

**Comment by mnonnenmacher** [comment]
@fviernau This should address part of the issues:
https://github.com/oss-review-toolkit/ort/pull/5200

For the last one it does not look like a nested provenance to me, but rather that the package has SVN provenance, so this should also be addressed by my PR. I will later add another PR that improves error reporting, because currently issues with provenance resolution are only logged to the command line, but not added as issues to the result file.

**Comment by mnonnenmacher** [comment]
@fviernau With #5241 all issues should be addressed, please re-open or create another issue if you find more problems.
