### ISSUE TITLE
Advisor OssIndexService MissingFieldException Field 'displayName' is missing

### ISSUE THREAD

**Issue by nanguax** [oss-review-toolkit/ort#5381]
Hello I've been encountering similar errors to #4607 and #4557.
```
Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'displayName' is required for type with serial name 'org.ossreviewtoolkit.clients.ossindex.OssIndexService.Vulnerability', but it was missing at path: $[9].vulnerabilities[0] at path: $[9].vulnerabilities[0] at path: $[9].vulnerabilities[0] at path: $[9].vulnerabilities[0]
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:40)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:100)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.Serializer$FromString.fromResponseBody(Serializer.kt:30)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:11)
        at com.jakewharton.retrofit2.converter.kotlinx.serialization.DeserializationStrategyConverter.convert(DeserializationStrategyConverter.kt:7)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Thank you for the help.

**Comment by sschuberth** [comment]
Hi @nanguax, could you please provide example artifact coordinates for which this happens? I wonder what other "mandatory" fields could be missing in the response.

**Comment by sschuberth** [comment]
And meanwhile, could you check whether https://github.com/oss-review-toolkit/ort/pull/5383 fixes your issue?
