### ISSUE TITLE
Analyzing ORT with itself throws exception

### ISSUE THREAD

**Issue by pepper-jk** [oss-review-toolkit/ort#5426]
Hi there,

I just started using this tool at work and tried to analyze this repo with it.
Sadly ORT throws an exception, when scanning itself.

Here is the terminal output:

```
$ docker run --rm -it -v $PWD:/project --entrypoint=/bin/bash censored.url/ort-image:latest
root@2732316eb1e0:/# ort --info analyze \
>     -i /project \
>     -o /project/ort/analyzer;

________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version DOCKER-SNAPSHOT-ee57c022fd0d817497999b9bc6f28855ce5c1e54.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'analyze' under Java 11.0.15 on Linux with
\_______  /____|_  / |____|    4 CPUs and a maximum of 4002 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /root/.ort/config
ORT_DATA_DIR = /root/.ort
TERM = xterm
http_proxy = censored.proxy.url
https_proxy = censored.proxy.url
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /tmp/go

Looking for analyzer-specific configuration in the following files and directories:
        /root/.ort/config/curations.yml (does not exist)
        /root/.ort/config/curations (does not exist)
        /project/.ort.yml
        /root/.ort/config/resolutions.yml (does not exist)
The following package managers are activated:
        Bower, Bundler, Cargo, Carthage, CocoaPods, Composer, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Unmanaged, Yarn
Analyzing project path:
        /project
11:31:41.205 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/examples/notifications/src/main/resources' as it is hard-coded to be ignored.
11:31:41.208 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/examples/evaluator-rules/src/main/resources' as it is hard-coded to be ignored.
11:31:41.215 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/evaluator/src/main/resources' as it is hard-coded to be ignored.
11:31:41.218 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/advisor/src/main/resources' as it is hard-coded to be ignored.
11:31:41.220 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/detekt-rules/src/main/resources' as it is hard-coded to be ignored.
11:31:41.237 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/.git' as it is hard-coded to be ignored.
11:31:41.242 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/scanner/src/main/resources' as it is hard-coded to be ignored.
11:31:41.251 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/main/resources' as it is hard-coded to be ignored.
11:31:41.274 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/node_modules' as it is hard-coded to be ignored.
11:31:41.278 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/resources' as it is hard-coded to be ignored.
11:31:41.291 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/test/src/main/resources' as it is hard-coded to be ignored.
11:31:41.293 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/spdx/src/main/resources' as it is hard-coded to be ignored.
11:31:41.297 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/common/src/main/resources' as it is hard-coded to be ignored.
11:31:41.307 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/model/src/main/resources' as it is hard-coded to be ignored.
11:31:41.317 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/downloader/src/main/resources' as it is hard-coded to be ignored.
11:31:41.319 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/cli/src/main/resources' as it is hard-coded to be ignored.
11:31:41.321 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/reporter/src/main/resources' as it is hard-coded to be ignored.
11:31:41.328 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/notifier/src/main/resources' as it is hard-coded to be ignored.
11:31:42.014 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
11:31:42.037 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
11:31:42.042 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/examples/notifications/src/main/resources' as it is hard-coded to be ignored.
11:31:42.043 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/examples/evaluator-rules/src/main/resources' as it is hard-coded to be ignored.
11:31:42.047 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/evaluator/src/main/resources' as it is hard-coded to be ignored.
11:31:42.049 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/advisor/src/main/resources' as it is hard-coded to be ignored.
11:31:42.050 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/detekt-rules/src/main/resources' as it is hard-coded to be ignored.
11:31:42.063 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/.git' as it is hard-coded to be ignored.
11:31:42.066 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/scanner/src/main/resources' as it is hard-coded to be ignored.
11:31:42.069 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/main/resources' as it is hard-coded to be ignored.
11:31:42.079 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/funTest/assets/projects/synthetic/npm/node-modules/node_modules' as it is hard-coded to be ignored.
11:31:42.081 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/analyzer/src/funTest/assets/projects/synthetic/sbt-http4s-template/src/main/resources' as it is hard-coded to be ignored.
11:31:42.087 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/test/src/main/resources' as it is hard-coded to be ignored.
11:31:42.088 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/spdx/src/main/resources' as it is hard-coded to be ignored.
11:31:42.090 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/utils/common/src/main/resources' as it is hard-coded to be ignored.
11:31:42.095 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/model/src/main/resources' as it is hard-coded to be ignored.
11:31:42.097 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/downloader/src/main/resources' as it is hard-coded to be ignored.
11:31:42.098 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/cli/src/main/resources' as it is hard-coded to be ignored.
11:31:42.099 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/reporter/src/main/resources' as it is hard-coded to be ignored.
11:31:42.102 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/project/notifier/src/main/resources' as it is hard-coded to be ignored.
11:31:42.210 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator is already installed.
11:31:42.210 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector is already installed.
11:31:42.216 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/project-xyz-with-inline-packages.spdx.yml'.
11:31:42.320 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/project-xyz-with-transitive-dependencies.spdx.yml'.
11:31:42.324 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/project-xyz-with-package-references.spdx.yml'.
11:31:42.327 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/libs/openssl/package.spdx.yml'.
11:31:42.330 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/libs/curl/package.spdx.yml'.
11:31:42.332 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/libs/my-lib/package.spdx.yml'.
11:31:42.337 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/analyzer/src/funTest/assets/projects/synthetic/spdx/libs/zlib/package.spdx.yml'.
11:31:42.338 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/utils/spdx/src/test/assets/spdx-spec-examples/SPDXYAMLExample-2.2.spdx.yaml'.
11:31:42.372 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/utils/spdx/src/test/assets/spdx-spec-examples/SPDXYAMLExample-2.2-no-ranges.spdx.yaml'.
11:31:42.387 [main] INFO  org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache - Loading SpdxDocument from '/project/utils/spdx/src/test/assets/spdx-spec-examples/SPDXYAMLExample-2.2-no-relationship-describes-or-document-describes.spdx.yaml'.
Exception in thread "main" com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.ossreviewtoolkit.utils.spdx.model.SpdxDocument`, problem: The document must either have at least one relationship of type 'DESCRIBES' or contain the 'documentDescribes' field.
 at [Source: (File); line: 382, column: 1]
        at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2047)
        at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1400)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapInstantiationProblem(BeanDeserializerBase.java:1866)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
        at org.ossreviewtoolkit.analyzer.managers.utils.SpdxDocumentCache.load(SpdxDocumentCache.kt:70)
        at org.ossreviewtoolkit.analyzer.managers.SpdxDocumentFile.mapDefinitionFiles(SpdxDocumentFile.kt:417)
        at org.ossreviewtoolkit.analyzer.Analyzer.findManagedFiles(Analyzer.kt:77)
        at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:242)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:393)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:390)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:408)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:433)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:81)
Caused by: java.lang.IllegalArgumentException: The document must either have at least one relationship of type 'DESCRIBES' or contain the 'documentDescribes' field.
        at org.ossreviewtoolkit.utils.spdx.model.SpdxDocument.<init>(SpdxDocument.kt:167)
        at org.ossreviewtoolkit.utils.spdx.model.SpdxDocument.<init>(SpdxDocument.kt:36)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
        at com.fasterxml.jackson.module.kotlin.ValueCreator.callBy(ValueCreator.kt:45)
        at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:135)
        at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:518)
        ... 18 more
```

We are running it in a docker container, which is build from this repo. As you can see the version running here is from Jun 2 (commit ee57c02). The repo I scanned is a bit newer and the most current commit is 1be897cbb787b6fbb9eec2ffdf8e4db09b633749.

I did not have the time today to update both image and repo and test it again, but maybe this helps you as is and this issue is not out of date.

I did not have this issue with other projects I scanned so far. Disclaimer: I only scanned 2 more.

Keep up the good work!

**Comment by mnonnenmacher** [comment]
Thanks for reporting @pepper-jk, the test asset is deliberately broken, but this should not crash the analyer. I have created a PR to address that.
