### ISSUE TITLE
ort scan:  IllegalStateException "The package and project scanners need to refer to the same global scanner configuration."

### ISSUE THREAD

**Issue by mawl** [oss-review-toolkit/ort#5460]
Hey,

According to my understanding, the parameter --package-types PACKAGE with possible values [PACKAGE,PROJECT] should exclude the project from being scanned and should only scan the packages/dependencies.

`ort scan -i ${ORT_OUTPUT_DIR}/analyzer-result.yml -o ${ORT_OUTPUT_DIR}  --package-types PACKAGE`

But it leads to: 
`Exception in thread "main" java.lang.IllegalStateException: The package and project scanners need to refer to the same global scanner configuration.
	at org.ossreviewtoolkit.scanner.ScannerKt.scanOrtResult(Scanner.kt:155)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:314)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:235)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:393)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:390)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:408)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:433)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:81)`

Any ideas?

Cheers,
Marco

**Comment by mnonnenmacher** [comment]
@mawl Thanks for reporting, the linked PR should fix the issue.

**Comment by mawl** [comment]
@mnonnenmacher: Thanks a lot :)
