### ISSUE TITLE
GoMod: Runs out of memory when analyzing the 'ossf/scorecard' project hosted on GitHub

### ISSUE THREAD

**Issue by qequ** [oss-review-toolkit/ort#5627]
Testing [Scorecard](https://github.com/ossf/scorecard) project ort ran out of heap memory with analyze tool.

command: `./cli/build/install/ort/bin/ort analyze -i ~/scorecard/ -o ortScorecard/`

ort dump:
```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 918e64e8eb.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'analyze' under Java 17.0.3 on Linux with
\_______  /____|_  / |____|    8 CPUs and a maximum of 5956 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /home/alvaro/.ort/config
ORT_DATA_DIR = /home/alvaro/.ort
SHELL = /bin/bash
TERM = xterm-256color

Looking for analyzer-specific configuration in the following files and directories:
	/home/alvaro/.ort/config/curations.yml (does not exist)
	/home/alvaro/.ort/config/curations (does not exist)
	/home/alvaro/scorecard/.ort.yml (does not exist)
	/home/alvaro/.ort/config/resolutions.yml (does not exist)
The following package managers are enabled:
	Bower, Bundler, Cargo, Carthage, CocoaPods, Composer, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, Poetry, Pub, SBT, SpdxDocumentFile, Stack, Unmanaged, Yarn, Yarn2
Analyzing project path:
	/home/alvaro/scorecard
Found 2 GoMod definition file(s) at:
	go.mod
	tools/go.mod
Found 2 definition file(s) from 1 package manager(s) in total.
Aug 01, 2022 4:39:26 PM org.tmatesoft.svn.core.internal.util.DefaultSVNDebugLogger log
SEVERE: WC: Java heap space
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.HashMap$KeySet.iterator(HashMap.java:983)
	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool.shutdownInactiveRepositories(DefaultSVNRepositoryPool.java:520)
	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool.access$200(DefaultSVNRepositoryPool.java:69)
	at org.tmatesoft.svn.core.wc.DefaultSVNRepositoryPool$TimeoutTask.run(DefaultSVNRepositoryPool.java:534)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

16:39:26.629 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for path 'go.mod' failed with: OutOfMemoryError: Java heap space

```

**Comment by fviernau** [comment]
@qequ how much RAM does the machine have and can you fix this by setting the environment variable to give more memore to the JVM? like:
```
export ORT_OPTS="-Xmx16G"
```

**Comment by dgutson** [comment]
Hi @fviernau, his computer has 16gb ram, and probably that will make it, but it is a brute force solution and it is a matter of time until we crash against another package that will need more memory.
Why is this process so much ram hungry, how can we limit it so it takes eg more time? I mean, if we can turn the unbounded memory variable into a 2 variables problem, like memory (bounded) and time (unbounded) then we can avoid crashes and will be able to run ORT safely.

**Comment by dgutson** [comment]
Maybe limiting the amount of concurrent processes?

**Comment by fviernau** [comment]
@qequ I came up with above fix. Would you mind testing it?

**Comment by qequ** [comment]
@fviernau Just tested the analyze tool on scorecard again and it worked great, no need of extra memory 👍

**Comment by fviernau** [comment]
> @fviernau Just tested the analyze tool on scorecard again and it worked great, no need of extra memory +1

Thanks!
