### ISSUE TITLE
Unreliable Docker builds by 503 Service Unavailable on SW360 dependency

### ISSUE THREAD

**Issue by nicorikken** [oss-review-toolkit/ort#5641]
As I'm running daily container builds at https://github.com/alliander-opensource/ort-container I noticed that over the weekend the builds failed because of the `org.eclipse.sw360:client:13.2.0-28` dependency. A more detailed of the [build](https://github.com/alliander-opensource/ort-container/runs/7712164455?check_suite_focus=true#step:9:3122) error is below:
```
 /usr/bin/git log -1 --format='%H'
'397378e110904c0980ebd26f49313210c73c21a2'
...
/usr/bin/docker buildx build --iidfile /tmp/docker-build-push-j6K6zY/iidfile --load --metadata-file /tmp/docker-build-push-j6K6zY/metadata-file .
...
#14 [build 4/4] RUN --mount=type=cache,target=/tmp/.gradle/     export GRADLE_USER_HOME=/tmp/.gradle/ &&     scripts/import_proxy_certs.sh &&     scripts/set_gradle_proxy.sh &&     sed -i -r 's,(^distributionUrl=)(.+)-all\.zip$,\1\2-bin.zip,' gradle/wrapper/gradle-wrapper.properties &&     sed -i -r '/distributionSha256Sum=[0-9a-f]{64}/d' gradle/wrapper/gradle-wrapper.properties &&     ./gradlew --no-daemon --stacktrace -Pversion=DOCKER-SNAPSHOT :cli:distTar :helper-cli:startScripts
...
#14 335.1 > Task :reporter-web-app:yarnInstall
#14 335.1 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#14 335.1 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 335.1 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
#14 335.1 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
#14 335.1 [3/4] Linking dependencies...
#14 335.1 warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
#14 335.1 warning " > @testing-library/user-event@13.2.1" has unmet peer dependency "@testing-library/dom@>=7.21.4".
#14 335.1 warning " > html-inline-css-webpack-plugin@1.11.1" has unmet peer dependency "html-webpack-plugin@^3.0.0 || ^4.0.0 || ^5.0.0".
#14 335.2 warning Workspaces can only be enabled in private projects.
#14 355.7 [4/4] Building fresh packages...
#14 357.0 Done in 67.20s.
#14 378.7 
#14 378.7 FAILURE: Build failed with an exception.
#14 378.7 
#14 378.7 * What went wrong:
#14 378.7 Execution failed for task ':analyzer:compileKotlin'.
#14 378.7 > Error while evaluating property 'filteredArgumentsMap' of task ':analyzer:compileKotlin'
#14 378.7    > Could not resolve all files for configuration ':analyzer:compileClasspath'.
#14 378.7       > Could not resolve org.eclipse.sw360:client:13.2.0-28.
#14 378.7         Required by:
#14 378.7             project :analyzer
#14 378.7          > Could not resolve org.eclipse.sw360:client:13.2.0-28.
#14 378.7             > Could not get resource 'https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/13.2.0-28/client-13.2.0-28.pom'.
#14 378.7                > Could not GET 'https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/13.2.0-28/client-13.2.0-28.pom'. Received status code 503 from server: Service Unavailable
#14 378.7 
#14 378.7 * Try:
#14 378.7 > Run with --info or --debug option to get more log output.
#14 378.7 > Run with --scan to get full insights.
#14 378.7 
#14 378.7 * Exception is:
#14 378.7 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':analyzer:compileKotlin'.
#14 378.7 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
#14 378.7 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
...
#14 378.7 Caused by: org.gradle.api.internal.tasks.properties.PropertyEvaluationException: Error while evaluating property 'filteredArgumentsMap' of task ':analyzer:compileKotlin'
#14 378.7 	at org.gradle.api.internal.tasks.properties.InputParameterUtils.prepareInputParameterValue(InputParameterUtils.java:33)
...
#14 378.7 Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':analyzer:compileClasspath'.
#14 378.7 	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1524)
...
#14 378.7 Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.eclipse.sw360:client:13.2.0-28.
#14 378.7 Required by:
#14 378.7     project :analyzer
#14 378.7 Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.eclipse.sw360:client:13.2.0-28.
#14 378.7 Caused by: org.gradle.api.resources.ResourceException: Could not get resource 'https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/13.2.0-28/client-13.2.0-28.pom'.
#14 378.7 	at org.gradle.internal.resource.ResourceExceptions.failure(ResourceExceptions.java:74)
...
#14 378.7 Caused by: org.gradle.internal.resource.transport.http.HttpErrorStatusCodeException: Could not GET 'https://repo.eclipse.org/content/repositories/sw360-releases/org/eclipse/sw360/client/13.2.0-28/client-13.2.0-28.pom'. Received status code 503 from server: Service Unavailable
#14 378.7 	at org.gradle.internal.resource.transport.http.HttpClientHelper.processResponse(HttpClientHelper.java:215)
...
#14 378.7 BUILD FAILED in 6m 18s
#14 378.8 32 actionable tasks: 32 executed
#14 ERROR: executor failed running [/bin/sh -c export GRADLE_USER_HOME=/tmp/.gradle/ &&     scripts/import_proxy_certs.sh &&     scripts/set_gradle_proxy.sh &&     sed -i -r 's,(^distributionUrl=)(.+)-all\.zip$,\1\2-bin.zip,' gradle/wrapper/gradle-wrapper.properties &&     sed -i -r '/distributionSha256Sum=[0-9a-f]{64}/d' gradle/wrapper/gradle-wrapper.properties &&     ./gradlew --no-daemon --stacktrace -Pversion=$ORT_VERSION :cli:distTar :helper-cli:startScripts]: exit code: 1
```

It worries me that two days in a row a 503 error is raised on the repository. Perhaps we can configure mirrors as a backup in case the primary repository fails?

**Comment by sschuberth** [comment]
We should probably try to address this via https://github.com/eclipse/sw360/issues/1259 to not depend on a weekly build of the SW360 client library anymore at all.

**Comment by sschuberth** [comment]
@nicorikken do you still see this happening now that https://github.com/oss-review-toolkit/ort/pull/5697 is merged?

**Comment by sschuberth** [comment]
I'm closing this for now. Feel free to reopen if it reoccurs.
