### ISSUE TITLE
package-configuration file parsing bug

### ISSUE THREAD

**Issue by pepper-jk** [oss-review-toolkit/ort#5739]
## Preparation:

I created a package-configuration for `PyPI::pillow:9.2.0` based on the examples in https://github.com/oss-review-toolkit/ort-config.

```yaml
---
id: "PyPI::pillow:9.2.0"
source_artifact_url: "https://files.pythonhosted.org/packages/8c/92/2975b464d9926dc667020ed1abfa6276e68c3571dcb77e43347e15ee9eed/Pillow-9.2.0.tar.gz"
path_excludes:
  - pattern: "Pillow-9.2.0/docs/**"
    reason: "DOCUMENTATION_OF"
  - pattern: "Pillow-9.2.0/Tests/**"
    reason: "TEST_OF"
```

## Bug:

I then tried to pass it to `ort-evaluate` via `--package-configuration-file path/to/source-artifact.yml`, but this produces the following error (on both 1020272b9baeabe28a685e4dfa43ba380e66f6b1 and 3696a8eb960da464481ea9295fdca8b54801af26):

```
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version DOCKER-SNAPSHOT-1020272b9baeabe28a685e4dfa43ba380e66f6b1.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'evaluate' under Java 11.0.16 on Linux with
\_______  /____|_  / |____|    4 CPUs and a maximum of 4002 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /config
ORT_DATA_DIR = /root/.ort
TERM = xterm
http_proxy = <cencored>
https_proxy = <cencored>
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
GOPATH = /tmp/go

Looking for evaluator-specific configuration in the following files and directories:
        /config/copyright-garbage.yml
        /config/license-classifications/generic.yml
13:09:28.562 [main] INFO  org.ossreviewtoolkit.cli.commands.EvaluatorCommand - Read ORT result from 'scan-result.yml' (0.26 MiB) in 1.014654859s.
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.util.ArrayList<org.ossreviewtoolkit.model.config.PackageConfiguration>` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (File); line: 2, column: 1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1515)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1462)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:392)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:252)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
        at org.ossreviewtoolkit.model.utils.FilePackageConfigurationProvider.<init>(SimplePackageConfigurationProvider.kt:91)
        at org.ossreviewtoolkit.cli.utils.PackageConfigurationOptionKt.createProvider(PackageConfigurationOption.kt:37)
        at org.ossreviewtoolkit.cli.commands.EvaluatorCommand.run(EvaluatorCommand.kt:297)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:81)
```

## Current Workaround(s):

If I only pass it via `--package-configuration-dir path/to/`, it works without a hitch.

## Additional Information:

At first I added all current package-configurations from https://github.com/oss-review-toolkit/ort-config to my repo, while keeping the directory structure. I then noticed that passing `--package-configuration-dir package-configurations/PyPI/` does not work at all. This is pretty counter intuitive.

It appears `--package-configuration-dir` only supports directories with YAML files, each including a package-configuration. The [pkg config documentation](https://github.com/oss-review-toolkit/ort/blob/main/docs/config-file-package-configuration-yml.md#command-line) also implies this.

However, if you keep the directory structure in the example config, I would recommend supporting it as is. This way, it would be also cleaner to manage large number of package-configurations within one config repo.

**Comment by sschuberth** [comment]
Note that the YAML file you point the `--package-configuration-file` option at is supposed to contain a list / array of package configurations, not a single package configuration. So by design you're not supposed to point that option at a single package configuration file from a hierarchy of package configurations. The latter is what `--package-configuration-dir`. So you should only use either option, depending on whether you decided to organize your package configurations all within a single file, or in a directory structure. It's either or.

**Comment by pepper-jk** [comment]
> Note that the YAML file you point the `--package-configuration-file` option at is supposed to contain a list / array of package configurations, not a single package configuration.

Could you provide an example? I fail to find one in the config repo.

Do you mean a index/list of individual pkg config files, or a file containing all pkg config files, but in a YAML list structure?

**Comment by pepper-jk** [comment]
> So by design you're not supposed to point that option at a single package configuration file from a hierarchy of package configurations. The latter is what `--package-configuration-dir`. So you should only use either option, depending on whether you decided to organize your package configurations all within a single file, or in a directory structure. It's either or.

Wait! So the `-dir` param points to a directory of files, without supporting any kind of (sub-)directory structure? And the `-file` param points to an index file for a more complex directory structure?

From a certain point of view this is the total opposite of what a user would expect.

Why not parse all yaml files in a directory no matter the dir structure? This would be way more user friendly and the `-file` parameter could be omitted or actually be used with a single file, with all pkg configs.

**Comment by sschuberth** [comment]
Are there any more open questions on this topic @pepper-jk?
