### ISSUE TITLE
CocoaPods IOException resolving pod based on Git

### ISSUE THREAD

**Issue by unclejay80** [oss-review-toolkit/ort#5834]
Got this error in the web report:

```
[CocoaPods::Podfile:](https://github.com/oss-review-toolkit/ort/issues/new#CocoaPods::Podfile:)
2022-09-19T21:43:49.421661Z [ERROR]: CocoaPods - Resolving CocoaPods dependencies for path 'Podfile' failed with: IOException: Running 'pod spec which AnalyticsEvents --version=0.1.0 --allow-root --regex' in '.../ort-gitlab/project' failed with exit code 1:
[!] Unable to find a pod with name matching `AnalyticsEvents'
```
from the logfile (with level warn):
```
java.io.IOException: Running 'pod spec which AnalyticsEvents --version=0.1.0 --allow-root --regex' in '/.../tools/ort-gitlab/project' failed with exit code 1:
[!] Unable to find a pod with name matching `AnalyticsEvents'
	at org.ossreviewtoolkit.utils.common.ProcessCapture.requireSuccess(ProcessCapture.kt:148)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:74)
	at org.ossreviewtoolkit.analyzer.managers.CocoaPods.run(CocoaPods.kt:73)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run$default(CommandLineTool.kt:68)
	at org.ossreviewtoolkit.analyzer.managers.CocoaPods.getPodspec(CocoaPods.kt:207)
	at org.ossreviewtoolkit.analyzer.managers.CocoaPods.getPackage(CocoaPods.kt:175)
	at org.ossreviewtoolkit.analyzer.managers.CocoaPods.resolveDependenciesInternal(CocoaPods.kt:141)
	at org.ossreviewtoolkit.analyzer.managers.CocoaPods.resolveDependencies(CocoaPods.kt:118)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:264)
	at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:322)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:[570](https://dl-.../tools/ort-gitlab/-/jobs/198586#L570))
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
21:43:49.424 [DefaultDispatcher-worker-3] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Resolving CocoaPods dependencies for path 'Podfile' failed with: IOException: Running 'pod spec which AnalyticsEvents --version=0.1.0 --allow-root --regex' in '.../tools/ort-gitlab/project' failed with exit code 1:
[!] Unable to find a pod with name matching `AnalyticsEvents'
```

Because of this the whole content of the Podfile is ignored.

Should also happen with the following project: https://github.com/vector-im/element-ios
Problem seems to be this line: https://github.com/vector-im/element-ios/blob/develop/Podfile#L76 :

`pod 'AnalyticsEvents', :git => 'https://github.com/matrix-org/matrix-analytics-events.git', :branch => 'release/swift', :inhibit_warnings => false`

**Comment by sschuberth** [comment]
Thanks for the report @unclejay80! As a stop-gap measure I've created https://github.com/oss-review-toolkit/ort/pull/5835. But you'll still be missing metadata for that package I believe.

**Comment by unclejay80** [comment]
great :) thanks!! working now - metadata is still missing. Do you want to keep the issue open for the metadata stuff or what would you recommend?

**Comment by sschuberth** [comment]
> Do you want to keep the issue open for the metadata stuff or what would you recommend?

I decided to create a [follow-up issue](https://github.com/oss-review-toolkit/ort/issues/5841) with a more specific title.
