### ISSUE TITLE
Scanner is taking much longer and fails to fetch packages

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#6027]
We noticed significant slowdowns in scans: the scanner hours to scan projects that previously took minutes.
This can be reproduced with [MoveTK](https://github.com/movetk/movetk), latest version.

Description:
The scanner starts it's normal operations, once in a while output lines are printed which start with a timestamp.
Then, for hours we get a series of similar errors, without any timestamp in between.
Right before these errors we get:
```
06:49:17.829 [DefaultDispatcher-worker-62] WARN  org.ossreviewtoolkit.downloader.vcs.Git - Failed to fetch everything: InvalidRemoteException: Invalid remote: origin
Caused by: NoRemoteRepositoryException: ssh://git@github.com/substack/node-shell-quote.git: ERROR: Repository not found.
java.io.IOException: Could not resolve revision for package 'NPM::shell-quote:1.7.3' with VcsInfo(type=Git, url=ssh://git@github.com/substack/node-shell-quote.git, revision=6a8a899c62a58a30fb128a7079f02826ed4faee0, path=):
	Could not resolve revision candidate '6a8a899c62a58a30fb128a7079f02826ed4faee0': InvalidRemoteException: Invalid remote: origin
```
and then a long list of IOexceptions like

```
java.io.IOException: Could not resolve revision for package 'NPM:@tsconfig:node14:1.0.1' with VcsInfo(type=Git, url=https://github.com/tsconfig/bases.git, revision=, path=bases):
	Could not find any revision candidates for package 'NPM:@tsconfig:node14:1.0.1' with VcsInfo(type=Git, url=https://github.com/tsconfig/bases.git, revision=, path=bases).
```
...
```
java.io.IOException: Could not resolve revision for package 'NPM:@types:body-parser:1.19.1' with VcsInfo(type=Git, url=https://github.com/DefinitelyTyped/DefinitelyTyped.git, revision=, path=types/body-parser):
	Could not find any revision candidates for package 'NPM:@types:body-parser:1.19.1' with VcsInfo(type=Git, url=https://github.com/DefinitelyTyped/DefinitelyTyped.git, revision=, path=types/body-parser).
```

Here a full trace

```
java.io.IOException: Could not resolve revision for package 'NPM:@babel:plugin-syntax-nullish-coalescing-operator:7.8.3' with VcsInfo(type=Git, url=https://github.com/babel/babel.git, revision=master, path=packages/babel-plugin-syntax-nullish-coalescing-operator):
	Discarding revision 'master' because the requested VCS path 'packages/babel-plugin-syntax-nullish-coalescing-operator' does not exist.
	Discarding revision 'v7.8.3' because the requested VCS path 'packages/babel-plugin-syntax-nullish-coalescing-operator' does not exist.
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:270)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver$resolveVcs$6.invoke(PackageProvenanceResolver.kt:207)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache.use(WorkingTreeCache.kt:65)
	at org.ossreviewtoolkit.scanner.utils.DefaultWorkingTreeCache$use$1.invokeSuspend(WorkingTreeCache.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver.resolveProvenance(PackageProvenanceResolver.kt:85)
	at org.ossreviewtoolkit.scanner.Scanner$resolvePackageProvenances$duration$1$1$1$1.invokeSuspend(Scanner.kt:175)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I haven't found any curation for plugin-syntax-nullish-coalescing-operator, and I don't think the teams have changed the build system, so I suspect it is some change in how the default source is identified.

**Comment by fviernau** [comment]
I've investigated the babel one and came up with this bug report: https://github.com/oss-review-toolkit/ort/issues/6028

**Comment by sschuberth** [comment]
@bennati, is this still reproducible and worth tracing separately from @fviernau's #6028, or can we close this?

**Comment by sschuberth** [comment]
> but actually ,the repo paths as [...] exists

Note that the error messages says it's about the *revision*, not the *path*. So ORT simply does not know which revision to checkout for scanning, as no revision could be determined that matches the package version. To solve this, probably [package curations](https://oss-review-toolkit.org/ort/docs/configuration/package-curations) are required.

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
