### ISSUE TITLE
Nullpointer exception on ort scan

### ISSUE THREAD

**Issue by dineshr93** [oss-review-toolkit/ort#6208]
Hello ,

I was following the startersdoc https://github.com/oss-review-toolkit/ort/blob/main/docs/getting-started.md

while running `ort scan`
The scan code didn't bootstrapped as mentioned in the doc.

ort version: 227a258be68b70cb8ab  (Date:   Wed Jan 26 22:57:27 2022)

<details><summary>ERROR</summary>
<p>

```js
    dinesh   ~    cd mime-types/ && ort scan -i analyzer-result.yml -o out --skip-excluded                                         in bash at 14:49:01
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 227a258be6.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'scan' under Java 11.0.17 on Linux with
\_______  /____|_  / |____|    8 CPUs and a maximum of 6392 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /home/dinesh/.ort/config
ORT_DATA_DIR = /home/dinesh/.ort
HOSTTYPE = x86_64
SHELL = /opt/distrod/alias/bin/bash
TERM = xterm-256color

Looking for ORT configuration in the following file:
        /home/dinesh/.ort/config/config.yml

Scanning projects with:
Exception in thread "main" java.io.IOException: Cannot run program "scancode": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:80)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.run(CommandLinePathScannerWrapper.kt:32)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:86)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getVersion(CommandLinePathScannerWrapper.kt:32)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode.getVersion(ScanCode.kt:179)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:85)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$details$2.invoke(CommandLinePathScannerWrapper.kt:40)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$details$2.invoke(CommandLinePathScannerWrapper.kt:40)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getDetails(CommandLinePathScannerWrapper.kt:40)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:194)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:194)
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3499)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3516)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3515)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:194)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:158)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
```

</p>
</details>

So I installed scancode https://github.com/nexB/scancode-toolkit/releases/tag/v31.2.1

did `export PATH=/sw/scancode-toolkit-v31.2.1:$PATH`

and ran `ort scan -i analyzer-result.yml -o out --skip-excluded`

I got <details><summary>Error</summary>
<p>

```js
    dinesh   mime-types detached at 2.1.18 > ort scan -i analyzer-result.yml -o out --skip-excluded
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 227a258be6.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'scan' under Java 11.0.17 on Linux with
\_______  /____|_  / |____|    8 CPUs and a maximum of 6392 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /home/dinesh/.ort/config
ORT_DATA_DIR = /home/dinesh/.ort
HOSTTYPE = x86_64
SHELL = /opt/distrod/alias/bin/bash
TERM = xterm-256color

Looking for ORT configuration in the following file:
        /home/dinesh/.ort/config/config.yml

Scanning projects with:
        ScanCode (version 31.2.1)
Scanning packages with:
        ScanCode (version 31.2.1)
Exception in thread "main" java.lang.NullPointerException
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeResultParserKt$getCopyrightFindings$1$1.invoke(ScanCodeResultParser.kt:260)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeResultParserKt$getCopyrightFindings$1$1.invoke(ScanCodeResultParser.kt:258)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:131)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeResultParserKt.getCopyrightFindings(ScanCodeResultParser.kt:383)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeResultParserKt.generateSummary(ScanCodeResultParser.kt:114)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCodeResultParserKt.generateSummary(ScanCodeResultParser.kt:83)
        at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode.scanPath(ScanCode.kt:144)
        at org.ossreviewtoolkit.scanner.Scanner.scanPath(Scanner.kt:525)
        at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:376)
        at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:155)
        at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:231)
        at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:158)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:82)
```

</p>
</details>

is the scancode verion incompatible ?

**Comment by sschuberth** [comment]
> The scan code didn't bootstrapped as mentioned in the doc.

Thanks for the note, fixed in https://github.com/oss-review-toolkit/ort/pull/6210.

**Comment by sschuberth** [comment]
> is the scancode verion incompatible ?

It shouldn't be, see https://github.com/oss-review-toolkit/ort/issues/5495, but let me double-check.

**Comment by sschuberth** [comment]
> It shouldn't be, see #5495, but let me double-check.

Indeed there was an issue, see https://github.com/oss-review-toolkit/ort/pull/6211.
