### ISSUE TITLE
shadowJar: Analyzing ORT with ORT fails

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6318]
Reproduce e.g.:
```
./gradlew cli:shadowJar
java -cp cli/build/libs/cli-40deb7a7d5-dirty-all.jar org.ossreviewtoolkit.cli.OrtMainKt analyze -i . -o . -m Maven,Gradle
```

Outcome:

Exception in thread "main" org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.eclipse.aether.RepositorySystem
  roleHint: default
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport.createRepositorySystemSession(MavenSupport.kt:873)
	at org.ossreviewtoolkit.analyzer.managers.utils.MavenSupport.<init>(MavenSupport.kt:321)
	at org.ossreviewtoolkit.analyzer.managers.Gradle.<init>(Gradle.kt:136)
	at org.ossreviewtoolkit.analyzer.managers.Gradle.<init>(Gradle.kt:74)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$Factory.create(Gradle.kt:93)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$Factory.create(Gradle.kt:83)
	at org.ossreviewtoolkit.analyzer.Analyzer.findManagedFiles(Analyzer.kt:91)
	at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:259)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.inject.LocatedBeans$Itr.next(LocatedBeans.java:141)
	at org.eclipse.sisu.inject.LocatedBeans$Itr.next(LocatedBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 17 more

**Comment by mnonnenmacher** [comment]
Could it be that `analyzer/src/main/resources/META-INF/plexus/components.xml` is not built into the shadow JAR?

**Comment by sschuberth** [comment]
Yes, and that's maybe because CLI subcommands are `ServiceLoader`-based plugins now, which might confuse the Shadow-plugin when determining dependencies.

**Comment by mnonnenmacher** [comment]
> Could it be that `analyzer/src/main/resources/META-INF/plexus/components.xml` is not built into the shadow JAR?

Probably that's not the root cause because the file only defines additional packagings. So it seems that for some reason Plexus is not correctly initialized, I suspect that's somehow related to how the shadow JAR is built, e.g. the `ServiceLoader`s @sschuberth mentioned.

**Comment by fviernau** [comment]
Maybe merging the manifest properly helps, as described here https://github.com/johnrengelman/shadow/issues/369.

**Comment by fviernau** [comment]
The dist archive does not exhibit this bug and can be used instead of the shadow jar.
As per discussion with @mnonnenmacher @sschuberth @tsteenbe it would make sense to

1. publish the dist archive at GitHub registry
2. Drop the shadow jar as it does not work currently.
