### ISSUE TITLE
Error generating reports

### ISSUE THREAD

**Issue by mlorenzoitx** [oss-review-toolkit/ort#6321]
This issue should be similar to #6316 

when I try to generate reports.
ort report -f NoticeTemplate,StaticHtml,WebApp -i reports/jersey/evaluation-result.yml --output-dir reports/jersey/

I get an error again
FreeMarker template error:
An error has occurred when reading existing sub-variable "licenseFiles"; see cause exception! The type of the containing value was: extended_hash+string (org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor$PackageModel wrapped into f.e.b.StringModel)

Java stack trace (for programmers):
----
freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:185)
	at freemarker.core.Dot._eval(Dot.java:43)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor.processTemplatesInternal(FreemarkerTemplateProcessor.kt:168)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor.processTemplates(FreemarkerTemplateProcessor.kt:97)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.NoticeTemplateReporter.generateReport(NoticeTemplateReporter.kt:65)
	at org.ossreviewtoolkit.cli.commands.ReporterCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReporterCommand.kt:279)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
	... 27 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLocations(LicenseInfoResolver.kt:218)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.createLicenseInfo(LicenseInfoResolver.kt:129)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLicenseInfo(LicenseInfoResolver.kt:61)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.createLicenseFileInfo(LicenseInfoResolver.kt:252)
	at org.ossreviewtoolkit.model.licenses.LicenseInfoResolver.resolveLicenseFiles(LicenseInfoResolver.kt:68)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor$PackageModel$licenseFiles$2.invoke(FreemarkerTemplateProcessor.kt:235)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor$PackageModel$licenseFiles$2.invoke(FreemarkerTemplateProcessor.kt:235)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor$PackageModel.getLicenseFiles(FreemarkerTemplateProcessor.kt:235)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1552)
	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:233)
	at freemarker.ext.beans.BeanModel.get(BeanModel.java:152)
	at freemarker.core.Dot._eval(Dot.java:43)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.Dot._eval(Dot.java:41)
	at freemarker.core.Expression.eval(Expression.java:101)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:99)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:383)
	at freemarker.core.IteratorBlock$IterationContext.executedNestedContentForCollOrSeqListing(IteratorBlock.java:291)
	at freemarker.core.IteratorBlock$IterationContext.executeNestedContent(IteratorBlock.java:271)
	at freemarker.core.IteratorBlock$IterationContext.accept(IteratorBlock.java:244)
	at freemarker.core.Environment.visitIteratorBlock(Environment.java:657)
	at freemarker.core.IteratorBlock.acceptWithResult(IteratorBlock.java:108)
	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:94)
	at freemarker.core.Environment.visit(Environment.java:347)
	at freemarker.core.Environment.visit(Environment.java:353)
	at freemarker.core.Environment.process(Environment.java:326)
	at freemarker.template.Template.process(Template.java:383)
14:45:32.752 [main] ERROR org.ossreviewtoolkit.cli.commands.ReporterCommand - Could not create 'NoticeTemplate' report in 8m 31.547105699s: _TemplateModelException: An error has occurred when reading existing sub-variable "licenseFiles"; see cause exception! The type of the containing value was: extended_hash+string (org.ossreviewtoolkit.reporter.reporters.freemarker.FreemarkerTemplateProcessor$PackageModel wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #list package.licenseFiles.files as l...  [in template "default.ftl" at line 75, column 5]
----
Caused by: InvocationTargetException: null
    Caused by: OutOfMemoryError: Java heap space
14:45:32.754 [main] ERROR org.ossreviewtoolkit.cli.commands.ReporterCommand - Could not create 'StaticHtml' report in 4m 39.504073028s: OutOfMemoryError: Java heap space
14:45:32.754 [main] ERROR org.ossreviewtoolkit.cli.commands.ReporterCommand - Could not create 'WebApp' report in 8m 31.533516360s: OutOfMemoryError: Java heap space
Created 0 of 3 report(s) in 8m 31.577105577s.

**Comment by mlorenzoitx** [comment]
Solved adding more memory in JVM_OPTS

edit file ..../cli/build/install/ort/bin/ort

and add this option

DEFAULT_JVM_OPTS="-Xmx8g"
