### ISSUE TITLE
Cannot run program "scancode" - wrong Scancode configuration/ version?

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6328]
I tried to run the scanner locally with recently docker image and get the following error. It seems to miss scancode.

```
Looking for ORT configuration in the following file:
	/project/ort/config.yml

Scanning projects with:
Exception in thread "main" java.io.IOException: Cannot run program "scancode": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.run(CommandLinePathScannerWrapper.kt:32)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:88)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getVersion(CommandLinePathScannerWrapper.kt:32)
	at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode.getVersion(ScanCode.kt:181)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:87)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$details$2.invoke(CommandLinePathScannerWrapper.kt:40)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$details$2.invoke(CommandLinePathScannerWrapper.kt:40)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getDetails(CommandLinePathScannerWrapper.kt:40)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:195)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:195)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:195)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:159)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 30 more
```
In the `config.yml` I use this configuration for Scancode:
```
options:
      ScanCode:
        commandLine: '--copyright --license --info --strip-root --timeout 300'
        parseLicenseExpressions: true
        # Criteria for matching stored scan results. These can be configured for any scanner that uses semantic
        # versioning. Note that the 'maxVersion' is exclusive and not part of the range of accepted versions.
        minVersion: '3.2.1-rc2'
        maxVersion: '32.0.0'
```

What is the problem behind this error stack trace? 
Is it the wrong version of Scancode? How could I find it out? Do I also have to include a docker image of Scancode locally or in gitlab?

Thank you very much for your help.

**Comment by mnonnenmacher** [comment]
We had the same issue on some machines and in our case it was an issue with the Docker cache. Running the docker build with the `--no-cache` option fixed it for us.

**Comment by schvvarzekatze** [comment]
Thank you for this solution for my error.

**Comment by sschuberth** [comment]
> I have installed Scancode via GIT

This probably means that your `scancode` executable is not in your `PATH` environment. But that needs to be the case for ORT to find it on your system. So, please ensure your `PATH` is set correctly.

**Comment by ibelz** [comment]
Arrrgh.... I had a typo in my PATH. 

Scan is running... Thanks
