### ISSUE TITLE
Unknown file format for file extension '' on analyzer step

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6336]
The analyzer step fails without setting explicitely a curation which should only be relevant for in the evaluation step.

**Reproduction:** Sample gradle project with only one dependency e.g. 

`dependencies.add("runtimeOnly", "com.codepoetics:protonpack:1.16")`

This results in the following stack trace:

```
17:17:22.088 [main] INFO  org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - EnvironmentVariableFilter initialized with denySubstrings = [key, pass, pwd, token, user] and allowNames = [CARGO_HTTP_USER_AGENT, COMPOSER_ALLOW_SUPERUSER, CONAN_LOGIN_ENCRYPTION_KEY, CONAN_LOGIN_USERNAME, CONAN_PASSWORD, CONAN_USERNAME, CONAN_USER_HOME, CONAN_USER_HOME_SHORT, DOTNET_CLI_CONTEXT_ANSI_PASS_THRU, GIT_ASKPASS, GIT_HTTP_USER_AGENT, GRADLE_USER_HOME, HACKAGE_USERNAME, HACKAGE_PASSWORD, HACKAGE_KEY, PWD, USER, USERPROFILE].
 ______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version DOCKER-SNAPSHOT.
|    |   | |       _/ |    |
|    |   | |    |   \ |    |    Running 'analyze' as 'ort' under Java 17.0.5 on Linux
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 7948 MiB of memory.

Environment variables:
ORT_CONFIG_DIR = /home/ort/.ort/config
ORT_DATA_DIR = /home/ort/.ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk

Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml (does not exist)

--package-managers is deprecated, use -P ort.analyzer.enabledPackageManagers=... on the ort command instead.
Looking for analyzer-specific configuration in the following files and directories:
        /project/.ort.yml (does not exist)
        /home/ort/.ort/config/resolutions.yml (does not exist)
The following package managers are enabled:
        Gradle
Analyzing project path:
        /project
Exception in thread "main" java.io.IOException: Failed parsing package curation from '/home/ort/.ort/config/curations'.
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProvider$Companion.readCurationFiles(FilePackageCurationProvider.kt:89)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProvider.<init>(FilePackageCurationProvider.kt:74)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProvider.<init>(FilePackageCurationProvider.kt:75)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProviderFactory.create(FilePackageCurationProvider.kt:48)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProviderFactory.create(FilePackageCurationProvider.kt:44)
        at org.ossreviewtoolkit.analyzer.PackageCurationProviderFactory$DefaultImpls.create(PackageCurationProvider.kt:41)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProviderFactory.create(FilePackageCurationProvider.kt:44)
        at org.ossreviewtoolkit.analyzer.PackageCurationProviderFactory$Companion.create(PackageCurationProvider.kt:38)
        at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:194)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Caused by: java.lang.IllegalArgumentException: Unknown file format for file extension ''.
        at org.ossreviewtoolkit.model.FileFormat$Companion.forExtension(FileFormat.kt:59)
        at org.ossreviewtoolkit.model.FileFormat$Companion.forFile(FileFormat.kt:67)
        at org.ossreviewtoolkit.model.FileFormatKt.mapper(FileFormat.kt:89)
        at org.ossreviewtoolkit.analyzer.curation.FilePackageCurationProvider$Companion.readCurationFiles(FilePackageCurationProvider.kt:124)
        ... 16 more

```

Do you have an idea where this broken curation file comes from and how this error can be fixed?

**Comment by sschuberth** [comment]
> Do you have an idea where this broken curation file comes

This is not due to a broken curation file, but due to a regression that was temporarily introduced. https://github.com/oss-review-toolkit/ort/pull/6326 contains a fix, but another one follows with https://github.com/oss-review-toolkit/ort/pull/6331.
