### ISSUE TITLE
Clearlydefined curation freeze

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#6358]
Hi,

I've got some issue with ClearlyDefined curation.
I've this configuration in my "ort.yml" :
```
  packageCurationProviders:
    - name: DefaultFile
    - name: DefaultDir
    - name: File
      config:
        path: '/project/curations.yml'
        mustExist: true
    - name: File
      config:
        path: '/project/ort-config/curations-dir'
        mustExist: false
    - name: OrtConfig
      enabled: true
    - name: ClearlyDefined
      config:
        serverUrl: 'https://api.clearlydefined.io'
        minTotalLicenseScore: 80
```
Some times (not at each audit), the analyzis phase is blocked and I get this error in the log :
```
18:18:45  17:18:44.413 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Finished NPM analysis.
18:18:58  17:18:56.051 [OkHttp https://api.clearlydefined.io/...] ERROR org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - HTTP request to 'https://api.clearlydefined.io/definitions' failed with an exception: StreamResetException: stream was reset: CANCEL
18:18:58  17:18:56.051 [OkHttp https://api.clearlydefined.io/...] ERROR org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - HTTP request to 'https://api.clearlydefined.io/definitions' failed with an exception: StreamResetException: stream was reset: CANCEL
18:18:58  17:18:56.051 [OkHttp https://api.clearlydefined.io/...] ERROR org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - HTTP request to 'https://api.clearlydefined.io/definitions' failed with an exception: StreamResetException: stream was reset: CANCEL
18:18:58  17:18:56.051 [OkHttp https://api.clearlydefined.io/...] ERROR org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - HTTP request to 'https://api.clearlydefined.io/definitions' failed with an exception: StreamResetException: stream was reset: CANCEL
18:18:58  Exception in thread "DefaultDispatcher-worker-9" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 9859456: Expected start of the object '{', but had ':' instead at path: $['npm/npmjs/-/eslint-plugin-tsdoc/0.2.2'].files[11].facets
18:18:58  JSON input: .....58654d8b0467d1998c6"},"facets":["tests"]},{"path":"package/l.....
18:18:58  	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
18:18:58  	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
18:18:58  	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:530)
18:18:58  	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:528)
18:18:58  	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:224)
18:18:58  	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:207)
18:18:58  	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
18:18:58  	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:97)
18:18:58  	at org.ossreviewtoolkit.clients.clearlydefined.Facets$$serializer.deserialize(Definition.kt:154)
18:18:58  	at org.ossreviewtoolkit.clients.clearlydefined.Facets$$serializer.deserialize(Definition.kt:154)
```
I think it's may be an format issue in the json from clearlydefined, but it will be great if ORT could not fail/freeze in this case and just write some logs and go on the process.

**Comment by sschuberth** [comment]
Which revision of ORT are you using? I believe this should have already been fixed in https://github.com/oss-review-toolkit/ort/pull/6337/commits/be1675f35a44d0fc8157a268a7f716501e2871c1 as part of https://github.com/oss-review-toolkit/ort/pull/6337.

**Comment by sschuberth** [comment]
> I believe this should have already been fixed in [be1675f](https://github.com/oss-review-toolkit/ort/commit/be1675f35a44d0fc8157a268a7f716501e2871c1) as part of #6337.

Ah, no, it's not. I'll have a look.

**Comment by sschuberth** [comment]
Thanks for reporting this @fb33. While investigating, I uncovered another bug that might have cause many (NPM) curations to be missed in the past :worried:

**Comment by fb33** [comment]
Hi, I'm using an ORT image build on the 16 january around 11h45 am.
Thanks for your reactivity ! :+1:
