### ISSUE TITLE
OkHttp & ClearlyDefined: Exceptions block the whole process

### ISSUE THREAD

**Issue by fb33** [oss-review-toolkit/ort#6367]
Hi,

I build a ORT docker image yesterday evening that contains https://github.com/oss-review-toolkit/ort/commit/c298c8aeea7505a9d1317c681cc9652657ba3d76.
It works well, but I got an other issue around clearlydefined usage.

When something get wrong during the request to clearlydefined, it freezes the whole process of the analyzer and my pipeline never finishes.

Here is the exception : 
```
12:00:14  11:00:13.948 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Finished NPM analysis.
12:00:21  11:00:20.312 [DefaultDispatcher-worker-12] INFO  org.ossreviewtoolkit.downloader.vcs.Git - Trying to fetch only revision 'main' with depth limited to 50.
12:00:25  11:00:24.988 [DefaultDispatcher-worker-12] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'git checkout main' in '/home/ort/.ort/ort-config'...
12:00:25  11:00:25.023 [DefaultDispatcher-worker-12] INFO  org.ossreviewtoolkit.analyzer.curation.OrtConfigPackageCurationProvider - Successfully cloned main from https://github.com/oss-review-toolkit/ort-config.git.
12:01:04  11:00:59.843 [OkHttp https://api.clearlydefined.io/...] ERROR org.ossreviewtoolkit.utils.ort.OkHttpClientHelper - HTTP request to 'https://api.clearlydefined.io/definitions' failed with an exception: SocketTimeoutException: timeout
12:01:04  Exception in thread "DefaultDispatcher-worker-12" java.net.SocketTimeoutException: timeout
12:01:04  	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
12:01:04  	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
12:01:04  	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
12:01:04  	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
12:01:04  	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
12:01:04  	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at org.ossreviewtoolkit.utils.ort.OkHttpClientHelper$defaultClient$2$invoke$$inlined$-addNetworkInterceptor$1.intercept(OkHttpClient.kt:1086)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
12:01:04  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
12:01:04  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
12:01:04  	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
12:01:04  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
12:01:04  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
12:01:04  	at java.base/java.lang.Thread.run(Thread.java:833)
12:01:04  	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@464dde64, Dispatchers.Default]
```
Can we find a way to make this exception non-blocking ?

**Comment by sschuberth** [comment]
I anyway have more CD-related improvements in the pipeline, so I'll have a look at this.

**Comment by fb33** [comment]
It's not relative to the pipeline, I wrote my own pipeline that run ORT image.
I think the analyze process never end if there is an exception when clearlydefined is called.
I don't go deeper in the code but it may be relative to the exception management of OkHttp

**Comment by sschuberth** [comment]
By "in the pipeline" I meant "in the works"... 😉

**Comment by sschuberth** [comment]
Note that we already have such a test for ClearlyDefined as a curation provider:

https://github.com/oss-review-toolkit/ort/blob/dfde047dc1dbc6fa159bd5d2d21a56887a1cbf54/analyzer/src/test/kotlin/curation/ClearlyDefinedPackageCurationProviderTest.kt#L61-L77

What's missing is an according test for ClearlyDefined as a scan storage.
