### ISSUE TITLE
npm Scan failes due to FileNotFoundException after longer freeze

### ISSUE THREAD

**Issue by schvvarzekatze** [oss-review-toolkit/ort#6371]
The scan of npm libraries in our gitt repository still fails after freezing for approximately 2 hours. The project should contain approximately 2000 external libraries, so it would not be suprising that an initial scan takes longer time. The scanned project is versioned on gitlab. The access to the project now seems to be succesful.

The scan seems to fail because the directory `/tmp/ort-ScanCode10701555441499944313/result.json` cannot be found. Why is the scanner needing it at all?

The scanner logs, the `config.yml` and the `package.json` structure ist provided below.

I hope this helps you to find an answer to my question or have an idea what could cause the scan fail in the logs below. Thank you very much.

**Scanner logs:**
```
INFO: Scan analyzer results with OSS review toolkit
18:53:57,384 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.5
18:53:57,400 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
18:53:57,402 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/opt/ort/lib/cli-DOCKER-SNAPSHOT.jar!/logback.xml]
18:53:57,403 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@cc239ba - Resource [logback.xml] occurs multiple times on the classpath.
18:53:57,403 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@cc239ba - Resource [logback.xml] occurs at [jar:file:/opt/ort/lib/helper-cli-DOCKER-SNAPSHOT.jar!/logback.xml]
18:53:57,403 |-WARN in ch.qos.logback.classic.util.DefaultJoranConfigurator@cc239ba - Resource [logback.xml] occurs at [jar:file:/opt/ort/lib/cli-DOCKER-SNAPSHOT.jar!/logback.xml]
18:53:57,407 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7d37f1c - URL [jar:file:/opt/ort/lib/cli-DOCKER-SNAPSHOT.jar!/logback.xml] is not of type file
18:53:57,475 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [STDOUT]
18:53:57,475 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
18:53:57,480 |-INFO in ch.qos.logback.core.model.processor.ImplicitModelHandler - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
18:53:57,496 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to WARN
18:53:57,497 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [STDOUT] to Logger[ROOT]
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.http.headers] to ERROR
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.http.wire] to ERROR
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.eclipse.jgit.internal.storage.file.FileSnapshot] to ERROR
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.analyzer.managers.Yarn2] to INFO
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.clients.fossid.FossIdRestService] to INFO
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.reporter.reporters.fossid.FossIdReporter] to INFO
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.scanner.scanners.fossid.FossId] to INFO
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.scanner.scanners.fossid.FossIdConfig] to INFO
18:53:57,498 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.ossreviewtoolkit.scanner.scanners.fossid.FossIdUrlProvider] to INFO
18:53:57,498 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@69d6a7cd - End of configuration.
18:53:57,498 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3162743f - Registering current configuration as safe fallback point
18:53:57.645 [main] INFO  org.ossreviewtoolkit.model.config.OrtConfiguration - Using ORT configuration file '/project/ort/config.yml'.
18:53:58.011 [main] INFO  org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - EnvironmentVariableFilter initialized with denySubstrings = [PASS, SECRET, USER] and allowNames = [PASSPORT, USER_HOME].
 ______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version DOCKER-SNAPSHOT.
|    |   | |       _/ |    |
|    |   | |    |   \ |    |    Running 'scan' as 'root' under Java 17.0.5 on Linux
\________/ |____|___/ |____|    with 8 CPUs and a maximum of 6556 MiB of memory.
Environment variables:
ORT_CONFIG_DIR = /project/ort
ORT_DATA_DIR = /root/.ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk
Looking for ORT configuration in the following file:
	/project/ort/config.yml
Scanning projects with:
18:53:58.052 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'scancode --version' in '/home/ort'...
	ScanCode (version 31.2.1)
Scanning packages with:
18:53:59.109 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'scancode --version' in '/home/ort'...
	ScanCode (version 31.2.1)
18:54:01.644 [main] INFO  org.ossreviewtoolkit.cli.commands.ScannerCommand - Read ORT result from 'analyzer-result.yml' (2.90 MiB) in 1.443068539s.
18:54:01.679 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scanning 1 project(s) with 1 scanner(s).
18:54:01.680 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Resolving provenance for 1 package(s).
18:54:01.705 [DefaultDispatcher-worker-3] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
18:54:01.806 [DefaultDispatcher-worker-3] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@462820c4
18:54:01.807 [DefaultDispatcher-worker-3] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
18:54:01.915 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver - Could not find a stored repository resolution result for package 'Yarn::package.json:', attempting resolution.
18:54:02.030 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
18:54:02.042 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
18:54:02.197 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for package 'package.json' and version '' found: IOException: Cannot guess a revision name from a blank version.
18:54:02.281 [DefaultDispatcher-worker-3] INFO  org.apache.sshd.common.util.security.eddsa.EdDSASecurityProviderRegistrar - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
18:54:02.387 [DefaultDispatcher-worker-3] INFO  org.apache.sshd.common.io.DefaultIoServiceFactoryFactory - No detected/configured IoServiceFactoryFactory; using Nio2ServiceFactoryFactory
18:54:02.875 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Adding Git fixed revision '9fc392bfc65cce4835428582128e35e8f1428b01' (taken from package metadata) as a candidate.
18:54:02.880 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver - Trying revision candidate '9fc392bfc65cce4835428582128e35e8f1428b01' (1 of 1).
18:54:02.893 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.downloader.vcs.Git - Trying to fetch only revision '9fc392bfc65cce4835428582128e35e8f1428b01' with depth limited to 50.
18:54:18.484 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'git checkout 9fc392bfc65cce4835428582128e35e8f1428b01' in '/tmp/ort-DefaultWorkingTreeCache17311795167687034441'...
18:54:22.608 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.scanner.provenance.DefaultPackageProvenanceResolver - Resolved revision for package 'Yarn::package.json:' to 9fc392bfc65cce4835428582128e35e8f1428b01 based on guessed revision 9fc392bfc65cce4835428582128e35e8f1428b01.
18:54:22.907 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Resolved provenance for 1 package(s) in 21.224008852s.
18:54:22.908 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Resolving nested provenances for 1 package(s).
18:54:22.928 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.scanner.provenance.DefaultNestedProvenanceResolver - Could not find a stored nested provenance for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@git.intra.xyz.com/xyz/project.git, revision=9fc392bfc65cce4835428582128e35e8f1428b01, path=), resolvedRevision=9fc392bfc65cce4835428582128e35e8f1428b01), attempting resolution.
18:54:22.930 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.downloader.vcs.Git - Trying to fetch only revision '9fc392bfc65cce4835428582128e35e8f1428b01' with depth limited to 50.
18:54:23.482 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'git checkout 9fc392bfc65cce4835428582128e35e8f1428b01' in '/tmp/ort-DefaultWorkingTreeCache17311795167687034441'...
18:54:24.470 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Resolved nested provenance for 1 package(s) in 1.561110092s.
18:54:24.472 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Reading stored scan results for 1 package(s) with 1 provenance(s).
18:54:24.520 [main] INFO  org.ossreviewtoolkit.scanner.ScanResultsStorage - Read 0 scan result(s) for 'Yarn::package.json:' from PostgresStorage in 28.877709ms.
18:54:24.522 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Read the following stored scan result(s) in 48.579658ms:
18:54:24.523 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - 	ScanCode: Result(s) for 0 of 1 provenance(s).
18:54:24.524 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scanning RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@git.intra.xyz.com/xyz/project.git, revision=9fc392bfc65cce4835428582128e35e8f1428b01, path=), resolvedRevision=9fc392bfc65cce4835428582128e35e8f1428b01) (1 of 1)...
18:54:24.525 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scanning RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@git.intra.xyz.com/xyz/project.git, revision=9fc392bfc65cce4835428582128e35e8f1428b01, path=), resolvedRevision=9fc392bfc65cce4835428582128e35e8f1428b01) (1 of 1)...
18:54:24.527 [main] INFO  org.ossreviewtoolkit.downloader.vcs.Git - Trying to fetch only revision '9fc392bfc65cce4835428582128e35e8f1428b01' with depth limited to 50.
18:54:24.998 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'git checkout 9fc392bfc65cce4835428582128e35e8f1428b01' in '/tmp/ort-DefaultWorkingTreeCache17311795167687034441'...
18:54:28.824 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@git.intra.xyz.com/xyz/project.git, revision=9fc392bfc65cce4835428582128e35e8f1428b01, path=), resolvedRevision=9fc392bfc65cce4835428582128e35e8f1428b01) with path scanner 'ScanCode' started.
18:54:28.827 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'scancode --copyright --license --info --strip-root --timeout 300 --processes 7 /tmp/ort-DefaultProvenanceDownloader1622431408250150910 --json-pp /tmp/ort-ScanCode10701555441499944313/result.json' in '/home/ort'...
Exception in thread "main" java.io.FileNotFoundException: /tmp/ort-ScanCode10701555441499944313/result.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.fasterxml.jackson.core.TokenStreamFactory._fileInputStream(TokenStreamFactory.java:262)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1030)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3157)
	at org.ossreviewtoolkit.model.FileFormatKt.readTree(FileFormat.kt:94)
	at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode.scanPath(ScanCode.kt:141)
	at org.ossreviewtoolkit.scanner.Scanner.scanPath(Scanner.kt:525)
	at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:376)
	at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:155)
	at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:232)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:159)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Uploading artifacts for failed job
00:01
Uploading artifacts...
build/oss-review-toolkit/*: found 4 matching files and directories 
Uploading artifacts as "archive" to coordinator... 201 Created  id=748963 responseStatus=201 Created token=he9xe3K7
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**`config.yml`:**
```
ort:
  allowedProcessEnvironmentVariableNames:
    - PASSPORT
    - USER_HOME
  deniedProcessEnvironmentVariablesSubstrings:
    - PASS
    - SECRET
    - USER
  enableRepositoryPackageCurations: true 
  enableRepositoryPackageConfigurations: true

  licenseFilePatterns:
    licenseFilenames: [ 'license*' ]
    patentFilenames: [ patents ]
    rootLicenseFilenames: [ 'readme*' ]

  severeIssueThreshold: ERROR
  severeRuleViolationThreshold: ERROR

  analyzer:
    allowDynamicVersions: true
    enabledPackageManagers: [ Gradle, Yarn,]
    packageManagers:
      Yarn:
        options:
          directDependenciesOnly: true
      Gradle:
        options:
          directDependenciesOnly: true

  downloader:
    allowMovingRevisions: true
    # Only used if the '--license-classifications-file' option is specified.
    includedLicenseCategories:
      - copyleft
      - copyleft-provide-sourcecode
      - weak-copyleft
      - weak-copyleft-provide-sourcecode
      - proprietary
      - permissive
      - public-domain
      - no-assertion
      - not-for-commercial-use
      - include-in-notice-file
      - include-source-code-offer-in-notice-file

  scanner:
    skipConcluded: true

    archive:
      enabled: true

      postgresStorage:
        connection:
          url: ${POSTGRES_URL}
          schema: public
          username: ort
          password: ${POSTGRES_PASSWORD}
          sslmode: disable

    createMissingArchives: true

    options:
      ScanCode:
        commandLine: '--copyright --license --info --strip-root --timeout 300'
        parseLicenseExpressions: true

    storages:
      postgres:
        connection:
          url: ${POSTGRES_URL}
          schema: public
          username: ort
          password: ${POSTGRES_PASSWORD}
          sslmode: disable
        type: PACKAGE_BASED

    storageReaders: [ postgres ]
    storageWriters: [ postgres ]

    ignorePatterns: [ '**/META-INF/DEPENDENCIES' ]

    provenanceStorage:

      postgresStorage:
        connection:
          url: ${POSTGRES_URL}
          schema: public
          username: ort
          password: ${POSTGRES_PASSWORD}
          sslmode: disable
```

**`package.json`**
```
{
  "private": true,
  "name": "project-monorepo",
  "version": "1.0.0",
  "repository": {
    "type": "git",
    "url": "git@git.intra.xyz.com:xyz/project.git"
  },
  "author": "XYZ",
  "license": "UNLICENSED",
  "devDependencies": {},
  "dependencies": {
    "codemirror": "^5.63.0",
    "mkdirp": "^0.5.1"
  },
  "workspaces": {
    "packages": [
        ...
    ],
    "nohoist": [
      "**/font-sassy/**"
    ]
  },
  "resolutions": {
    "jquery": "^3.6.0",
    "node-fetch": "^2.6.7",
    "lodash": "^4.17.21",
    "minimist": "^1.2.6"
  }
}
```

**Comment by sschuberth** [comment]
> The scan seems to fail because the directory `/tmp/ort-ScanCode10701555441499944313/result.json` cannot be found. Why is the scanner needing it at all?

That's the raw result file from ScanCode that the ORT scanner wrapper parses.

**Comment by schvvarzekatze** [comment]
This error seems to be solved with with 32 CPUs and a maximum of 32768 MiB of memory instead of 8 CPUs and a maximum of 6556 MiB of memory.

I only have to check why the reports are still empty unlike in the gradle run. But this would be a different issue.

**Comment by schvvarzekatze** [comment]
It also worked with 8 CPUs and a maximum of 13112 MiB (`--env "JAVA_OPTS=-XX:MaxRAMPercentage=${ORT_MAX_RAM_PERCENTAGE:-80.0}"` of memory in the last run.
