### ISSUE TITLE
Reference file is wrong on option analyzer/skipExcluded

### ISSUE THREAD

**Issue by borisbaldassari** [oss-review-toolkit/ort#6494]
Reference configuration file at https://github.com/oss-review-toolkit/ort/blob/7315bb3c065555fc0429055d41e57451eb1de134/model/src/main/resources/reference.yml
states that we can use `skipExcluded: true` in `config.yml`, but when trying it we get the following error:

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "skip_excluded
" (class org.ossreviewtoolkit.model.config.AnalyzerConfiguration), not marked as ignorable (5 known properties: "sw360_configu
ration", "allow_dynamic_versions", "disabled_package_managers", "enabled_package_managers", "package_managers"])
 at [Source: (File); line: 57, column: 6] (through reference chain: org.ossreviewtoolkit.model.OrtResult["analyzer"]->org.ossr
eviewtoolkit.model.AnalyzerRun["config"]->org.ossreviewtoolkit.model.config.AnalyzerConfiguration["skip_excluded"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase
.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase
.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase
.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java
:323)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)

```

**Comment by sschuberth** [comment]
> org.ossreviewtoolkit.model.config.AnalyzerConfiguration["skip_excluded"]

This looks like you were using `skip_excluded` instead of `skipExcluded`, could this be?

Because we have actually a test in place that ensure `reference.yml` can be parsed:

https://github.com/oss-review-toolkit/ort/blob/eb34b0dd11ee08ddbb537aa3c7eb54ecb7ff5bd7/model/src/test/kotlin/JsonSchemaTest.kt#L82-L89

**Comment by borisbaldassari** [comment]
> This looks like you were using `skip_excluded` instead of `skipExcluded`, could this be?

Nope, I'm indeed using skipExcluded. Note that all options in that log use snake cake [1] whereas they should be camel case according to the [reference file](https://github.com/oss-review-toolkit/ort/blob/7315bb3c065555fc0429055d41e57451eb1de134/model/src/main/resources/reference.yml). But (and I double-checked) the config file used here really uses `skipExcluded`.

[1] `(5 known properties: "sw360_configuration", "allow_dynamic_versions", "disabled_package_managers", "enabled_package_managers", "package_managers"])`

**Comment by sschuberth** [comment]
I'm clueless as

    ./gradlew :cli:run --args="config --check-syntax ../model/src/main/resources/reference.yml"

also passes. Can it be that you're using an ORT version before  eb09951d8b28d19be52f8ea29e8998ac3278265b where `AnalyzerConfiguration.skipExcluded` was introduced about two weeks ago?

**Comment by borisbaldassari** [comment]
I pulled from ort/main around 9am CET, this morning.

**Comment by sschuberth** [comment]
And the rebuild of your Docker image also went fine this time? 😉 Please verify the version output of your running ORT.

**Comment by borisbaldassari** [comment]
```
genie.infra@ortstaging-vm1:/ort/ort$ docker run ort --version
eb34b0dd11-dirty
```

**Comment by borisbaldassari** [comment]
Oh, interestingly, the error keeps happening even after removing skipExcluded from the `config.yml` file. 

So it might well having nothing to do with the skipExcluded of the reference file - but then, where would that come from?

**Comment by borisbaldassari** [comment]
Link to a public Jenkins job where the error happens: https://foundation.eclipse.org/ci/infra/job/ort/job/Staging/job/staging_run_ort/765/console

**Comment by sschuberth** [comment]
Looking at the reference chain again:

> through reference chain: org.ossreviewtoolkit.model.OrtResult["analyzer"]

So this happens when reading an ORT result file, not when reading the ORT config file. So maybe you've created an ORT result file with a contained analyzer result (and analyzer configuration), and then you're further processing this result on another build node that has a loewr version of ORT installed, that cannot yet parse `skipExcluded` as part of the ORT result file.

**Comment by borisbaldassari** [comment]
Ouch, it's becoming tricky. I don't see how this could happen. I execute this on a single host.

The error happens on the staging host (executed from Jenkins w/ a single node, or directly on the host), and all steps of the run_ort.sh script should use the same Docker image, right? I'll rm all docker images but the latest one and retry it.

**Comment by borisbaldassari** [comment]
Oh wait, both servers (prod, old ort, and staging, new ort) use the same Postgres server/db for their storage. 

Does that mean that the Postgres DB has to be reinitialised when upgrading with this breaking change, or that we cannot mix different ort instances in the PG DB? That would explain it all..

**Comment by sschuberth** [comment]
Are you also storing analyzer results (not just scan results) in the DB?

**Comment by borisbaldassari** [comment]
I think I'm storing only scanner results (all storages are defined under ort/scanner in config.yml).

**Comment by sschuberth** [comment]
Yes, unless you're explicitly using [UploadResultToPostgresCommand](https://github.com/oss-review-toolkit/ort/blob/main/cli/src/main/kotlin/commands/UploadResultToPostgresCommand.kt), analyzer results don't end up in the DB, and the DB does *not* have to be reinitialized.

**Comment by fviernau** [comment]
Does `eb34b0dd11-dirty` mean that it's not `eb34b0dd11` but some un-commited changes on top?
If so, maybe it's worth using a non-dirty version and verify again.

**Comment by sschuberth** [comment]
Here's some more context from the log:

```
Writing analyzer result to '/output/analyzer-result.json'.
14:26:15.280 [main] INFO  org.ossreviewtoolkit.cli.commands.AnalyzerCommand - Wrote ORT result to 'analyzer-result.json' (0.30 MiB) in 449.990072ms.
The analysis took 26.618897436s.
Found 2 project(s) and 223 package(s) in total (not counting excluded ones).
Applied 0 curation(s) from 3 provider(s).
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 0 errors, 1 warning, 0 hints.

real	0m31.670s
user	0m0.063s
sys	0m0.069s
* Finish analyzer at 2023-02-16 14:26

* Updating .ort.yml file at [/ort/eclipsefdn-ort/conf/repositories/ecd.che/che/].
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "skip_excluded" (class org.ossreviewtoolkit.model.config.AnalyzerConfiguration), not marked as ignorable (5 known properties: "sw360_configuration", "allow_dynamic_versions", "disabled_package_managers", "enabled_package_managers", "package_managers"])
 at [Source: (File); line: 57, column: 6] (through reference chain: org.ossreviewtoolkit.model.OrtResult["analyzer"]->org.ossreviewtoolkit.model.AnalyzerRun["config"]->org.ossreviewtoolkit.model.config.AnalyzerConfiguration["skip_excluded"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2023)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:540)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:564)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3514)
	at org.ossreviewtoolkit.helper.utils.UtilsKt.readOrtResult(Utils.kt:367)
	at org.ossreviewtoolkit.helper.commands.repoconfig.GenerateScopeExcludesCommand.run(GenerateScopeExcludesCommand.kt:61)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.helper.HelperMainKt.main(HelperMain.kt:67)

* Start scanner at 2023-02-16 14:26
docker run -v /data/results/ecd.che/che/202302161425:/output -v /data/cache/ort/:/ort_cache/ -v /ort/eclipsefdn-ort/conf:/home/ort/.ort/config/ --rm -e JAVA_OPTS=-Xmx10g --env-file /ort/eclipsefdn-ort/run_env.txt ort --info scan -f JSON --scanners ScanCode -i /output/analyzer-result.json -o /output
```

So the `UnrecognizedPropertyException` occurs *after* writing the analyzer result but *before* running the scanner. Now the big question is: What command you running in between there, @borisbaldassari?

**Comment by borisbaldassari** [comment]
@sschuberth Well done! I had almost forgotten about this intermediate step. For infrmation, it was recommended by tsteenbe to improve the analysis scope, and I have to admit I didn't see the format change coming and forgot to update the binaries. The problem seems to have vanished, as far as I can see. I'll close this issue now.

Thanks a lot for the hint!
