### ISSUE TITLE
Reference file is wrong on option archive/postgresStorage

### ISSUE THREAD

**Issue by borisbaldassari** [oss-review-toolkit/ort#6495]
Reference configuration file at https://github.com/oss-review-toolkit/ort/blob/7315bb3c065555fc0429055d41e57451eb1de134/model/src/main/resources/reference.yml
states that we should put the `postgresStorage` storage definition under the `archive` section but then the run fails, complaining about not finding the postgresStorage definition: 

```
Exception in thread "main" java.lang.IllegalArgumentException: Failed to load ORT configuration: - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfigurationWrapper' because:

    - 'ort': - Could not instantiate 'org.ossreviewtoolkit.model.config.OrtConfiguration' because:

        - 'scanner': - Could not instantiate 'org.ossreviewtoolkit.model.config.ScannerConfiguration' because:

            - 'storages': Collection element decode failure (env):

                Could not find appropriate subclass of class org.ossreviewtoolkit.model.config.ScanStorageConfiguration: Tried org.ossreviewtoolkit.model.config.ClearlyDefinedStorageConfiguration, org.ossreviewtoolkit.model.config.FileBasedStorageConfiguration, org.ossreviewtoolkit.model.config.PostgresStorageConfiguration, org.ossreviewtoolkit.model.config.Sw360StorageConfiguration (env)
        at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion$load$1.invoke(OrtConfiguration.kt:169)
        at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion$load$1.invoke(OrtConfiguration.kt:168)
        at com.sksamuel.hoplite.fp.ValidatedKt.getOrElse(Validated.kt:115)
        at org.ossreviewtoolkit.model.config.OrtConfiguration$Companion.load(OrtConfiguration.kt:168)
        at org.ossreviewtoolkit.cli.OrtMain.run(OrtMain.kt:171)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
```

**Comment by sschuberth** [comment]
> Collection element decode failure (env):

This sounds as if you're referring to an environment variable that's not set, and thus a required property is not set, which makes the loader fail.

**Comment by mnonnenmacher** [comment]
@borisbaldassari The `archive` section is used to configure the storage for license files (which can later be used when generating notice files), it's not used to configure the storage for scan results, this is done in the `storage` section.

**Comment by borisbaldassari** [comment]
@mnonnenmacher Ah! That makes sense. I missed that step or information. 

Closing this issue, thank you for the quick replies!
