### ISSUE TITLE
Scanner: Frequent constraint violations on insertion to ProvenanceBasedPostgresStorage

### ISSUE THREAD

**Issue by fviernau** [oss-review-toolkit/ort#6581]
When running scans against random projects with latest ORT, I usually see multiple occurences
of constraint violations in the logs. I'm running ORT's `scanner` command only on one machine, and no other `scanner` command does access the database in parallel.

```
WARN  Exposed - Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.. Statement(s): INSERT INTO provenance_scan_results (artifact_hash, artifact_url, scan_summary, scanner_configuration, scanner_name, scanner_version, vcs_revision, vcs_type, vcs_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:64)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:141)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:127)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:71)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage$write$1.invoke(ProvenanceBasedPostgresStorage.kt:144)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage$write$1.invoke(ProvenanceBasedPostgresStorage.kt:143)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:241)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:240)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:190)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:160)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:146)
	at org.ossreviewtoolkit.model.utils.DatabaseUtils.transaction(DatabaseUtils.kt:120)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage.write(ProvenanceBasedPostgresStorage.kt:143)
	at org.ossreviewtoolkit.scanner.Scanner.storeProvenanceScanResult(Scanner.kt:549)
	at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:383)
	at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:155)
	at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:232)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:159)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:123)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:131)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	... 39 common frames omitted
```

**Comment by sschuberth** [comment]
For the record, I've also seen this, and has asked @mnonnenmacher about it. But back then our assumption was that this only happens if two scans for the same package start almost at the same time, and one finishes before the other.

**Comment by fviernau** [comment]
> For the record, I've also seen this, and has asked @mnonnenmacher about it. But back then our assumption was that this only happens if two scans for the same package start almost at the same time, and one finishes before the other.

Thanks @sschuberth . I'm certain there is no concurrency involved besides the one which is built-in into the `scan` command, as I observed this on my local machine with a DB running on my local machine as well, which nobody else is using.

**Comment by sschuberth** [comment]
@heliocastro also just posted this stacktrace in [Slack](https://oss-review-toolkit.slack.com/archives/C9NNJ54B1/p1746693567419129):

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://user@github.com/scipy/scipy-mathjax.git, 36f4c898f2255e0c98eb6949cd67381552d5ffea, ScanCode, 32.3.3, --copyright --license --info --strip-root --timeout 600 --license-references --json --prefer-file-license) already exists.
```

But his use-case is that he runs multiple independent `ort scan` CLI invocations in parallel.

**Comment by fviernau** [comment]
> [@heliocastro](https://github.com/heliocastro) also just posted this stacktrace in [Slack](https://oss-review-

To my understanding there is no scan failure involved at all, but this complain is only about stack traces being logged.
Otherwise the error is being ignored, execution continues and (parallel) scan(s) succeeds without any issue(s).

Note: The SQLException which leads to above logs is not a problem at all. It simply means that
           another job has meanwhile scanned the storage and written the result into the database. 
           So, the failure can / should be ignored.

So, IMO we have the options to

1. Reduce the severity of the log messages
2. Make the issue more compact
3. Investigate if we can figure out whether the `SQLException` was due to constraint violation,
    and then swallow it completely.
4. Stop logging it twice
    - https://github.com/oss-review-toolkit/ort/blob/f9cfa61b8494323e46594a67b28be6f894a8a285/scanner/src/main/kotlin/storages/ProvenanceBasedPostgresStorage.kt#L166-L172
    - https://github.com/oss-review-toolkit/ort/blob/f9cfa61b8494323e46594a67b28be6f894a8a285/scanner/src/main/kotlin/Scanner.kt#L662-L669

**Comment by fviernau** [comment]
> Options 1 is reasonable to me, option 5 looks like too dangerous unless 8 somehow is implemented but would be the best

Why is option 5, UPSERT or `insertIgnore` dangerous?

**Comment by mnonnenmacher** [comment]
@fviernau I like option 3 because it allows to log what exactly happened, so the log could say something like "not storing result because a result for the same scanner and provenance is already stored".

We have some code in the server to find out if there was a unique constraint violation:
https://github.com/eclipse-apoapsis/ort-server/blob/d7502e9407c5a230da5a451473b72cffb63a62f5/dao/src/main/kotlin/Database.kt#L199-L212
https://github.com/eclipse-apoapsis/ort-server/blob/d7502e9407c5a230da5a451473b72cffb63a62f5/dao/src/main/kotlin/Exceptions.kt#L32-L34

**Comment by fviernau** [comment]
> [@fviernau](https://github.com/fviernau) I like option 3 because it allows to log what exactly happened, so the log could say something like "not storing result because a result for the same scanner and provenance is already stored".

If option 3 could be implemented with an `insertIgnore`, would you be fine with this too?

**Comment by heliocastro** [comment]
@fviernau 5 can lead to this situation:

- First package scans fine, all data is correct and inserted in the database
- Second package, for whatever reason, borked some of the information, ams still finished, updated with the new wrong info

We will not be easily able to know if the information included there is right or wrong, and not easy way to simply pin down which of the multiples packages caused the issue.

Apart that, i agree with version 3 too. It is a solution and we need pick one, already adopted somehow in other places, then we should go with that for start.

**Comment by fviernau** [comment]
> We will not be easily able to know if the information included there is right or wrong, and not easy way to simply pin down which of the multiples packages caused the issue.
> 
> Apart that, i agree with version 3 too. It is a solution and we need pick one, already adopted somehow in other places, then we should go with that for start.

The assumption one has to make in such a setup is, that all scanners which write to the database do not insert garbage, but a correctly computed scan result. This is why one can imply that any attempt to write a scan result with a conflicting unique constraint would only overwrite information with identical information (no effect). So, it would not be problematic. The same for skipping the write with `insertIgnore`, with the benefit of not affecting any timestamp information of the entry postgres for some reason may hold.

**Comment by fviernau** [comment]
I decided to simply make a PR, so we can continue discussion there: https://github.com/oss-review-toolkit/ort/pull/10301.
