### ISSUE TITLE
analyzer: Empty binaryRemoteArtifact for Gradle project's dependency causes duplicate package error and prohibits result file creation

### ISSUE THREAD

**Issue by devcooch** [oss-review-toolkit/ort#6780]
1) I use Maven and Gradle package managers together (e.g. in config: `enabledPackageManagers: [Maven, Gradle]`)
2) both Maven and Gradle projects are using same dependency package
3) I run analyzer on the folder with these two project

Something causes binaryArtifact to be empty in Gradle project, which in turn causes two entries in Set<Packages> where only binaryArtifact differs (empty and non-empty).
This in turn creates duplicate packages error, e.g.:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create the AnalyzerResult as it contains packages and projects with the same ids: [[Package(id=Identifier(type=Maven, namespace=org.hamcrest, name=hamcrest-core, version=1.3), purl=pkg:maven/org.hamcrest/hamcrest-core@1.3, cpe=null, authors=[Joe Walnes, Nat Pryce, Steve Freeman, Neil Dunn, Tom Denley], declaredLicenses=[New BSD License], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=BSD-3-Clause, mapped={New BSD License=BSD-3-Clause}, unmapped=[]), concludedLicense=null, description=This is the core API of hamcrest matcher framework to be used by third-party framework providers. This includes the a foundation set of matcher implementations for common operations., homepageUrl=https://github.com/hamcrest/JavaHamcrest/hamcrest-core, binaryArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar, hash=Hash(value=42a25dc3219429f0e5d060061f71acb49bf010a0, algorithm=SHA-1)), sourceArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar, hash=Hash(value=1dc37250fbc78e23a65a67fbbaf71d2e9cbc3c0b, algorithm=SHA-1)), vcs=VcsInfo(type=Git, url=git@github.com:hamcrest/JavaHamcrest.git, revision=, path=), vcsProcessed=VcsInfo(type=Git, url=ssh://git@github.com/hamcrest/JavaHamcrest.git, revision=, path=), isMetadataOnly=false, isModified=false), Package(id=Identifier(type=Maven, namespace=org.hamcrest, name=hamcrest-core, version=1.3), purl=pkg:maven/org.hamcrest/hamcrest-core@1.3, cpe=null, authors=[Joe Walnes, Nat Pryce, Steve Freeman, Neil Dunn, Tom Denley], declaredLicenses=[New BSD License], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=BSD-3-Clause, mapped={New BSD License=BSD-3-Clause}, unmapped=[]), concludedLicense=null, description=This is the core API of hamcrest matcher framework to be used by third-party framework providers. This includes the a foundation set of matcher implementations for common operations., homepageUrl=https://github.com/hamcrest/JavaHamcrest/hamcrest-core, binaryArtifact=RemoteArtifact(url=, hash=Hash(value=, algorithm=)), sourceArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar, hash=Hash(value=1dc37250fbc78e23a65a67fbbaf71d2e9cbc3c0b, algorithm=SHA-1)), vcs=VcsInfo(type=Git, url=git@github.com:hamcrest/JavaHamcrest.git, revision=, path=), vcsProcessed=VcsInfo(type=Git, url=ssh://git@github.com/hamcrest/JavaHamcrest.git, revision=, path=), isMetadataOnly=false, isModified=false)], [Package(id=Identifier(type=Maven, namespace=net.bytebuddy, name=byte-buddy, version=1.9.3), purl=pkg:maven/net.bytebuddy/byte-buddy@1.9.3, cpe=null, authors=[Rafael Winterhalter], declaredLicenses=[The Apache Software License, Version 2.0], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=Apache-2.0, mapped={The Apache Software License, Version 2.0=Apache-2.0}, unmapped=[]), concludedLicense=null, description=Byte Buddy is a Java library for creating Java classes at run time.
        This artifact is a build of Byte Buddy with all ASM dependencies repackaged into its own name space., homepageUrl=http://bytebuddy.net/byte-buddy, binaryArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3.jar, hash=Hash(value=f32e510b239620852fc9a2387fac41fd053d6a4d, algorithm=SHA-1)), sourceArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3-sources.jar, hash=Hash(value=ef8bdb760633510eed72e262193d6afbc451cc72, algorithm=SHA-1)), vcs=VcsInfo(type=Git, url=git@github.com:raphw/byte-buddy.git, revision=byte-buddy-1.9.3, path=), vcsProcessed=VcsInfo(type=Git, url=ssh://git@github.com/raphw/byte-buddy.git, revision=byte-buddy-1.9.3, path=), isMetadataOnly=false, isModified=false), Package(id=Identifier(type=Maven, namespace=net.bytebuddy, name=byte-buddy, version=1.9.3), purl=pkg:maven/net.bytebuddy/byte-buddy@1.9.3, cpe=null, authors=[Rafael Winterhalter], declaredLicenses=[The Apache Software License, Version 2.0], declaredLicensesProcessed=ProcessedDeclaredLicense(spdxExpression=Apache-2.0, mapped={The Apache Software License, Version 2.0=Apache-2.0}, unmapped=[]), concludedLicense=null, description=Byte Buddy is a Java library for creating Java classes at run time.
        This artifact is a build of Byte Buddy with all ASM dependencies repackaged into its own name space., homepageUrl=http://bytebuddy.net/byte-buddy, binaryArtifact=RemoteArtifact(url=, hash=Hash(value=, algorithm=)), sourceArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.9.3/byte-buddy-1.9.3-sources.jar, hash=Hash(value=ef8bdb760633510eed72e262193d6afbc451cc72, algorithm=SHA-1)), vcs=VcsInfo(type=Git, url=git@github.com:raphw/byte-buddy.git, revision=byte-buddy-1.9.3, path=), vcsProcessed=VcsInfo(type=Git, url=ssh://git@github.com/raphw/byte-buddy.git, revision=byte-buddy-1.9.3, path=), isMetadataOnly=false, isModified=false)]]
	at org.ossreviewtoolkit.analyzer.AnalyzerResultBuilder.build(AnalyzerResultBuilder.kt:49)
	at org.ossreviewtoolkit.analyzer.AnalyzerState.buildResult(Analyzer.kt:270)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyzeInParallel(Analyzer.kt:180)
	at org.ossreviewtoolkit.analyzer.Analyzer.analyze(Analyzer.kt:132)
	at org.ossreviewtoolkit.cli.commands.AnalyzerCommand.run(AnalyzerCommand.kt:222)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:75)
```

To simplify debugging, I've create a test project where issue is reproducible with current HEAD and the issue above is visible:
https://github.com/devcooch/ort-gradle-maven-issue

**Comment by devcooch** [comment]
Oh, sounds interesting!

**Comment by devcooch** [comment]
I tried this `gradle-inspector-model-builder` branch and still fails on this test repository, I guess more branches are needed..

**Comment by sschuberth** [comment]
> I tried this `gradle-inspector-model-builder` branch and still fails on this test repository, I guess more branches are needed..

No, but you need to explicitly enable `GradleInspector` and disable `Gradle` as described in the [dedicated `README.md`](https://github.com/oss-review-toolkit/ort/pull/6782/files#diff-75307b425ea854d0b371bec35cf75d91730dc0b71e04f57cd8e7b757c6b74d7bR7-R13).

**Comment by devcooch** [comment]
@sschuberth I am trying to run locally using this instruction. I tried modifying ~/.ort/config/config.yaml and through command-line, but new package manager somehow is not found. Am I missing something? I did git pull today and I assume the code is already merged.

The run configuration looks like this:
![image](https://user-images.githubusercontent.com/2089015/232476529-10a42098-d12f-451c-8ed6-ba4f56e4dbfc.png)

Maybe you have some idea or hint why GradleInspector package manager could not be found?
