### ISSUE TITLE
JRE segfaults when building ORT in Docker

### ISSUE THREAD

**Issue by haikoschol** [oss-review-toolkit/ort#6847]
Trying to build the Dockerfile of ORT revision `5eb8162a9150c24524f1925d27779b432c999f69`.

I'm using Docker with BuildKit on macOS (aarch64) and a [Lima](https://github.com/lima-vm/lima) VM (x86_64), using [Colima](https://github.com/abiosoft/colima). Maybe the issue is related to this uncommon setup. I'll try again later on a stock Ubuntu on x86_64 hardware. But from the error message it looks more likely to be related to this Eclipse JDK image. 🤔

Docker & BuildKit versions:
```
$ docker --version
Docker version 23.0.3, build 3e7cbfdee1
$ docker buildx version
github.com/docker/buildx v0.10.4 c513d34049e499c53468deac6c4267ee72948f02
```

Docker build output:
```
 > [ortbuild 2/2] RUN --mount=type=cache,target=/var/tmp/gradle     --mount=type=bind,target=/home/ort/src/ort,rw     export GRADLE_USER_HOME=/var/tmp/gradle     && sudo chown -R "ort". /home/ort/src/ort /var/tmp/gradle     && scripts/set_gradle_proxy.sh     && ./gradlew --no-daemon --stacktrace         -Pversion=DOCKER-SNAPSHOT         :cli:installDist         :helper-cli:startScripts     && mkdir /opt/ort     && cp -a /home/ort/src/ort/cli/build/install/ort /opt/     && cp -a /home/ort/src/ort/scripts/*.sh /opt/ort/bin/     && cp -a /home/ort/src/ort/helper-cli/build/scripts/orth /opt/ort/bin/     && cp -a /home/ort/src/ort/helper-cli/build/libs/helper-cli-*.jar /opt/ort/lib/:
#0 18.17 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#0 23.76
#0 23.76 FAILURE: Build failed with an exception.
#0 23.76
#0 23.76 * What went wrong:
#0 23.77 Unable to start the daemon process.
#0 23.77 This problem might be caused by incorrect configuration of the daemon.
#0 23.77 For example, an unrecognized jvm option is used.
#0 23.77 Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/8.1/userguide/gradle_daemon.html
#0 23.77 Process command line: /opt/java/openjdk/bin/java -XX:MaxMetaspaceSize=512m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /var/tmp/gradle/wrapper/dists/gradle-8.1-bin/2eyty4r6kz6fpakefpk52nbbm/gradle-8.1/lib/gradle-launcher-8.1.jar -javaagent:/var/tmp/gradle/wrapper/dists/gradle-8.1-bin/2eyty4r6kz6fpakefpk52nbbm/gradle-8.1/lib/agents/gradle-instrumentation-agent-8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.1
#0 23.77 Please read the following process output to find out more:
#0 23.77 -----------------------
#0 23.77 #
#0 23.77 # A fatal error has been detected by the Java Runtime Environment:
#0 23.77 #
#0 23.77 #  SIGSEGV (0xb) at pc=0x00007f6499496f40, pid=42, tid=43
#0 23.79 #
#0 23.79 # JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
#0 23.79 # Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
#0 23.79 # Problematic frame:
#0 23.79 # J 149 c1 java.util.zip.ZipUtils.CENNAM([BI)I java.base@17.0.6 (9 bytes) @ 0x00007f6499496f40 [0x00007f6499496f40+0x0000000000000000]
#0 23.79 #
#0 23.79 # Core dump will be written. Default location: /var/tmp/gradle/daemon/8.1/core
#0 23.80 #
#0 23.80 # An error report file with more information is saved as:
#0 23.80 # /var/tmp/gradle/daemon/8.1/hs_err_pid42.log
#0 23.80 Compiled method (c1)    2543  149       3       java.util.zip.ZipUtils::CENNAM (9 bytes)
#0 23.80  total in heap  [0x00007f6499496d90,0x00007f64994971d0] = 1088
#0 23.80  relocation     [0x00007f6499496ef0,0x00007f6499496f28] = 56
#0 23.81  main code      [0x00007f6499496f40,0x00007f64994970c0] = 384
#0 23.81  stub code      [0x00007f64994970c0,0x00007f64994970f0] = 48
#0 23.81  metadata       [0x00007f64994970f0,0x00007f6499497100] = 16
#0 23.81  scopes data    [0x00007f6499497100,0x00007f6499497130] = 48
#0 23.81  scopes pcs     [0x00007f6499497130,0x00007f64994971b0] = 128
#0 23.81  dependencies   [0x00007f64994971b0,0x00007f64994971b8] = 8
#0 23.82  nul chk table  [0x00007f64994971b8,0x00007f64994971d0] = 24
#0 23.82 #
#0 23.82 # If you would like to submit a bug report, please visit:
#0 23.82 #   https://github.com/adoptium/adoptium-support/issues
#0 23.82 #
#0 23.82
#0 23.82
#0 23.82 * Try:
#0 23.82 > Run with --info or --debug option to get more log output.
#0 23.83 > Run with --scan to get full insights.
#0 23.85
#0 23.85 * Exception is:
#0 23.85 org.gradle.api.GradleException: Unable to start the daemon process.
#0 23.85 This problem might be caused by incorrect configuration of the daemon.
#0 23.85 For example, an unrecognized jvm option is used.
#0 23.85 Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/8.1/userguide/gradle_daemon.html
#0 23.85 Process command line: /opt/java/openjdk/bin/java -XX:MaxMetaspaceSize=512m --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx1024m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /var/tmp/gradle/wrapper/dists/gradle-8.1-bin/2eyty4r6kz6fpakefpk52nbbm/gradle-8.1/lib/gradle-launcher-8.1.jar -javaagent:/var/tmp/gradle/wrapper/dists/gradle-8.1-bin/2eyty4r6kz6fpakefpk52nbbm/gradle-8.1/lib/agents/gradle-instrumentation-agent-8.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.1
#0 23.85 Please read the following process output to find out more:
#0 23.85 -----------------------
#0 23.85 #
#0 23.85 # A fatal error has been detected by the Java Runtime Environment:
#0 23.85 #
#0 23.85 #  SIGSEGV (0xb) at pc=0x00007f6499496f40, pid=42, tid=43
#0 23.85 #
#0 23.85 # JRE version: OpenJDK Runtime Environment Temurin-17.0.6+10 (17.0.6+10) (build 17.0.6+10)
#0 23.85 # Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (17.0.6+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
#0 23.85 # Problematic frame:
#0 23.85 # J 149 c1 java.util.zip.ZipUtils.CENNAM([BI)I java.base@17.0.6 (9 bytes) @ 0x00007f6499496f40 [0x00007f6499496f40+0x0000000000000000]
#0 23.85 #
#0 23.85 # Core dump will be written. Default location: /var/tmp/gradle/daemon/8.1/core
#0 23.85 #
#0 23.85 # An error report file with more information is saved as:
#0 23.85 # /var/tmp/gradle/daemon/8.1/hs_err_pid42.log
#0 23.85 Compiled method (c1)    2543  149       3       java.util.zip.ZipUtils::CENNAM (9 bytes)
#0 23.85  total in heap  [0x00007f6499496d90,0x00007f64994971d0] = 1088
#0 23.85  relocation     [0x00007f6499496ef0,0x00007f6499496f28] = 56
#0 23.85  main code      [0x00007f6499496f40,0x00007f64994970c0] = 384
#0 23.85  stub code      [0x00007f64994970c0,0x00007f64994970f0] = 48
#0 23.85  metadata       [0x00007f64994970f0,0x00007f6499497100] = 16
#0 23.85  scopes data    [0x00007f6499497100,0x00007f6499497130] = 48
#0 23.85  scopes pcs     [0x00007f6499497130,0x00007f64994971b0] = 128
#0 23.85  dependencies   [0x00007f64994971b0,0x00007f64994971b8] = 8
#0 23.85  nul chk table  [0x00007f64994971b8,0x00007f64994971d0] = 24
#0 23.85 #
#0 23.85 # If you would like to submit a bug report, please visit:
#0 23.85 #   https://github.com/adoptium/adoptium-support/issues
#0 23.85 #
#0 23.85
#0 23.85        at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:38)
#0 23.85        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:195)
#0 23.85        at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:151)
#0 23.85        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:222)
#0 23.85        at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startSingleUseDaemon(DefaultDaemonConnector.java:247)
#0 23.85        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:51)
#0 23.85        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
#0 23.85        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
#0 23.85        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
#0 23.85        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
#0 23.87        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
#0 23.87        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
#0 23.88        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
#0 23.88        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
#0 23.89        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
#0 23.89        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
#0 23.89        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
#0 23.89        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
#0 23.89        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
#0 23.90        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
#0 23.90        at org.gradle.launcher.Main.doAction(Main.java:35)
#0 23.90        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
#0 23.90        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 23.91        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 23.91        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 23.91        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 23.91        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
#0 23.92        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
#0 23.92        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 23.92        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 23.92        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 23.92        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 23.92        at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
#0 23.93        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 23.93        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 23.93        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 23.93        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 23.94        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
#0 23.94        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:110)
#0 23.96        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
#0 23.96
#0 23.96
#0 23.96 * Get more help at https://help.gradle.org
------
ERROR: failed to solve: executor failed running [/bin/sh -c export GRADLE_USER_HOME=/var/tmp/gradle     && sudo chown -R "$USER". ${HOME}/src/ort /var/tmp/gradle     && scripts/set_gradle_proxy.sh     && ./gradlew --no-daemon --stacktrace         -Pversion=$ORT_VERSION         :cli:installDist         :helper-cli:startScripts     && mkdir /opt/ort     && cp -a ${HOME}/src/ort/cli/build/install/ort /opt/     && cp -a ${HOME}/src/ort/scripts/*.sh /opt/ort/bin/     && cp -a ${HOME}/src/ort/helper-cli/build/scripts/orth /opt/ort/bin/     && cp -a ${HOME}/src/ort/helper-cli/build/libs/helper-cli-*.jar /opt/ort/lib/]: exit code: 1
```

**Comment by sschuberth** [comment]
> I'm using Docker with BuildKit on macOS (aarch64

Note that we had [several](https://github.com/oss-review-toolkit/ort/issues/5411) [issues](https://github.com/oss-review-toolkit/ort/issues/5840) with building our Docker image on macOS in the past.

> But from the error message it looks more likely to be related to this Eclipse JDK image

IMO it's rather unlikely that we have a general problem there, as we're succeffully buildin gthe image on a daily basis on various (x86) hosts.

**Comment by sschuberth** [comment]
As this seem to happen in the Gradle daemon, and we recently upgraded to version 8.1 which [changed memory allocation for Docker scenarios](https://github.com/gradle/gradle/issues/17610), trying to revert to version 8.0.2 could also be an option.

**Comment by haikoschol** [comment]
> > But from the error message it looks more likely to be related to this Eclipse JDK image
 
> IMO it's rather unlikely that we have a general problem there, as we're succeffully buildin gthe image on a daily basis on various (x86) hosts.

I tried it on a fresh install of Ubuntu 22.04 with Docker installed by following the instructions on docker.com and it worked as expected. It was also so much faster to build all the other bits (Python, Ruby, etc.) on an old ThinkPad X280 that it's probably pointless to continue trying to make it work on the M1 MacBook Air.

**Comment by haikoschol** [comment]
> As this seem to happen in the Gradle daemon, and we recently upgraded to version 8.1 which [changed memory allocation for Docker scenarios](https://github.com/gradle/gradle/issues/17610), trying to revert to version 8.0.2 could also be an option.

I tried downgrading to Gradle 8.0.2 and succeeded in getting a different error message:

```
 > [ortbuild 2/2] RUN --mount=type=cache,target=/var/tmp/gradle     --mount=type=bind,target=/home/ort/src/ort,rw     export GRADLE_USER_HOME=/var/tmp/gradle     && sudo chown -R "ort". /home/ort/src/ort /var/tmp/gradle     && scripts/set_gradle_proxy.sh     && ./gradlew --no-daemon --stacktrace         -Pversion=DOCKER-SNAPSHOT         :cli:installDist         :helper-cli:startScripts     && mkdir /opt/ort     && cp -a /home/ort/src/ort/cli/build/install/ort /opt/     && cp -a /home/ort/src/ort/scripts/*.sh /opt/ort/bin/     && cp -a /home/ort/src/ort/helper-cli/build/scripts/orth /opt/ort/bin/     && cp -a /home/ort/src/ort/helper-cli/build/libs/helper-cli-*.jar /opt/ort/lib/:
#0 10.92 Downloading https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
#0 20.53 ...........10%............20%............30%............40%............50%............60%...........70%............80%............90%............100%
#0 84.28
#0 84.30 Welcome to Gradle 8.0.2!
#0 84.30
#0 84.32 Here are the highlights of this release:
#0 84.33  - Improvements to the Kotlin DSL
#0 84.33  - Fine-grained parallelism from the first build with configuration cache
#0 84.33  - Configurable Gradle user home cache cleanup
#0 84.33
#0 84.33 For more details see https://docs.gradle.org/8.0.2/release-notes.html
#0 84.33
#0 88.50 To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
#0 114.3 Daemon will be stopped at the end of the build
#0 156.0 The message received from the daemon indicates that the daemon has disappeared.
#0 156.0 Build request sent: Build{id=677b5715-3ef2-4f04-83ae-ee241cab253a, currentDir=/home/ort/src/ort}
#0 156.0 Attempting to read last messages from the daemon log...
#0 156.1 Daemon pid: 57
#0 156.1   log file: /var/tmp/gradle/daemon/8.0.2/daemon-57.out.log
#0 156.1 ----- Last  20 lines from daemon log file - daemon-57.out.log -----
#0 156.1 2023-04-14T16:57:52.651+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
#0 156.1 2023-04-14T16:57:52.660+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
#0 156.1 2023-04-14T16:57:52.688+0000 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
#0 156.1 2023-04-14T16:57:52.690+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
#0 156.1 2023-04-14T16:57:52.695+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
#0 156.1 2023-04-14T16:57:52.709+0000 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=677b5715-3ef2-4f04-83ae-ee241cab253a, currentDir=/home/ort/src/ort}. Dispatching build started information...
#0 156.1 2023-04-14T16:57:52.727+0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 22: dispatching org.gradle.launcher.daemon.protocol.BuildStarted@7a1275ba
#0 156.1 2023-04-14T16:57:52.775+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: [PATH, LANGUAGE, HOMEDIR, JAVA_HOME, USER_ID, USER, LANG, CRT_FILES, GRADLE_USER_HOME, ORT_VERSION, LC_ALL, USER_GID, USERNAME, PWD, JAVA_VERSION, HOME]
#0 156.1 2023-04-14T16:57:52.839+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
#0 156.1 2023-04-14T16:57:52.867+0000 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 57). The daemon log file: /var/tmp/gradle/daemon/8.0.2/daemon-57.out.log
#0 156.1 2023-04-14T16:57:52.905+0000 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 20: received class org.gradle.launcher.daemon.protocol.CloseInput
#0 156.1 2023-04-14T16:57:52.906+0000 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 20: Received IO message from client: org.gradle.launcher.daemon.protocol.CloseInput@784bd536
#0 156.1 2023-04-14T16:57:52.915+0000 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] Closing daemon's stdin at end of input.
#0 156.2 2023-04-14T16:57:52.928+0000 [INFO] [org.gradle.launcher.daemon.server.exec.ForwardClientInput] The daemon will no longer process any standard input.
#0 156.2 2023-04-14T16:57:52.962+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon] Requesting daemon stop after processing Build{id=677b5715-3ef2-4f04-83ae-ee241cab253a, currentDir=/home/ort/src/ort}
#0 156.2 2023-04-14T16:57:52.968+0000 [LIFECYCLE] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Daemon will be stopped at the end of the build
#0 156.2 2023-04-14T16:57:52.975+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Stop as soon as idle requested. The daemon is busy: true
#0 156.2 2023-04-14T16:57:52.976+0000 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon stop has been requested. Sleeping until state changes.
#0 156.2 2023-04-14T16:57:53.322+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
#0 156.2 2023-04-14T16:57:53.344+0000 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=26b2bd87-ea58-436b-9bd3-b055c293a6e6,javaHome=/opt/java/openjdk,daemonRegistryDir=/var/tmp/gradle/daemon,pid=57,idleTimeout=120000,priority=NORMAL,daemonOpts=-XX:MaxMetaspaceSize=512m,--add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]
#0 156.2 ----- End of the daemon log -----
#0 156.2
#0 156.2 JVM crash log found: file:///home/ort/src/ort/hs_err_pid57.log
#0 156.3
#0 156.3 FAILURE: Build failed with an exception.
#0 156.3
#0 156.3 * What went wrong:
#0 156.3 Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
#0 156.3
#0 156.3 * Try:
#0 156.3 > Run with --info or --debug option to get more log output.
#0 156.3 > Run with --scan to get full insights.
#0 156.3
#0 156.3 * Exception is:
#0 156.3 org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
#0 156.3        at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:269)
#0 156.4        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:242)
#0 156.4        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:204)
#0 156.4        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:54)
#0 156.4        at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
#0 156.4        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
#0 156.4        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
#0 156.4        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
#0 156.4        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
#0 156.4        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:82)
#0 156.4        at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
#0 156.4        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
#0 156.4        at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
#0 156.4        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
#0 156.4        at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
#0 156.4        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
#0 156.4        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
#0 156.4        at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
#0 156.4        at org.gradle.launcher.Main.doAction(Main.java:35)
#0 156.4        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 156.4        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 156.4        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 156.4        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
#0 156.4        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 156.4        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 156.4        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 156.4        at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
#0 156.4        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
#0 156.4        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
#0 156.4        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
#0 156.4        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
#0 156.4        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:110)
#0 156.4        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
#0 156.4
#0 156.4
#0 156.4 * Get more help at https://help.gradle.org
------
ERROR: failed to solve: executor failed running [/bin/sh -c export GRADLE_USER_HOME=/var/tmp/gradle     && sudo chown -R "$USER". ${HOME}/src/ort /var/tmp/gradle     && scripts/set_gradle_proxy.sh     && ./gradlew --no-daemon --stacktrace         -Pversion=$ORT_VERSION         :cli:installDist         :helper-cli:startScripts     && mkdir /opt/ort     && cp -a ${HOME}/src/ort/cli/build/install/ort /opt/     && cp -a ${HOME}/src/ort/scripts/*.sh /opt/ort/bin/     && cp -a ${HOME}/src/ort/helper-cli/build/scripts/orth /opt/ort/bin/     && cp -a ${HOME}/src/ort/helper-cli/build/libs/helper-cli-*.jar /opt/ort/lib/]: exit code: 1
```

The mentioned JVM crash log at `/home/ort/src/ort/hs_err_pid57.log` might be useful, but I don't know how to get at it, since it never made it into a container image.

Just going off the `DaemonDisappearedException`, this might be the same issue that triggered the memory allocation changes between 8.0.2 and 8.1.

**Comment by haikoschol** [comment]
Closing this since I won't investigate further for now and will build the image on an x86 host.
