### ISSUE TITLE
Docker build: Scancode installation issues

### ISSUE THREAD

**Issue by hornpecom** [oss-review-toolkit/ort#6942]
- Errors during scancode installation will not cause the build to fail

```
#53 [pythonbuild 4/4] RUN arch=$(arch | sed s/aarch64/arm64/)     && if [ "$arch" != "arm64" ]; then         curl -Os https://raw.githubusercontent.com/nexB/scancode-toolkit/v31.2.4/requirements.txt;         pip install -U --constraint requirements.txt scancode-toolkit==31.2.4;         rm requirements.txt;        fi
#53 75.50      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  101.5/103.8 MB 5.5 MB/s eta 0:00:01
#53 75.60 ERROR: Exception:
#53 75.60 Traceback (most recent call last):
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 435, in _error_catcher
#53 75.60     yield
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 516, in read
#53 75.60     data = self._fp.read(amt) if not fp_closed else b""
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 90, in read
#53 75.60     data = self.__fp.read(amt)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/http/client.py", line 465, in read
#53 75.60     s = self.fp.read(amt)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/socket.py", line 705, in readinto
#53 75.60     return self._sock.recv_into(b)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/ssl.py", line 1274, in recv_into
#53 75.60     return self.read(nbytes, buffer)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/ssl.py", line 1130, in read
#53 75.60     return self._sslobj.read(len, buffer)
#53 75.60 TimeoutError: The read operation timed out
#53 75.60 
#53 75.60 During handling of the above exception, another exception occurred:
#53 75.60 
#53 75.60 Traceback (most recent call last):
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
#53 75.60     status = run_func(*args)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
#53 75.60     return func(self, options, args)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 369, in run
#53 75.60     requirement_set = resolver.resolve(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
#53 75.60     result = self._result = resolver.resolve(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
#53 75.60     state = resolution.resolve(requirements, max_rounds=max_rounds)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
#53 75.60     self._add_to_criteria(self.state.criteria, r, parent=None)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
#53 75.60     if not criterion.candidates:
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
#53 75.60     return bool(self._sequence)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#53 75.60     return any(self)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#53 75.60     return (c for c in iterator if id(c) not in self._incompatible_ids)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#53 75.60     candidate = func()
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
#53 75.60     self._link_candidate_cache[link] = LinkCandidate(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
#53 75.60     super().__init__(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
#53 75.60     self.dist = self._prepare()
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
#53 75.60     dist = self._prepare_distribution()
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
#53 75.60     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 438, in prepare_linked_requirement
#53 75.60     return self._prepare_linked_requirement(req, parallel_builds)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 483, in _prepare_linked_requirement
#53 75.60     local_file = unpack_url(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 165, in unpack_url
#53 75.60     file = get_http_url(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 106, in get_http_url
#53 75.60     from_path, content_type = download(link, temp_dir.path)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/network/download.py", line 147, in __call__
#53 75.60     for chunk in chunks:
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 53, in _rich_progress_bar
#53 75.60     for chunk in iterable:
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
#53 75.60     for chunk in response.raw.stream(
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 573, in stream
#53 75.60     data = self.read(amt=amt, decode_content=decode_content)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 509, in read
#53 75.60     with self._error_catcher():
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/contextlib.py", line 153, in __exit__
#53 75.60     self.gen.throw(typ, value, traceback)
#53 75.60   File "/opt/python/versions/3.10.8/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 440, in _error_catcher
#53 75.60     raise ReadTimeoutError(self._pool, None, "Read timed out.")
#53 75.60 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
#53 75.66 
#53 75.66 [notice] A new release of pip available: 22.2.2 -> 23.1.2
#53 75.66 [notice] To update, run: pip install --upgrade pip
#53 DONE 76.6s

#52 [rubybuild 6/6] RUN rbenv install 3.1.2 -v     && rbenv global 3.1.2     && gem install bundler cocoapods:1.11.2
#52 571.9 make[2]: Leaving directory '/tmp/ruby-build.20230428103753.19.ylEU8Z/ruby-3.1.2/ext/digest/sha1'
#52 571.9 make[2]: Entering directory '/tmp/ruby-build.20230428103753.19.ylEU8Z/ruby-3.1.2/ext/json/parser'
```

**Comment by sschuberth** [comment]
This

> TimeoutError: The read operation timed out

does not actually look like an SSL certificate issue. What's the exact command line you're running `docker build` with? In particular, do you pass a build argument for custom certificate files?

**Comment by sschuberth** [comment]
> Ok, the timeout error can be a proxy server issue

Indeed. And as there's not other error than that, I'm closing this. Feel free to reopen with additional information if the issue persists.
