### ISSUE TITLE
NoSuchElementException during EvaluatedModelReporter

### ISSUE THREAD

**Issue by MarcelBochtler** [oss-review-toolkit/ort#7042]
During the creation of the EvaluatedModelReporter / WebAppReporter, the ORT reporter crashes with this exception:

```
java.util.NoSuchElementException: Key Identifier(type=Unknown, namespace=<unknown>, name=org.springframework.cloud_spring-cloud-sleuth-zipkin, version=) is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:349)
	at org.ossreviewtoolkit.plugins.reporters.evaluatedmodel.EvaluatedModelMapper.addShortestPaths(EvaluatedModelMapper.kt:694)
	at org.ossreviewtoolkit.plugins.reporters.evaluatedmodel.EvaluatedModelMapper.build(EvaluatedModelMapper.kt:126)
	at org.ossreviewtoolkit.plugins.reporters.evaluatedmodel.EvaluatedModel$Companion.create(EvaluatedModel.kt:151)
	at org.ossreviewtoolkit.plugins.reporters.evaluatedmodel.EvaluatedModelReporter.generateReport(EvaluatedModelReporter.kt:50)
	at org.ossreviewtoolkit.cli.commands.ReporterCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReporterCommand.kt:288)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

Unfortunately, I cannot provide an example project to reproduce this. But with an evaluator-result.yml from a customer, I can reproduce this behavior.

Git bisect shows this commit as the cause:
https://github.com/oss-review-toolkit/ort/commit/8e1a9cee3a97c38be83303b02fa2457a240038fc

Reverting this commit fixes the issue.

**Comment by sschuberth** [comment]
For the record, I've seen this flying by recently, too. IIRC it was for the ID of a project (not package) where the version was unspecified. Maybe that's the thing in common: That some of the ID's properties are "unusual".

**Comment by MarcelBochtler** [comment]
According to git bisect the same commit also causes the WebApp reporter to be broken if it was created successfully:
![image](https://github.com/oss-review-toolkit/ort/assets/4022103/33eaab0c-f996-4078-ac2b-8ce626dfc295)
