### ISSUE TITLE
The analyzer cannot run `python-inspector` although it is install in `PATH`

### ISSUE THREAD

**Issue by HardikRa** [oss-review-toolkit/ort#7086]
I tried to scan Django as I had a while ago and noticed that there are some issues present in the json file
The command I ran after cloning Django is `/home/unixusername/BEProject/ort/cli/build/install/ort/bin/ort --debug --stacktrace -P ort.analyzer.allowDynamicVersions=true analyze -i /home/unixusername/clonedProjects/django -o /home/unixusername/clonedProjects/djangoORTAnalyzerOutput -f JSON`

This is what I found in the JSON
```
"issues" : {
        "PIP::docs/requirements.txt:" : [ {
          "timestamp" : "2023-06-03T12:20:31.076951Z",
          "source" : "PIP",
          "message" : "PIP failed to resolve dependencies for path 'docs/requirements.txt': IOException: Cannot run program \"python-inspector\" (in directory \"/home/unixusername/clonedProjects/django/docs\"): error=2, No such file or directory\nCaused by: IOException: error=2, No such file or directory",
          "severity" : "ERROR"
        } ],
        "PIP::setup.py:" : [ {
          "timestamp" : "2023-06-03T12:20:30.945884200Z",
          "source" : "PIP",
          "message" : "PIP failed to resolve dependencies for path 'setup.py': IOException: Cannot run program \"python-inspector\" (in directory \"/home/unixusername/clonedProjects/django\"): error=2, No such file or directory\nCaused by: IOException: error=2, No such file or directory",
          "severity" : "ERROR"
        } ],
        "PIP::tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt:" : [ {
          "timestamp" : "2023-06-03T12:20:31.002084100Z",
          "source" : "PIP",
          "message" : "PIP failed to resolve dependencies for path 'tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt': IOException: Cannot run program \"python-inspector\" (in directory \"/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir\"): error=2, No such file or directory\nCaused by: IOException: error=2, No such file or directory",
          "severity" : "ERROR"
        } ]
      }
```
and I had to perform a keyboard interrupt in order to get this on the stacktrace
```
17:54:33.563 [main] DEBUG org.ossreviewtoolkit.cli.OrtMain - Used command line arguments: [--debug, --stacktrace, -P, ort.analyzer.allowDynamicVersions=true, analyze, -i, /home/unixusername/clonedProjects/django, -o, /home/unixusername/clonedProjects/djangoORTAnalyzerOutput, -f, JSON]
17:54:33.607 [main] INFO  org.ossreviewtoolkit.model.config.OrtConfiguration - Using ORT configuration arguments:
        ort.analyzer.allowDynamicVersions=true
17:54:33.998 [main] INFO  org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - EnvironmentVariableFilter initialized with denySubstrings = [key, pass, pwd, token, user] and allowNames = [CARGO_HTTP_USER_AGENT, COMPOSER_ALLOW_SUPERUSER, CONAN_LOGIN_ENCRYPTION_KEY, CONAN_LOGIN_USERNAME, CONAN_PASSWORD, CONAN_USERNAME, CONAN_USER_HOME, CONAN_USER_HOME_SHORT, DOTNET_CLI_CONTEXT_ANSI_PASS_THRU, GIT_ASKPASS, GIT_HTTP_USER_AGENT, GRADLE_USER_HOME, HACKAGE_USERNAME, HACKAGE_PASSWORD, HACKAGE_KEY, PWD, USER, USERPROFILE].
 ______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version ab1779038b.
|    |   | |       _/ |    |
|    |   | |    |   \ |    |    Running 'analyze' as 'root' under Java 17.0.5 on Linux
\________/ |____|___/ |____|    with 12 CPUs and a maximum of 1530 MiB of memory.

Environment variables:
ORT_CONFIG_DIR = /root/.ort/config
ORT_DATA_DIR = /root/.ort
SHELL = /bin/bash
TERM = xterm-256color

Looking for ORT configuration in the following file:
        /root/.ort/config/config.yml (does not exist)

Looking for analyzer-specific configuration in the following files and directories:
        /home/unixusername/clonedProjects/django/.ort.yml (does not exist)
        /root/.ort/config/resolutions.yml (does not exist)
The following 24 package manager(s) are enabled:
        Bower, Bundler, Cargo, Carthage, CocoaPods, Composer, Conan, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, PNPM, Poetry, Pub, SBT, SpdxDocumentFile, Stack, Unmanaged, Yarn, Yarn2
The following 2 package curation provider(s) are enabled:
        DefaultDir, DefaultFile
Analyzing project path:
        /home/unixusername/clonedProjects/django
17:54:34.798 [main] DEBUG org.ossreviewtoolkit.analyzer.Analyzer - Using the following configuration settings:
--- {}

17:54:34.811 [main] DEBUG org.ossreviewtoolkit.analyzer.PackageManager - Searching for managed files using the following excludes: Excludes(paths=[], scopes=[])
17:54:35.513 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/home/unixusername/clonedProjects/django/.git' as it is hard-coded to be ignored.
Found 1 NPM definition file(s) at:
        package.json
Found 3 PIP definition file(s) at:
        setup.py
        tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt
        docs/requirements.txt
Found in total 4 definition file(s) from the following 2 package manager(s):
        NPM, PIP
17:54:37.035 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Starting NPM analysis.
17:54:37.044 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Starting PIP analysis.
17:54:37.045 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using PIP to resolve dependencies for path 'setup.py'...
17:54:37.062 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Resolving dependencies for '/home/unixusername/clonedProjects/django/setup.py' with Python version '3.10' and operating system 'linux'.
17:54:37.070 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - Filtering out these variables from the environment: [SUDO_USER]
17:54:37.070 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - Filtering out these variables from the environment: [SUDO_USER]
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.104 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Unable to determine dependencies for definition file '/home/unixusername/clonedProjects/django/setup.py': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.128 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'npm --version' in '/home/unixusername/BEProject/ScanRE/backend/app/Controllers'...
17:54:37.351 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
17:54:37.378 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
17:54:37.447 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.SystemReader - loading config FileBasedConfig[/root/.config/jgit/config]
17:54:37.453 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - readpipe [/usr/bin/git, --version],/usr/bin
17:54:37.470 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - readpipe may return 'git version 2.25.1'
17:54:37.471 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - remaining output:

17:54:37.473 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - readpipe [/usr/bin/git, config, --system, --show-origin, --list, -z],/usr/bin
17:54:37.496 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - readpipe may return 'null'
17:54:37.496 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - remaining output:

17:54:37.550 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - readpipe rc=128
17:54:37.551 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.FS - Exception caught during execution of command '[/usr/bin/git, config, --system, --show-origin, --list, -z]' in '/usr/bin', return code '128', error message 'fatal: unable to read config file '/etc/gitconfig': No such file or directory
'
17:54:37.553 [DefaultDispatcher-worker-2] DEBUG org.eclipse.jgit.util.SystemReader - loading config FileBasedConfig[/root/.gitconfig]
17:54:37.640 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - PIP failed to resolve dependencies for path 'setup.py': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
17:54:37.646 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - PIP resolved dependencies for path 'setup.py' in 592.763700ms.
17:54:37.646 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using PIP to resolve dependencies for path 'tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt'...
17:54:37.646 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Resolving dependencies for '/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt' with Python version '3.10' and operating system 'linux'.
17:54:37.649 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - Filtering out these variables from the environment: [SUDO_USER]
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.671 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Unable to determine dependencies for definition file '/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.711 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - PIP failed to resolve dependencies for path 'tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/tests/admin_scripts/custom_templates/project_template/additional_dir"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
17:54:37.712 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - PIP resolved dependencies for path 'tests/admin_scripts/custom_templates/project_template/additional_dir/requirements.txt' in 65.556ms.
17:54:37.712 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using PIP to resolve dependencies for path 'docs/requirements.txt'...
17:54:37.712 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Resolving dependencies for '/home/unixusername/clonedProjects/django/docs/requirements.txt' with Python version '3.10' and operating system 'linux'.
17:54:37.715 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - Filtering out these variables from the environment: [SUDO_USER]
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/docs"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.735 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.plugins.packagemanagers.python.Pip - Unable to determine dependencies for definition file '/home/unixusername/clonedProjects/django/docs/requirements.txt': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/docs"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
java.io.IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/docs"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
        at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
        at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.run(PythonInspector.kt:60)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.utils.PythonInspector.inspect(PythonInspector.kt:108)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.runPythonInspector(Pip.kt:111)
        at org.ossreviewtoolkit.plugins.packagemanagers.python.Pip.resolveDependencies(Pip.kt:93)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 19 more
17:54:37.760 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - PIP failed to resolve dependencies for path 'docs/requirements.txt': IOException: Cannot run program "python-inspector" (in directory "/home/unixusername/clonedProjects/django/docs"): error=2, No such file or directory
Caused by: IOException: error=2, No such file or directory
17:54:37.761 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.PackageManager - PIP resolved dependencies for path 'docs/requirements.txt' in 49.050100ms.
17:54:37.770 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Finished PIP analysis.
17:54:38.194 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - 9.6.6
17:54:38.195 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - 
17:54:38.225 [DefaultDispatcher-worker-1] WARN  org.ossreviewtoolkit.utils.common.CommandLineTool - The command is required in version >=6.0.0 and <9.0.0, but you are using version 9.6.6. This could lead to problems.
17:54:38.225 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using NPM to resolve dependencies for path 'package.json'...
17:54:38.231 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.EnvironmentVariableFilter - Filtering out these variables from the environment: [SUDO_USER]
^C17:54:38.254 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'npm ci --ignore-scripts --no-audit' in '/home/unixusername/clonedProjects/django'...
```

**Comment by sschuberth** [comment]
> Cannot run program "python-inspector"

If you're not running ORT from a Docker image built from our [Dockerfile](https://github.com/oss-review-toolkit/ort/blob/main/Dockerfile) you need to install [python-inspector](https://github.com/nexB/python-inspector) manually (plus all other tools as indicated by `ort requirements`). Also see https://github.com/oss-review-toolkit/ort#running-the-tools.

**Comment by HardikRa** [comment]
I do in fact have `python-inspector` installed and it still is not working, hence the issue, here is the output of running ort requirements that shows the same
```
Other tools:
        - MercurialCommand: Requires 'hg' in no specific version. Tool not found.
        - NuGetInspector: Requires 'nuget-inspector' in no specific version. Tool not found.
        * PythonInspector: Requires 'python-inspector' in version >=0.9.2. Found version 0.9.7.
```

**Comment by sschuberth** [comment]
> I do in fact have `python-inspector` installed and it still is not working

Then you probably don't have it in your `PATH` environment. From the same prompt where `ort --version` works, also `python-inspector --version` needs to work.

> hence the issue

That was not obvious from the original report.

**Comment by HardikRa** [comment]
`./ort --version` and `python-inspector --version` does work in the same folder, and `python-inspector` works globally while my venv is active. Here is a clip from my terminal.
```
(BEProject) unixusername@HardiksLaptop:~/BEProject/ort/cli/build/install/ort/bin$ ./ort --version
ab1779038b
(BEProject) unixusername@HardiksLaptop:~/BEProject/ort/cli/build/install/ort/bin$ python-inspector --version
Python-inspector version: 0.9.7
```
Do let me know if I can provide any additional information or help solve this issue in any way

**Comment by sschuberth** [comment]
> Running 'analyze' as 'root' under Java 17.0.5 on Linux

So you're running ORT as "root". Please double check that you're also "root" when running `python-inspector` manually.

> and python-inspector works globally while my venv is active. Here is a clip from my terminal.

What venv exactly? ORT itself doesn't know anything about venv and probably bypasses it when trying to run `python-inspector`.

**Comment by sschuberth** [comment]
@HardikRa is there any update on the issue?

**Comment by HardikRa** [comment]
Will update by tomorrow

**Comment by mnonnenmacher** [comment]
@HardikRa Is this still relevant or can this issue be closed?

**Comment by sschuberth** [comment]
Closing due to a lack of feedback.
