### ISSUE TITLE
Scanner / Evaluator fail with error "There must be exactly one unique provenance associated with the empty path"

### ISSUE THREAD

**Issue by bennati** [oss-review-toolkit/ort#7263]
This error trace is 
```
Exception in thread "main" java.lang.IllegalArgumentException: There must be exactly one unique provenance associated with the empty path.
	at org.ossreviewtoolkit.model.utils.ScanResultUtilsKt.mergeScanResultsByScanner(ScanResultUtils.kt:42)
	at org.ossreviewtoolkit.model.ScannerRun.getMergedResultsForId(ScannerRun.kt:163)
	at org.ossreviewtoolkit.model.ScannerRun.access$getMergedResultsForId(ScannerRun.kt:39)
	at org.ossreviewtoolkit.model.ScannerRun$scanResultsById$2.invoke(ScannerRun.kt:137)
	at org.ossreviewtoolkit.model.ScannerRun$scanResultsById$2.invoke(ScannerRun.kt:136)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.model.ScannerRun.getScanResultsById(ScannerRun.kt:136)
	at org.ossreviewtoolkit.model.ScannerRun.getIssues(ScannerRun.kt:189)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.run(ScannerCommand.kt:169)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:67)
```

This issue crashes both the Scanner and the Evaluator, it happens with both Git and GitRepo projects.

**Comment by sschuberth** [comment]
FYI, related [Slack conversation](https://ort-talk.slack.com/archives/C9NNJ54B1/p1688646731768639).
