### ISSUE TITLE
Error running scanner

### ISSUE THREAD

**Issue by mrityunjay-cnuro** [oss-review-toolkit/ort#7438]
I'm a new user and trying to run ORT under Win11 using WSL. I'm able to get the analyze step to run but facing the below error running scanner. 
```
Scanning projects with:
        ScanCode (version 32.0.6)
Scanning packages with:
        ScanCode (version 32.0.6)
Exception in thread "main" kotlinx.serialization.MissingFieldException: Field 'licenses' is required for type with serial name 'org.ossreviewtoolkit.plugins.scanners.scancode.FileEntry', but it was missing
        at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
        at org.ossreviewtoolkit.plugins.scanners.scancode.FileEntry.<init>(ScanCodeResultModel.kt:51)
        at org.ossreviewtoolkit.plugins.scanners.scancode.FileEntry$$serializer.deserialize(ScanCodeResultModel.kt:51)
        at org.ossreviewtoolkit.plugins.scanners.scancode.FileEntry$$serializer.deserialize(ScanCodeResultModel.kt:51)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
        at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280)
        at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCodeResult$$serializer.deserialize(ScanCodeResultModel.kt:29)
        at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCodeResult$$serializer.deserialize(ScanCodeResultModel.kt:29)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:127)
        at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCodeResultParserKt.parseResult(ScanCodeResultParser.kt:183)
        at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCodeResultParserKt.parseResult(ScanCodeResultParser.kt:57)
        at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCode.createSummary(ScanCode.kt:165)
        at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.scanPath(CommandLinePathScannerWrapper.kt:42)
        at org.ossreviewtoolkit.scanner.Scanner.scanPath(Scanner.kt:607)
        at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:459)
        at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:194)
        at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.runScanners(ScannerCommand.kt:228)
        at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.run(ScannerCommand.kt:155)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:72)
```

**Comment by sschuberth** [comment]
Your ScanCode version of 32.0.6 is too new, also see https://github.com/oss-review-toolkit/ort/issues/6617. Currently, your options are to either downgrade ScanCode to version 31.2.4 (as [used in the Dockerfile](https://github.com/oss-review-toolkit/ort/blob/65f50322b29baf250c56233222f8f050de52bf96/Dockerfile#L143)s), or manually merge https://github.com/oss-review-toolkit/ort/pull/7397 (which only fails due to a bug in a test tool that we use) and build ORT from source.

To keep the topic to a single place, I'm closing this in favor of https://github.com/oss-review-toolkit/ort/issues/6617.
