### ISSUE TITLE
Missing Key 'AFNetworking/UIKit' from CocoaPod in Dependency Map from ORT analyzer

### ISSUE THREAD

**Issue by ksg97031** [oss-review-toolkit/ort#7523]
While testing the  https://github.com/youusername/magnetX.git repository, I came across a crash issue. The problem is related to a missing key, specifically "AFNetworking/UIKit." It's worth noting that this issue is considered common in the majority of repositories that utilize AFNetworking.

```
9:33:11.814 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'pod repo add-cdn trunk https://cdn.cocoapods.org --allow-root' in '/Users/ksg/test/'...

java.util.NoSuchElementException: Key AFNetworking/UIKit is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:360)
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPodsKt.getPackageReferences$createPackageReference(CocoaPods.kt:256)
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPodsKt.getPackageReferences$createPackageReference(CocoaPods.kt:257)
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPodsKt.getPackageReferences(CocoaPods.kt:262)
  1 #!/bin/bash
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPodsKt.access$getPackageReferences(CocoaPods.kt:1)
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPods.resolveDependenciesInternal(CocoaPods.kt:130)
        at org.ossreviewtoolkit.plugins.packagemanagers.cocoapods.CocoaPods.resolveDependencies(CocoaPods.kt:110)
        at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:319)
        at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:323)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by sschuberth** [comment]
> While testing the https://github.com/yourusername/magnetX repository

Thanks for the report, would you have an actually existing repository to reproduce?

**Comment by ksg97031** [comment]
> > While testing the https://github.com/yourusername/magnetX repository
> 
> Thanks for the report, would you have an actually existing repository to reproduce?

Oh, there was a typo error. This is the test project: https://github.com/youusername/magnetX.git

**Comment by ksg97031** [comment]
@sschuberth
The PackageManager for CocoaPods only creates a package reference with a depth of 1. However, the issue arises because "AFNetworking/UIKit" is not within this depth, resulting in a key mapping error.

Temporarily, you have the option to disregard unparsed dependencies 

https://github.com/oss-review-toolkit/ort/blob/af1cbfc196c65299e5132aecfcdd2365f93f386a/plugins/package-managers/cocoapods/src/main/kotlin/CocoaPods.kt#L254-L258 

to 

```kotlin
fun createPackageReference(name: String): PackageReference =
    PackageReference(
        id = Identifier("Pod", "", name, versionForName.getValue(name)),
        dependencies = dependenciesForName.getValue(name).mapNotNullTo(mutableSetOf()) {
            if (versionForName.containsKey(it)) {
                createPackageReference(it)
            } else {
                null
            }
        }
    )
```

**Comment by fviernau** [comment]
@ksg97031  mind explaining a bit more what you mean by "It's worth noting that this issue is considered common in the majority of repositories that utilize AFNetworking." ?

**Comment by fviernau** [comment]
Thanks @ksg97031 ! Mind also giving a hint why you think "The PackageManager for CocoaPods only creates a package reference with a depth of 1." ?

**Comment by sschuberth** [comment]
Hmm, we certainly have transitive / more than first-level dependencies in our test data for CocoaPods:

https://github.com/oss-review-toolkit/ort/blob/b8d271204291a8626463fadb51eabf16cb7d6dfb/plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/dep-tree-expected-output.yml#L19-L31

**Comment by ksg97031** [comment]
> Hmm, we certainly have transitive / more than first-level dependencies in our test data for CocoaPods:
> 
> https://github.com/oss-review-toolkit/ort/blob/b8d271204291a8626463fadb51eabf16cb7d6dfb/plugins/package-managers/cocoapods/src/funTest/assets/projects/synthetic/dep-tree-expected-output.yml#L19-L31

In your case, the first-level dependencies can encompass the second-level dependencies as indicated in [Podfile1.lock.txt](https://github.com/oss-review-toolkit/ort/files/12683481/Podfile1.lock.txt). However, in some other cases, the first-level dependencies do not encompass the second-level dependencies as seen in [Podfile2.lock.txt](https://github.com/oss-review-toolkit/ort/files/12683482/Podfile2.lock.txt), leading to key mapping errors.

You can verify this using the following script:
```
def intersection(filename):
    with open(filename, 'r') as f:
        data = f.read()
        data = data.split('PODS:\n')[1].split('DEPENDENCIES:')[0].rstrip()

        first_level = set([])
        second_level = set([])
        for line in data.split("\n"):
            entry = line.split('- ')[1]

            if line.startswith('  -'):
                name = entry.split(' (')[0]
                first_level.add(name)
            elif line.startswith('    -'):
                name = entry.split(' (')[0]
                second_level.add(name)
            else:
                raise Exception("error")


        if len(second_level - first_level) == 0:
            print("[%s] second_level ∩ first_level = second_level" % filename)
        else:
            print("[%s] second_level ∩ first_level != second_level" % filename)

if __name__ == '__main__':
    intersection('Podfile1.lock.txt')
    intersection('Podfile2.lock.txt')
```

Result:
```
$ python test.py
[Podfile1.lock.txt] second_level ∩ first_level = second_level
[Podfile2.lock.txt] second_level ∩ first_level != second_level
```

**Comment by fviernau** [comment]
@ksg97031 I wonder whether the lockfile normally should contain all dependencies of the dependency tree. Or phrased differently, can the described problem happen in case the lockfile covers all dependencies in the dependency tree?
