### ISSUE TITLE
Troubleshooting information improvement proposal

### ISSUE THREAD

**Issue by LuciaMartinezGavier** [oss-review-toolkit/ort#7766]
I propose to improve the message when something fails because of timeout.

Now I'm receiving this exception when downloading gradle:
```
Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-8.4-bin.zip failed: timeout (10000ms)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:151)
	at org.gradle.wrapper.Download.download(Download.java:109)
	at org.gradle.wrapper.Install.forceFetch(Install.java:171)
	at org.gradle.wrapper.Install.fetchDistribution(Install.java:104)
	at org.gradle.wrapper.Install.access$400(Install.java:46)
	at org.gradle.wrapper.Install$1.call(Install.java:81)
	at org.gradle.wrapper.Install$1.call(Install.java:68)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:68)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:102)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:66)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:305)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:177)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:509)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:604)
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:373)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:207)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:193)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:129)

```
But it might be better to receive a cleaner message informing the timeout

@dgutson

**Comment by sschuberth** [comment]
During which operation does this timeout happen @LuciaMartinezGavier? I looks like something that's not happening when actually running ORT, but probably when building the Docker image / building ORT. Because the error seems to come directly from the Gradle wrapper, not ORT (there's no `org.ossreviewtoolkit` package in the stacktrace).

**Comment by LuciaMartinezGavier** [comment]
Yes, it was while building the Docker image

**Comment by dgutson** [comment]
then @LuciaMartinezGavier let's consider to report this to Gradle.

@sschuberth you can close this issue.

**Comment by sschuberth** [comment]
Then this is nothing we can really improve on as this message comes directly from Gradle. In fact, we're explicitly telling Gradle to *include* the stack trace via `--stacktrace` in the `Dockerfile`, but this is nothing I'd want to remove as it provides valuable diagnostics in other failure cases. If the verbose output confuses you, just remove `--stacktrace` in your own copy of the `Dockerfile`s.
