### ISSUE TITLE
Scanner fails with PIP::protobuf:  has a non-empty VCS path which is not allowed 

### ISSUE THREAD

**Issue by dimitris-iliou** [oss-review-toolkit/ort#7821]
```
 WARN  org.ossreviewtoolkit.scanner.Scanner - Could not read scan result for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@main.gitlab.in.here.com:3389/external/protobuf, revision=6484708b736239546051af5ee5713e0116477037, path=upstream/third_party/benchmark), resolvedRevision=6484708b736239546051af5ee5713e0116477037) from ProvenanceBasedPostgresStorage: ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
11:22:20.293 [main] WARN  org.ossreviewtoolkit.scanner.Scanner - Could not read scan result for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@main.gitlab.in.here.com:3389/external/protobuf, revision=6484708b736239546051af5ee5713e0116477037, path=upstream/third_party/googletest), resolvedRevision=6484708b736239546051af5ee5713e0116477037) from ProvenanceBasedPostgresStorage: ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
11:22:29.004 [main] WARN  org.ossreviewtoolkit.downloader.vcs.GitWorkingTree - Git submodule at 'upstream/third_party/benchmark' not initialized. Cannot recursively list its submodules.
11:22:29.005 [main] WARN  org.ossreviewtoolkit.downloader.vcs.GitWorkingTree - Git submodule at 'upstream/third_party/googletest' not initialized. Cannot recursively list its submodules.
11:35:33.476 [main] WARN  org.ossreviewtoolkit.scanner.Scanner - Could not write scan result for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@main.gitlab.in.here.com:3389/external/protobuf, revision=6484708b736239546051af5ee5713e0116477037, path=upstream/third_party/benchmark), resolvedRevision=6484708b736239546051af5ee5713e0116477037) to ProvenanceBasedPostgresStorage: ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
11:35:34.517 [main] WARN  org.ossreviewtoolkit.downloader.vcs.GitWorkingTree - Git submodule at 'upstream/third_party/benchmark' not initialized. Cannot recursively list its submodules.
11:35:34.518 [main] WARN  org.ossreviewtoolkit.downloader.vcs.GitWorkingTree - Git submodule at 'upstream/third_party/googletest' not initialized. Cannot recursively list its submodules.
11:48:30.481 [main] WARN  org.ossreviewtoolkit.scanner.Scanner - Could not write scan result for RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=ssh://git@main.gitlab.in.here.com:3389/external/protobuf, revision=6484708b736239546051af5ee5713e0116477037, path=upstream/third_party/googletest), resolvedRevision=6484708b736239546051af5ee5713e0116477037) to ProvenanceBasedPostgresStorage: ScanStorageException: Repository provenances with a non-empty VCS path are not supported.
Exception in thread "main" java.lang.IllegalArgumentException: The resolved sub-repository for package PIP::protobuf: under path 'upstream/third_party/benchmark' has a non-empty VCS path which is not allowed.
	at org.ossreviewtoolkit.model.ProvenanceResolutionResult.<init>(ProvenanceResolutionResult.kt:68)
	at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:192)
	at org.ossreviewtoolkit.scanner.Scanner$scan$2.invokeSuspend(Scanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.runScanners(ScannerCommand.kt:240)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.run(ScannerCommand.kt:153)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:72)
```

**Comment by sschuberth** [comment]
@mnonnenmacher could you assist here?

**Comment by sschuberth** [comment]
> @mnonnenmacher could you assist here?

Ping again @mnonnenmacher, any idea how the issue could occur?

**Comment by mnonnenmacher** [comment]
> Ping again @mnonnenmacher, any idea how the issue could occur?

No, I haven't seen this error message for a long time.
@dimitris-iliou Can you check if the issue still occurs with the latest ORT release, and if so, can you provide steps to reproduce it?

**Comment by sschuberth** [comment]
Closed as part of backlog grooming. Feel free to comment if you would like to contribute to this.
