### ISSUE TITLE
Analyzer: Go package manager fails if go module version contains upper-case characters

### ISSUE THREAD

**Issue by bs-tu-osmi** [oss-review-toolkit/ort#7879]
If the version of a dependent go library **contains upper-case characters**, ORT analyzer fails and creates a stack trace.

**How to reproduce?**

Given the following Go module dependency:

    Running 'go list -m -json -buildvcs=false all' in ...
    ...
    {
    	"Path": "github.com/eclipse-kanto/update-manager",
    	"Version": "v0.1.0-M4.0.20231102094829-08e0c3cd016c",
    	"Time": "2023-11-02T09:48:29Z",
    	"GoMod": "/Users/klw1imb/go/pkg/mod/cache/download/github.com/eclipse-kanto/
    	   update-manager/@v/v0.1.0-!m4.0.20231102094829-08e0c3cd016c.mod",
    	"GoVersion": "1.17"
    }

Will result in:

    java.io.FileNotFoundException: /var/folders/s6/pz_cc3kn7jq1794gysvg3fk80000gq/T/ort-GoMod6417441135426321236/pkg/mod/cache/download/github.com/eclipse-kanto/update-manager/@v/v0.1.0-M4.0.20231102094829-08e0c3cd016c.info (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.ossreviewtoolkit.plugins.packagemanagers.go.GoModKt.toVcsInfo(GoMod.kt:461)

But, a file named `v0.1.0-!m4.0.20231102094829-08e0c3cd016c.info` actually exists in this directory.

Consequence: Currently, with ORT analyzer and the package manager for Go you cannot use versions in dependent go modules that contain upper-case characters.

**Comment by sschuberth** [comment]
There's also a difference WRT "!" between the file names:

```
v0.1.0-M4.0.20231102094829-08e0c3cd016c.info
v0.1.0-!m4.0.20231102094829-08e0c3cd016c.info
```

Or is this a typo?
