### ISSUE TITLE
ort scan java.io.IOException

### ISSUE THREAD

**Issue by remi-cogito** [oss-review-toolkit/ort#7893]
System:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

Java:
openjdk 11.0.20.1 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

After running ort scan I am getting:
```
Scanning projects with:
Exception in thread "main" java.io.IOException: Cannot run program "scancode": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:95)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:33)
	at org.ossreviewtoolkit.utils.common.ProcessCapture.<init>(ProcessCapture.kt:41)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.run(CommandLineTool.kt:82)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.run(CommandLinePathScannerWrapper.kt:31)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion(CommandLineTool.kt:88)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getVersion(CommandLinePathScannerWrapper.kt:31)
	at org.ossreviewtoolkit.plugins.scanners.scancode.ScanCode.getVersion(ScanCode.kt:142)
	at org.ossreviewtoolkit.utils.common.CommandLineTool$DefaultImpls.getVersion$default(CommandLineTool.kt:87)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$version$2.invoke(CommandLinePathScannerWrapper.kt:32)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper$version$2.invoke(CommandLinePathScannerWrapper.kt:32)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.ossreviewtoolkit.scanner.CommandLinePathScannerWrapper.getVersion(CommandLinePathScannerWrapper.kt:32)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:193)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand$runScanners$1.invoke(ScannerCommand.kt:193)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3490)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3507)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3506)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.runScanners(ScannerCommand.kt:193)
	at org.ossreviewtoolkit.plugins.commands.scanner.ScannerCommand.run(ScannerCommand.kt:153)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:306)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:319)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:40)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:458)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:455)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:475)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:482)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:72)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 30 more
```

**Comment by sschuberth** [comment]
I guess since [you were unable to build the Docker image](https://github.com/oss-review-toolkit/ort/issues/7891), you're running ORT natively. If you do that, you need to manually ensure to have all external tools as indicated by `ort requirements` are installed. This includes ScanCode (if used as the scanner).

**Comment by remi-cogito** [comment]
OK but I ma running ./gradlew installDist from inside ort git repo. How I am suppose to install Scanner, Evaluator, Reporter?

**Comment by sschuberth** [comment]
> How I am suppose to install Scanner, Evaluator, Reporter?

You're not supposed to install the tools that belong to ORT itself; they are part of the distribution created by `installDist`. But you need to ensure that e.g. the *actual* scanner called by ORT's scanner wrapper is install on your host machine and available in `PATH`. So if you're on Linux, basically do `sudo -H pip install scancode-toolkit==32.0.8`, provided that you have a Python 3 version supported by ScanCode installed (up to Python 3.11, but preferably Python 3.8).

**Comment by remi-cogito** [comment]
Great thanks!
