### ISSUE TITLE
Evaluate error: Unable to list the remote branches, not authorized on git

### ISSUE THREAD

**Issue by woznik** [oss-review-toolkit/ort#8232]
Hello
I would like to refer to the closed issue https://github.com/oss-review-toolkit/ort/issues/6400
I have similar case but in EVALUATION phase.
I tried to pass the credentials in .netrc file or even pass to evaluate coammand `--package-types PACKAGE` but 
the oprion is not present in EVALUATION Error: no such option --package-types. same error:
Without the option I encounter following:
```
10:17:05.008 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Trying to download ':::' sources to '/tmp/ort-Companion1745841932715318541' from VCS...
10:17:05.008 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Using processed VcsInfo(type=Git, url=https://gitlab-ci-token@************/opensource/oss-compliance-sample-projects/maven-01.git, revision=8f2a20ce55b2f6633637fe3020aef1511b2b8ed2, path=). Original was VcsInfo(type=, url=, revision=, path=).
10:17:05.052 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
10:17:05.066 [main] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
10:17:05.197 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Detected VCS type 'Git' from type name 'Git'.
10:17:05.399 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for package '' and version '' found: IOException: Cannot guess a revision name from a blank version.
10:17:06.122 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Metadata has invalid Git revision '8f2a20ce55b2f6633637fe3020aef1511b2b8ed2': IOException: Unable to list the remote branches.
Caused by: TransportException: https://gitlab-ci-token@************/opensource/oss-compliance-sample-projects/maven-01.git: not authorized
    Caused by: TransportException: https://gitlab-ci-token@************/opensource/oss-compliance-sample-projects/maven-01.git: not authorized
10:17:06.123 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Falling back to trying to download from https://************/opensource/oss-compliance-sample-projects/maven-01.git which has credentials removed.
10:17:06.208 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - No Git revision for package '' and version '' found: IOException: Cannot guess a revision name from a blank version.
10:17:06.917 [main] INFO  org.ossreviewtoolkit.downloader.VersionControlSystem - Metadata has invalid Git revision '8f2a20ce55b2f6633637fe3020aef1511b2b8ed2': IOException: Unable to list the remote branches.
Caused by: TransportException: https://************/opensource/oss-compliance-sample-projects/maven-01.git: not authorized
    Caused by: TransportException: https://************/opensource/oss-compliance-sample-projects/maven-01.git: not authorized
10:17:07.036 [main] INFO  org.ossreviewtoolkit.downloader.Downloader - Failed attempt to download source code for ':::' from VcsInfo(type=Git, url=https://gitlab-ci-token@************/opensource/oss-compliance-sample-projects/maven-01.git, revision=8f2a20ce55b2f6633637fe3020aef1511b2b8ed2, path=) took 2.028289033s.
10:17:07.047 [main] INFO  org.ossreviewtoolkit.utils.scripting.ScriptRunner - Evaluating the script took 9.916247556s.
Exception in thread "main" org.ossreviewtoolkit.downloader.DownloadException: Download failed for ':::'.
	at org.ossreviewtoolkit.downloader.Downloader.download(Downloader.kt:75)
	at org.ossreviewtoolkit.downloader.Downloader.download$default(Downloader.kt:70)
	at org.ossreviewtoolkit.evaluator.SourceTreeResolver$Companion$forRemoteRepository$1.invoke(SourceTreeResolver.kt:42)
	at org.ossreviewtoolkit.evaluator.SourceTreeResolver$Companion$forRemoteRepository$1.invoke(SourceTreeResolver.kt:36)
```

Is there an option to pass credentials to ORT for gitlab or tell evaluator not to review again the sources that are already checkout in the working directory

the project I want to evaluate is located in my internal gitlab

**Comment by sschuberth** [comment]
> ORT for gitlab

As a general remark, if the issue is specific to / only occurs with the GitLab integration, please considering filing it at https://github.com/oss-review-toolkit/ort-ci-gitlab/issues.

> https://gitlab-ci-token@************/opensource/oss-compliance-sample-projects/maven-01.git: not authorized

Reading this in the log, it seems to me that you simply need to grant the user running the GitLab CI access to your repo.

But as this really looks like a GitLab-integration specific issue, I'm transferring it.
