### ISSUE TITLE
Node package manager: IllegalArgumentExceptions if package author is a list of authors

### ISSUE THREAD

**Issue by wkl3nk** [oss-review-toolkit/ort#9201]
### Describe the bug

Scan of project fails in the analyze phase, generating the following stack trace:

_java.lang.IllegalArgumentException: Element class kotlinx.serialization.json.JsonArray is not a JsonPrimitive
	at kotlinx.serialization.json.JsonElementKt.error(JsonElement.kt:327)
	at kotlinx.serialization.json.JsonElementKt.getJsonPrimitive(JsonElement.kt:230)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.AuthorSerializer.transformDeserialize(PackageJson.kt:138)
	at kotlinx.serialization.json.JsonTransformingSerializer.deserialize(JsonTransformingSerializer.kt:78)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement$lambda$3(Tagged.kt:288)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:294)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:286)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJson$$serializer.deserialize(PackageJson.kt:90)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJson$$serializer.deserialize(PackageJson.kt:90)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:337)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:26)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:186)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJsonKt.parsePackageJson(PackageJson.kt:154)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJsonKt.parsePackageJson(PackageJson.kt:47)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJsonKt.parsePackageJson(PackageJson.kt:45)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.Npm.parsePackage$node_package_manager(Npm.kt:270)
	at org.ossreviewtoolkit.plugins.packagemanagers.node.Npm$parseInstalledModules$2$1$2.invokeSuspend(Npm.kt:253)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
11:23:46.236 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - NPM failed to resolve dependencies for path 'src/xxx/package.json': IllegalArgumentException: Element class kotlinx.serialization.json.JsonArray is not a JsonPrimitive_

First analysis shows that it happens when trying to deserialize author strings like

["Brandon Alexander <baalexander@gmail.com> (https://github.com/baalexander)","Sean Massa <endangeredmassa@gmail.com> (http://massalabs.com)"]

Which in fact is a _JsonArray_, and neither a _JsonObject_ nor a _JsonPrimitive_.
Section in code is in file PackageJson.kt:138

### Expected behavior

Don't know. At least no exception should be thrown.
The model just seems to support **one** author per package, so how to deal with the situation if two authors are specified?

### Environment

* ORT version: 32.1.0
* Java version: 17
* OS: Linux

### Additional context

@fviernau did a rework of the code in early September 2024

**Comment by wkl3nk** [comment]
Does not seem to be a totally strange thing to have more than one author for a package:

https://github.com/baalexander/node-portscanner/blob/master/package.json

**Comment by fb33** [comment]
Hi all,

It's cool to improve robustness of ORT, but in fact, the package.json of portscanner seems really invalid regarding the specification https://docs.npmjs.com/cli/v10/configuring-npm/package-json#people-fields-author-contributors 

author is a string, contributors is an array.

I wonder if it's a good approach to be more permissive than the specification.
By the way, the side effect of an invalid package.json somewhere in the node_modules is that it breaks the global analyse of the audited project. We end up with an empty dependency tree with only "NPM::package.json:" as a name...
Perhaps it's more the robustness of the whole analyse process that should be improved than the parsing of package json. 
It could be interesting to have an issue when parsing a wrong package but having also the rest of the dependency tree without the falsy packag

**Comment by sschuberth** [comment]
> I wonder if it's a good approach to be more permissive than the specification.

That's a very good question, but unfortunately also a difficult one to answer. I guess, as so often, we need to find a balance between staying strict to the specs, but accepting (and warning) about very commonly made mistakes. We do something similar for invalid syntax of Maven SCM connection URLs, for example.

We now have several real-life example for authors being arrays of *strings*, so we should probably tolerate that. But I wouldn't support e.g. an array of *objects*, for example, as I have yet to see any real-life examples for that.
