### ISSUE TITLE
Pub cannot parse Yaml file

### ISSUE THREAD

**Issue by nnobelis** [oss-review-toolkit/ort#9310]
A customer from us started to experience issues with Pub since some time:
```
IncorrectTypeException at dev_dependencies.lint on line 18, column 8: Expected element to be YamlMap but is YamlNull
	at com.charleskorn.kaml.YamlNodeKt.error(YamlNode.kt:278)
	at com.charleskorn.kaml.YamlNodeKt.getYamlMap(YamlNode.kt:272)
	at org.ossreviewtoolkit.plugins.packagemanagers.pub.DependencyMapSerializer.decodeDependency(Pubspec.kt:128)
```

```
08:53:13.076 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.plugins.packagemanagers.pub.Pub - Failed to parse pubspec.yaml for package functional_listener:2.3.1: IncorrectTypeException: Expected element to be YamlMap but is YamlNull
```
The pub file `/home/nino/.pub-cache/hosted/pub.dev/functional_listener-2.3.1/pubspec.yaml`:
```
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
```
Maybe in `YamlNode.decodeDependency()` should check if this is a map ?

Bug happening with ORT 34.0.0.

**Comment by franzlst** [comment]
Additional info: "line 18" is referring to "lint:", which value is supposed to be a map, but is null here.
