### ISSUE TITLE
Analyzer fails with: Option path is required but not set.

### ISSUE THREAD

**Issue by dimitris-iliou** [oss-review-toolkit/ort#9342]
### Describe the bug

```shell
Looking for ORT configuration in the following file:
        /builds/oss/oss-review-toolkit/ort-gitlab-ci/config.yml
Looking for analyzer-specific configuration in the following files and directories:
        /builds/oss/oss-review-toolkit/ort-gitlab-ci/project/.ort.yml (does not exist)
        /builds/oss/oss-review-toolkit/ort-gitlab-ci/ort-configuration/resolutions.yml
The following 25 package manager(s) are enabled:
        Bazel, Bower, Bundler, Cargo, Carthage, CocoaPods, Composer, Conan, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, PNPM, Poetry, Pub, SBT, SpdxDocumentFile, Stack, SwiftPM, Unmanaged, Yarn, Yarn2
Exception in thread "main" java.lang.IllegalStateException: Option path is required but not set.
	at org.ossreviewtoolkit.plugins.packagecurationproviders.file.FilePackageCurationProviderFactory.create(FilePackageCurationProviderFactory.kt:14)
	at org.ossreviewtoolkit.plugins.packagecurationproviders.file.FilePackageCurationProviderFactory.create(FilePackageCurationProviderFactory.kt:9)
	at org.ossreviewtoolkit.plugins.packagecurationproviders.api.PackageCurationProviderFactory$Companion.create(PackageCurationProviderFactory.kt:51)
	at org.ossreviewtoolkit.plugins.commands.analyzer.AnalyzerCommand.run(AnalyzerCommand.kt:167)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.parse(CoreCliktCommand.kt:107)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:78)
	at com.github.ajalt.clikt.core.CoreCliktCommandKt.main(CoreCliktCommand.kt:90)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:87)
``` 

* ORT version: [e.g. 37.0.0]
* Java version: [e.g. 21]
* OS: [e.g. Linux]

The error appeared after building latest ORT version, I am not sure how to proceed with this

**Comment by dimitris-iliou** [comment]
Great, I resolved the issue! I’m using [this filter](https://github.com/oss-review-toolkit/ort/issues?q=label%3A%22breaking+API+change%22%2C%22breaking+change%22%2C%22breaking+configuration+change%22) to track breaking changes, but this one wasn’t included. Are there any additional filters I should consider adding?

**Comment by sschuberth** [comment]
> Great, I resolved the issue!

Good, then let's close the issue.

> Are there any additional filters I should consider adding?

No. We somewhat deprecated the use of PR labels for breaking changes in favor of listing them in the [release notes](https://github.com/oss-review-toolkit/ort/releases) on a per-commit basis. I'd recommend to watch the release notes instead.
