### ISSUE TITLE
WebApp=deduplicateDependencyTree on reports broken after 40.0.0 changes to plugin model

### ISSUE THREAD

**Issue by heliocastro** [oss-review-toolkit/ort#9434]
### Describe the bug

Configuration value is broken after recent move to plugin model.
the option -O WebApp=deduplicateDependencyTree is treated as a boolean instead of value.

### To Reproduce

Pick any evaluation-result.yml and execute:

`ort report -i evaluation-result.yml -o . -f WebApp -O WebApp=deduplicateDependencyTree`

### Expected behavior

Reports generated

### Console / log output

Add console and / or log output that shows the error and additional context.
No screenshots of plain text please, to keep text searchable.

```
 ______________________________                                                               
/        \_______   \__    ___/       The OSS Review Toolkit, version 40.0.0,                 
|    |   | |       _/ |    |          built with JDK 21.0.5+11-LTS, running under Java 21.0.5.
|    |   | |    |   \ |    |          Executing 'report' as 'DHXBWM7' on Mac OS X             
\________/ |____|___/ |____|          with 10 CPUs and a maximum of 8192 MiB of memory.       
                                                                                              
Environment variables:                                                                       
ORT_CONFIG_DIR = /Users/*****/data/ort-config                                              
ORT_DATA_DIR = /Users/*****/.ort                                                           
HOME = /Users/****                                                                       
SHELL = /bin/zsh                                                                             
TERM = xterm-kitty                                                                           
http_proxy = http://*****@127.0.0.1:9000                                                     
https_proxy = http://*****@127.0.0.1:9000                                                    
JAVA_HOME = /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home                   
ANDROID_HOME = /Users/*******/.local/toolchains/android/android-sdk                          
                                                                                             
Looking for ORT configuration in the following file:
        /Users/*****/data/ort/config_host.yml

08:35:44.531 [main] INFO  org.ossreviewtoolkit.plugins.commands.api.utils.ExtensionsKt - Read ORT result from 'evaluation-result.yml' (8,77 MiB) in 871.471042ms.
Generating the 'WebApp' report in thread 'DefaultDispatcher-worker-2'...
Generating the 'EvaluatedModel' report in thread 'DefaultDispatcher-worker-3'...
Exception in thread "main" java.lang.IllegalArgumentException: The string doesn't represent a boolean value: 
	at kotlin.text.StringsKt__StringsKt.toBooleanStrict(Strings.kt:1481)
	at org.ossreviewtoolkit.plugins.reporters.webapp.WebAppReporterFactory.create(WebAppReporterFactory.kt:14)
	at org.ossreviewtoolkit.plugins.reporters.webapp.WebAppReporterFactory.create(WebAppReporterFactory.kt:9)
	at org.ossreviewtoolkit.plugins.commands.reporter.ReporterCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReporterCommand.kt:297)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

### Environment

* ORT version: 40.0.0
* Java version: 21
* OS: MacOS and Linux

**Comment by sschuberth** [comment]
Actually, I believe that if

    ort report -i evaluation-result.yml -o . -f WebApp -O WebApp=deduplicateDependencyTree

worked before, *that* was the bug, and it should explicitly be

   ort report -i evaluation-result.yml -o . -f WebApp -O WebApp=deduplicateDependencyTree=true

Does the latter work for you @heliocastro?

**Comment by sschuberth** [comment]
I just confirmed that the previous default value was also `false`, see

https://github.com/oss-review-toolkit/ort/blob/61e9dd072023adf4a9a86961bdb7f15a9672847c/plugins/reporters/evaluated-model/src/main/kotlin/EvaluatedModelReporter.kt#L60

`toBoolean()` only returns true [if the value is explicitly "true"](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.text/to-boolean.html).

**Comment by heliocastro** [comment]
Ok, THAT's surprised me. Worked and thanks for that @sschuberth. 
I'm closing as "bug from the past"...
